import type { BlogPost } from './data';

type RecordSpec = {
  slug: string; title: string; audience: string; focus: string; outcome: string;
  firstStep: string; check: string; boundary: string; published: '2026-08-13';
};

// These are replacement identities for the rejected campaign. Keep the publication
// date on every source record so provenance checks do not infer it from a batch.
const records: RecordSpec[] = [
  { slug: 'outsourced-assistant-appointment-intake', title: 'Make appointment intake easier to act on', audience: 'a service business receiving appointments through several channels', focus: 'appointment intake', outcome: 'a complete request ready for confirmation', firstStep: 'list the fields needed before a slot can be offered', check: 'the request, time zone, and contact details agree', boundary: 'medical, legal, and priority decisions', published: '2026-08-13' },
  { slug: 'outsourced-assistant-service-inquiry-routing', title: 'Route service inquiries without losing context', audience: 'an owner whose inquiries arrive through email and web forms', focus: 'inquiry routing', outcome: 'each inquiry reaching the right next owner', firstStep: 'define a small set of service and urgency labels', check: 'the handoff includes the original question and source', boundary: 'promising availability, fit, or outcomes', published: '2026-08-13' },
  { slug: 'outsourced-assistant-client-document-chasing', title: 'Follow up on client documents with a clear record', audience: 'a professional service team waiting on client paperwork', focus: 'document follow-up', outcome: 'missing items that are visible and easy to resolve', firstStep: 'make a checklist tied to the client’s approved request', check: 'each reminder names the item and the accepted channel', boundary: 'interpreting documents or changing requirements', published: '2026-08-13' },
  { slug: 'outsourced-assistant-review-request-coordination', title: 'Coordinate review requests without manufacturing praise', audience: 'a local business asking recent customers for feedback', focus: 'review-request coordination', outcome: 'polite, timely requests sent to eligible customers', firstStep: 'confirm the approved trigger and message', check: 'the request is voluntary and tied to a real interaction', boundary: 'incentives, review selection, and writing customer opinions', published: '2026-08-13' },
  { slug: 'outsourced-assistant-shared-drive-permissions', title: 'Keep shared-drive access aligned with the work', audience: 'a growing team with folders shared across projects', focus: 'shared-drive administration', outcome: 'people seeing the folders they need and no more', firstStep: 'map each folder to a role and business purpose', check: 'a sample account has only approved access', boundary: 'security exceptions and retaining access after a role ends', published: '2026-08-13' },
  { slug: 'outsourced-assistant-lead-source-records', title: 'Make lead-source records useful for follow-up', audience: 'a small sales team trying to understand where inquiries begin', focus: 'lead-source records', outcome: 'clean source information attached to each inquiry', firstStep: 'choose the source labels and the original evidence for each', check: 'unknown sources stay unknown instead of being guessed', boundary: 'changing attribution or judging lead quality', published: '2026-08-13' },
  { slug: 'outsourced-assistant-customer-renewal-calendar', title: 'Build a dependable customer renewal calendar', audience: 'a service owner tracking agreement dates across accounts', focus: 'renewal calendar administration', outcome: 'decision dates and owners visible before they become urgent', firstStep: 'collect dates from the approved agreement records', check: 'each calendar entry links back to its source', boundary: 'changing terms or negotiating with customers', published: '2026-08-13' },
  { slug: 'outsourced-assistant-product-catalog-maintenance', title: 'Maintain product catalog details without silent changes', audience: 'a commerce team with many descriptions and attributes to update', focus: 'catalog maintenance', outcome: 'consistent product records ready for review', firstStep: 'separate source facts from display formatting', check: 'every change has a source and reviewer', boundary: 'inventing specifications, claims, or availability', published: '2026-08-13' },
  { slug: 'outsourced-assistant-community-moderation-queue', title: 'Make a community moderation queue easier to review', audience: 'a community owner handling recurring member reports', focus: 'moderation queue administration', outcome: 'reports grouped with context and a clear decision owner', firstStep: 'define report categories and the evidence each needs', check: 'the original report remains attached to the queue item', boundary: 'making final safety, legal, or ban decisions', published: '2026-08-13' },
  { slug: 'outsourced-assistant-webinar-attendee-followup', title: 'Keep webinar attendee follow-up personal and orderly', audience: 'a small team following up after educational events', focus: 'attendee follow-up', outcome: 'attendees receiving the approved next message at the right time', firstStep: 'segment attendees by the action they actually took', check: 'each message matches consent and the event record', boundary: 'adding people to lists or making commercial promises', published: '2026-08-13' },
  { slug: 'outsourced-assistant-business-license-calendar', title: 'Track business license dates before they become surprises', audience: 'an owner responsible for several operational renewals', focus: 'license-date tracking', outcome: 'renewal reminders with source documents and owners', firstStep: 'inventory dates, jurisdictions, and responsible contacts', check: 'each reminder points to the current official record', boundary: 'legal interpretation and filing decisions', published: '2026-08-13' },
  { slug: 'outsourced-assistant-proposal-library-maintenance', title: 'Keep a proposal library accurate and easy to search', audience: 'a service team reusing approved proposal material', focus: 'proposal library maintenance', outcome: 'current examples that do not carry stale claims forward', firstStep: 'label approved, expired, and owner-review content', check: 'every reusable section has a review date', boundary: 'changing scope, terms, or proof points', published: '2026-08-13' },
  { slug: 'outsourced-assistant-membership-record-updates', title: 'Update membership records with a visible audit trail', audience: 'an association or program with recurring member changes', focus: 'membership record updates', outcome: 'accurate status and contact records with traceable edits', firstStep: 'identify the approved source for each field', check: 'old and new values are explainable', boundary: 'eligibility decisions and sensitive record disclosure', published: '2026-08-13' },
  { slug: 'outsourced-assistant-return-request-intake', title: 'Handle return-request intake before a decision is made', audience: 'an online seller managing routine return questions', focus: 'return-request intake', outcome: 'complete cases ready for an authorized decision', firstStep: 'capture order, item, reason, and requested remedy', check: 'the case matches the current order record', boundary: 'approving refunds, exceptions, or chargebacks', published: '2026-08-13' },
  { slug: 'outsourced-assistant-partner-contact-directory', title: 'Keep a partner contact directory trustworthy', audience: 'an operator coordinating with referral and delivery partners', focus: 'partner directory maintenance', outcome: 'current contacts connected to the right relationship', firstStep: 'set a source and review date for every contact', check: 'stale entries are flagged before they are used', boundary: 'sharing private data or changing relationship ownership', published: '2026-08-13' },
  { slug: 'outsourced-assistant-training-session-logistics', title: 'Coordinate training logistics around the learner experience', audience: 'a team arranging recurring training sessions', focus: 'training logistics', outcome: 'participants receiving accurate places, times, and materials', firstStep: 'confirm the roster, time zone, location, and materials', check: 'the final notice matches the approved session record', boundary: 'changing curriculum or assessing performance', published: '2026-08-13' },
  { slug: 'outsourced-assistant-business-trip-expense-records', title: 'Prepare business-trip expense records for review', audience: 'an owner sorting travel receipts after a work trip', focus: 'expense-record preparation', outcome: 'receipts matched to dates and business context', firstStep: 'group receipts by trip and identify missing evidence', check: 'amounts and dates match the original receipt', boundary: 'approving reimbursement or changing tax treatment', published: '2026-08-13' },
  { slug: 'outsourced-assistant-local-event-vendor-coordination', title: 'Keep local-event vendor details from drifting', audience: 'an event organizer coordinating several suppliers', focus: 'vendor coordination', outcome: 'one current record of contacts, deliverables, and open questions', firstStep: 'record the latest approved commitment and its source', check: 'changes are confirmed before they reach the event plan', boundary: 'accepting new terms or committing funds', published: '2026-08-13' },
  { slug: 'outsourced-assistant-client-portal-content-check', title: 'Check client-portal content before customers rely on it', audience: 'a service team maintaining a client-facing portal', focus: 'portal content checks', outcome: 'clear pages with stale or missing details flagged', firstStep: 'compare a page against its named source of truth', check: 'links, dates, and instructions still match', boundary: 'publishing policy changes or technical guarantees', published: '2026-08-13' },
  { slug: 'outsourced-assistant-subscription-cancellation-intake', title: 'Record subscription cancellation requests respectfully', audience: 'a business receiving cancellations through several channels', focus: 'cancellation intake', outcome: 'complete requests routed without pressure or delay', firstStep: 'capture the request, account, date, and preferred confirmation', check: 'the record preserves the customer’s stated request', boundary: 'retention pressure, refunds, and account changes', published: '2026-08-13' },
  { slug: 'outsourced-assistant-office-supply-replenishment', title: 'Make office-supply replenishment predictable', audience: 'a small office that repeatedly runs short of essentials', focus: 'supply replenishment', outcome: 'a reviewed list based on actual usage and approved needs', firstStep: 'set minimum levels for a short list of essentials', check: 'each request names the location and quantity needed', boundary: 'placing unapproved orders or choosing vendors', published: '2026-08-13' },
  { slug: 'outsourced-assistant-referral-followup-records', title: 'Record referral follow-up without losing the relationship', audience: 'a service business receiving introductions from partners', focus: 'referral follow-up records', outcome: 'timely, respectful follow-up with context intact', firstStep: 'record who introduced the inquiry and what was consented', check: 'the next message uses the approved contact path', boundary: 'claiming referral credit or making promises', published: '2026-08-13' }
];

function makePost(record: RecordSpec): BlogPost {
  return {
    slug: record.slug,
    title: record.title,
    published: record.published,
    minutes: 8,
    excerpt: `A practical guide for ${record.audience}: use outsourced assistant support for ${record.focus} while keeping review and decisions clear.`,
    takeaway: `Define ${record.outcome} before handing off ${record.focus}; start with ${record.firstStep}, and keep ${record.boundary} with the owner.`,
    sections: [
      { heading: 'Define the finished record', body: `For ${record.focus}, finished work is ${record.outcome}. Write that result into the brief, name the source of truth, and identify the person who reviews it. A precise finish line makes useful support possible without guessing.` },
      { heading: 'Start with a bounded request', body: `Begin with ${record.firstStep}. Provide one approved example and one exception. This gives the assistant enough context to prepare dependable work while leaving judgment with the person who owns the decision.` },
      { heading: 'Use a check that catches drift', body: `Apply this check before expanding the lane: ${record.check}. Review a small sample, record corrections, and update the example when the same question returns.` },
      { heading: 'Protect the decision boundary', body: `Pause when work reaches ${record.boundary}. Preserve the relevant context, state what is missing, and route it to the named owner. A clear boundary is part of good service, not a delay.` },
      { heading: 'Leave a readable handoff', body: `End with completed items, items waiting for review, open questions, and the next action. Keep the note beside the source record so the owner can understand status without reconstructing it from messages.` },
      { heading: 'Improve from real corrections', body: `After the first few cycles, look for repeated corrections in ${record.focus}. Improve the brief, permission, or example that caused the confusion. Small evidence-based changes make the next handoff easier to trust.` }
    ],
    faqs: [
      { q: `What if ${record.focus} is unclear?`, a: 'Pause, record the missing context, and use the agreed escalation path. Do not guess at a customer-facing or irreversible decision.' },
      { q: 'What should the owner review first?', a: 'Review a small initial sample closely, then use a consistent sample only after accuracy and escalation judgment are stable.' },
      { q: 'What belongs in the handoff?', a: 'Include the trigger, source of truth, finished result, examples, approval boundary, and route for questions.' }
    ],
    internalLinks: [{ href: '/resources/assistant-sop-handoff-checklist', label: 'Assistant handoff checklist' }, { href: '/services', label: 'Outsourced assistant services' }]
  };
}

export const dailyBlogBatch20260813: BlogPost[] = records.map(makePost);
