import type { BlogPost } from './data';

type Topic = {
  slug: string;
  title: string;
  audience: string;
  focus: string;
  result: string;
  firstStep: string;
  check: string;
  boundary: string;
  published?: '2026-08-13';
};

const topics: Topic[] = [
  { slug: 'filipino-virtual-assistant-inbox-zero', title: 'A calmer inbox with a Filipino virtual assistant', audience: 'a founder with a crowded shared inbox', focus: 'inbox triage', result: 'a short list of messages that truly need the owner', firstStep: 'separate newsletters, routine requests, and decisions', check: 'every label leads to a named next action', boundary: 'private legal, banking, and relationship-sensitive messages', published: '2026-08-13' },
  { slug: 'filipino-virtual-assistant-calendar-conflicts', title: 'Prevent calendar conflicts with Filipino assistant support', audience: 'an operator coordinating several people', focus: 'calendar coordination', result: 'meetings that have an owner, purpose, and realistic time', firstStep: 'map fixed commitments before offering open slots', check: 'the invite and time zone match the approved request', boundary: 'moving priority meetings or making promises for attendees', published: '2026-08-13' },
  { slug: 'filipino-virtual-assistant-customer-support-queues', title: 'Make customer support queues easier to trust', audience: 'a small service team handling recurring questions', focus: 'support queue administration', result: 'customers receiving consistent first responses', firstStep: 'group requests by answer type and urgency', check: 'each response uses an approved answer and clear handoff', boundary: 'refund decisions, sensitive data, and policy exceptions' },
  { slug: 'filipino-virtual-assistant-lead-follow-up', title: 'Keep warm leads moving with Filipino assistant support', audience: 'an owner who loses track of promising conversations', focus: 'lead follow-up', result: 'a visible next step for every active conversation', firstStep: 'define which replies are approved and which need review', check: 'the record shows the last contact and next action', boundary: 'commercial promises, qualification decisions, and negotiations' },
  { slug: 'filipino-virtual-assistant-crm-data-cleanup', title: 'Improve CRM records without losing useful history', audience: 'a sales team whose records have grown inconsistent', focus: 'CRM data cleanup', result: 'records that can be searched and reported consistently', firstStep: 'agree on canonical fields and obvious duplicate rules', check: 'changed records can be traced to their source', boundary: 'deleting history, changing ownership, and altering forecasts' },
  { slug: 'filipino-virtual-assistant-research-source-notes', title: 'Turn research into useful source notes', audience: 'an operator who needs evidence before making a decision', focus: 'source-note preparation', result: 'dated notes that separate facts, interpretation, and open questions', firstStep: 'name the decision and the sources worth checking', check: 'each important claim points to its original source', boundary: 'legal, medical, financial, or strategic conclusions' },
  { slug: 'filipino-virtual-assistant-content-calendar-maintenance', title: 'Keep a content calendar useful to the whole team', audience: 'a business publishing practical customer education', focus: 'content calendar maintenance', result: 'clear topics, owners, review dates, and approved next steps', firstStep: 'remove vague ideas and define the audience for each entry', check: 'no item is marked ready without an owner review', boundary: 'inventing claims or publishing without approval' },
  { slug: 'filipino-virtual-assistant-invoice-record-prep', title: 'Prepare invoice records while keeping payment control', audience: 'a business with recurring client billing', focus: 'invoice record preparation', result: 'complete records ready for an authorized review', firstStep: 'match each record to approved work and a source document', check: 'differences are listed instead of silently corrected', boundary: 'bank changes, payment approval, and money movement' },
  { slug: 'filipino-virtual-assistant-vendor-request-tracking', title: 'Make vendor follow-up visible and respectful', audience: 'an operations owner managing several suppliers', focus: 'vendor request tracking', result: 'open questions with dates, owners, and useful replies', firstStep: 'record the request, promised response, and last contact', check: 'overdue items are escalated with the original context', boundary: 'contract changes and unauthorized commitments' },
  { slug: 'filipino-virtual-assistant-meeting-action-items', title: 'Turn meeting notes into accountable action items', audience: 'a team where decisions disappear after calls', focus: 'meeting action tracking', result: 'decisions and next actions that people can verify', firstStep: 'capture the decision, owner, due date, and unresolved question', check: 'the summary is approved before it is shared externally', boundary: 'rewriting decisions or distributing confidential discussion' },
  { slug: 'filipino-virtual-assistant-digital-file-organization', title: 'Build a findable digital filing system', audience: 'a growing business with scattered shared files', focus: 'digital file organization', result: 'records that are easy to locate without unsafe sharing', firstStep: 'choose names, folders, and an index for one work area', check: 'a second person can find a sample without coaching', boundary: 'deleting records or changing retention decisions' },
  { slug: 'filipino-virtual-assistant-ecommerce-order-questions', title: 'Handle routine ecommerce order questions carefully', audience: 'a store owner balancing customer messages and fulfillment', focus: 'order-question handling', result: 'fast answers for ordinary status questions', firstStep: 'separate tracking, address, return, and exception requests', check: 'the answer matches the current order record', boundary: 'refunds, chargebacks, and address changes' },
  { slug: 'filipino-virtual-assistant-real-estate-listing-admin', title: 'Support real-estate listing administration with clear limits', audience: 'a real-estate team with many listing details to maintain', focus: 'listing administration', result: 'current records and fewer missed document deadlines', firstStep: 'create a source-of-truth list for each property', check: 'every update includes its source and review date', boundary: 'legal advice, pricing claims, and client promises' },
  { slug: 'filipino-virtual-assistant-coach-client-admin', title: 'Give coaches more room with dependable client administration', audience: 'a coach or agency owner doing too much coordination', focus: 'client administration', result: 'prepared sessions and visible outstanding details', firstStep: 'list the client-facing tasks that do not require advice', check: 'every client message has the right approved tone', boundary: 'client advice, scope changes, and sensitive disclosures' },
  { slug: 'filipino-virtual-assistant-sales-call-preparation', title: 'Prepare sales calls without overpromising', audience: 'a founder who wants context before each conversation', focus: 'sales-call preparation', result: 'briefs that help the owner ask better questions', firstStep: 'collect only approved context from the named sources', check: 'unknowns are listed rather than filled with guesses', boundary: 'claims about fit, outcomes, or commercial terms' },
  { slug: 'filipino-virtual-assistant-weekly-operations-report', title: 'Create a weekly operations report people can act on', audience: 'an owner who needs a clear view of work in progress', focus: 'weekly operations reporting', result: 'a concise view of completed work, blockers, and decisions', firstStep: 'agree on definitions for done, late, waiting, and blocked', check: 'every number can be traced back to a source', boundary: 'inventing figures or presenting interpretation as fact' },
  { slug: 'filipino-virtual-assistant-sop-documentation', title: 'Document repeatable work so handoffs improve', audience: 'a team whose instructions live in scattered messages', focus: 'task documentation', result: 'short reference pages with examples and exceptions', firstStep: 'observe one real task from trigger to finished result', check: 'a new reviewer can identify the finish line', boundary: 'hiding unclear ownership behind a long document' },
  { slug: 'filipino-virtual-assistant-philippines-time-zone-handoff', title: 'Make a Philippines time-zone handoff predictable', audience: 'an owner and assistant working different hours', focus: 'time-zone handoff', result: 'continuity without assuming someone is always available', firstStep: 'write the overlap window and the approved urgent path', check: 'the end-of-shift note names finished, waiting, and blocked work', boundary: 'urgent decisions outside the named escalation route' },
  { slug: 'filipino-virtual-assistant-offboarding-access-review', title: 'Close assistant access cleanly when a role changes', audience: 'a business ending or reshaping a support role', focus: 'access offboarding', result: 'closed accounts and a complete transfer of open work', firstStep: 'inventory accounts, folders, sessions, and unfinished tasks', check: 'each access item has a removal owner and confirmation', boundary: 'keeping shared credentials or quietly retaining access' },
  { slug: 'filipino-virtual-assistant-project-coordination', title: 'Delegate project coordination without changing scope', audience: 'a small team with too many moving deadlines', focus: 'project coordination', result: 'visible owners, dates, dependencies, and exceptions', firstStep: 'map the next milestone and the facts needed to report it', check: 'a change is recorded rather than buried in a message', boundary: 'changing scope or promising a delivery date' },
  { slug: 'filipino-virtual-assistant-data-entry-accuracy', title: 'Raise data-entry accuracy with simple controls', audience: 'a team relying on records entered by hand', focus: 'data-entry accuracy', result: 'complete records that another person can trust', firstStep: 'identify required fields and the original source for each one', check: 'conflicts are flagged instead of guessed away', boundary: 'changing source records or inferring identity' },
  { slug: 'filipino-virtual-assistant-client-onboarding-admin', title: 'Give client onboarding a dependable first week', audience: 'a service business welcoming several clients at once', focus: 'client onboarding administration', result: 'new clients seeing clear next steps and fewer missing details', firstStep: 'map approved welcome messages, setup tasks, and owners', check: 'each client record shows consent, status, and next action', boundary: 'sensitive disclosures and promises about service outcomes' }
];

function makePost(topic: Topic): BlogPost {
  return {
    slug: topic.slug, title: topic.title, published: '2026-08-13', minutes: 8,
    excerpt: `A practical guide for ${topic.audience}: use Filipino assistant support for ${topic.focus} while keeping decisions, access, and review clear.`,
    takeaway: `Define ${topic.result} before handing off ${topic.focus}; start with ${topic.firstStep}, and keep ${topic.boundary} with the owner.`,
    sections: [
      { heading: 'Name the finish line', body: `For ${topic.focus}, finished work is ${topic.result}. Write that sentence into the brief, then name the source of truth, the due point, and the person who reviews the result. A narrow finish line helps a Filipino assistant know when to stop and ask.` },
      { heading: 'Start with the smallest useful lane', body: `Begin with ${topic.firstStep}. Show one good example and one exception. The assistant can then work from evidence instead of guessing what the owner meant by a broad request.` },
      { heading: 'Check the work before expanding it', body: `Use this check at the start: ${topic.check}. Review a small sample closely, record corrections, and add examples where the same question repeats. Expand the lane only when the evidence supports it.` },
      { heading: 'Keep decisions with the right owner', body: `Pause when work reaches ${topic.boundary}. Save the relevant context, state what is missing, and route it to the named owner. This protects the customer and the assistant from an irreversible guess.` },
      { heading: 'Make the handoff readable', body: `End each work period with completed items, items waiting for review, open questions, and the next action. Keep that note beside the source record so the owner can understand the status without reconstructing it from chat.` },
      { heading: 'Improve one example at a time', body: `After the first week, look for repeated corrections in ${topic.focus}. Fix the brief, permissions, or example that caused the confusion. A better handoff makes good work easier to repeat and makes exceptions easier to spot.` }
    ],
    faqs: [
      { q: `What should the assistant do when ${topic.focus} is unclear?`, a: 'Pause, record the missing context, and use the agreed escalation path. Do not guess at a customer-facing or irreversible decision.' },
      { q: 'How much should the owner review at the beginning?', a: 'Review the first small sample closely, then move to a consistent sample only after accuracy and escalation judgment are stable.' },
      { q: 'What belongs in the handoff brief?', a: 'Include the trigger, source of truth, finished result, examples, approval boundary, and the route for questions.' }
    ],
    internalLinks: [{ href: '/resources/assistant-sop-handoff-checklist', label: 'Assistant handoff checklist' }, { href: '/services', label: 'Filipino assistant services' }]
  };
}

export const dailyBlogBatch20260813: BlogPost[] = topics.map(makePost);
