import type { BlogPost } from './data';

type Spec = {
  slug: string; title: string; excerpt: string; audience: string; workflow: string;
  record: string; inputs: string; boundary: string; example: string; metric: string; image: string;
};

const specs: Spec[] = [
  { slug:'virtual-assistant-shared-inbox-triage', title:'How to set up shared inbox triage for a virtual assistant', excerpt:'A bounded inbox routine can shorten response times while keeping sensitive, contractual, and high-impact messages with the right owner.', audience:'a small business with a busy shared email address', workflow:'shared inbox triage', record:'inbox routing register', inputs:'message ID, sender, received time, approved category, priority signal, account owner, draft status, escalation reason, and next review time', boundary:'Pause for threats, legal notices, payment disputes, security reports, sensitive personal data, cancellations, or any message requiring an undocumented promise.', example:'A customer asks for a refund and mentions a chargeback. The assistant tags the message, preserves the original wording, and routes it to the account owner without approving or denying money.', metric:'first-sort time, correctly routed messages, drafts approved without correction, missed escalation signals, reopened threads, and aging by owner', image:'/images/blog-2026-08-20/cross-timezone-queue-status-note.png' },
  { slug:'virtual-assistant-calendar-gatekeeping-workflow', title:'Build a calendar gatekeeping workflow for a virtual assistant', excerpt:'A calendar gatekeeping routine protects focus time without allowing an assistant to accept commitments or disclose private schedule details.', audience:'a founder or manager with frequent meeting requests', workflow:'calendar gatekeeping', record:'meeting request queue', inputs:'requester, purpose, source, attendees, duration, time zone, required decision, approved priority, conflicts, and calendar owner', boundary:'Stop when the purpose is unclear, attendance creates a conflict, confidential calendar details may be exposed, travel is affected, or the request commits money or authority.', example:'A vendor asks for an urgent meeting and requests the names of other attendees already booked. The assistant offers approved windows without exposing private calendar entries.', metric:'requests resolved, protected focus blocks, reschedules, unclear-purpose escalations, time-zone errors, and meetings accepted by the owner', image:'/images/blog-2026-08-20/remote-meeting-preparation-brief.png' },
  { slug:'virtual-assistant-crm-data-cleanup-rules', title:'Create safe CRM data-cleanup rules for a virtual assistant', excerpt:'A source-linked cleanup lane can improve CRM usefulness without silently merging people, erasing history, or inventing customer facts.', audience:'a sales or service team with inconsistent CRM records', workflow:'CRM data cleanup', record:'CRM correction log', inputs:'record ID, field in question, current value, authoritative source, proposed value, duplicate candidate, account owner, approval state, and change time', boundary:'Pause before merging records, deleting history, changing consent, reassigning ownership, altering deal values, or resolving conflicting sources.', example:'Two contacts share a company and surname but use different email addresses. The assistant flags a possible duplicate and leaves both records intact until the owner verifies identity.', metric:'source-backed corrections, duplicate candidates reviewed, rejected changes, consent exceptions, reopened records, and corrections sampled for accuracy', image:'/images/blog-2026-08-20/shared-drive-filing-conventions-assistant.png' },
  { slug:'virtual-assistant-service-kickoff-readiness-gate', title:'Build a service kickoff readiness gate for a virtual assistant', excerpt:'A documented readiness gate prevents a service kickoff from beginning with missing approvals, unsafe access, or an unowned customer decision.', audience:'a service business preparing approved customer projects for delivery', workflow:'service kickoff readiness review', record:'kickoff readiness board', inputs:'project ID, signed scope reference, required inputs, access request, kickoff date, delivery owner, approval evidence, open dependency, and readiness state', boundary:'Stop when scope is unsigned, credentials would be shared insecurely, promised dates conflict, a new deliverable appears, or a required owner has not accepted the handoff.', example:'A project appears ready, but the customer requests access for an extra contractor not named in the approved setup. The assistant holds the readiness state and routes the access decision.', metric:'ready projects, missing approvals, access exceptions, kickoff holds, owner decisions overdue, and false-ready findings', image:'/images/blog-2026-08-20/outsourced-article-outline-approval.png' },
  { slug:'virtual-assistant-password-reset-request-routing', title:'Route password-reset requests safely with a virtual assistant', excerpt:'A narrow identity-check and routing lane can speed account recovery without giving an assistant power to bypass security controls.', audience:'a company receiving routine account-access questions', workflow:'password-reset request routing', record:'account recovery intake log', inputs:'case ID, claimed account, approved verification state, request channel, reset method offered by the system, suspicious signal, security owner, and outcome', boundary:'Escalate failed verification, changed contact details, unusual urgency, requests to disable safeguards, administrator accounts, or any attempt to obtain or transmit a password.', example:'A caller says their email is unavailable and asks the assistant to send a reset link to a new address. The assistant makes no account change and routes the case to security review.', metric:'verified requests routed, self-service completions, failed checks, suspicious cases, policy deviations, and recovery time after owner approval', image:'/images/blog-2026-08-20/least-privilege-tool-onboarding-assistant.png' },
  { slug:'virtual-assistant-project-status-reporting-cadence', title:'Set a project status-reporting cadence for a virtual assistant', excerpt:'A structured status routine turns scattered updates into a decision-ready view without letting the assistant conceal uncertainty or declare work complete.', audience:'a delivery team coordinating several active projects', workflow:'project status reporting', record:'weekly project status brief', inputs:'project ID, milestone, owner update, evidence link, due date, dependency, risk wording, decision needed, next action, and update time', boundary:'Stop when owners disagree, evidence is missing, a deadline must move, scope changes, budget is affected, or a risk could harm a customer.', example:'A task is marked done in chat but the promised customer file is absent. The assistant reports the mismatch as unresolved instead of converting the informal message into completion.', metric:'updates received on time, unsupported completion claims, aging dependencies, decisions requested, deadline changes approved, and stale projects', image:'/images/blog-2026-08-20/remote-project-dependency-register.png' },
  { slug:'virtual-assistant-purchase-order-match-preparation', title:'Prepare purchase-order matches with a virtual assistant', excerpt:'A three-record preparation lane can surface purchasing discrepancies without authorising payment or changing supplier terms.', audience:'an operations or finance team reviewing supplier invoices', workflow:'purchase-order match preparation', record:'purchase match exception file', inputs:'supplier, purchase order, receipt evidence, invoice number, quantities, line prices, tax shown, variance, requester, and finance reviewer', boundary:'Pause for unmatched suppliers, changed bank details, duplicate invoices, price or quantity variance, missing receipt evidence, disputed goods, or pressure to release payment.', example:'An invoice matches the order total but lists a new bank account. The assistant flags the change and follows the independent verification route instead of updating payment details.', metric:'clean matches, duplicate candidates, price variances, receipt gaps, payment-detail changes, and exceptions resolved by finance', image:'/images/blog-2026-08-20/delegated-invoice-exception-notes.png' },
  { slug:'virtual-assistant-customer-renewal-reminder-workflow', title:'Build a customer renewal-reminder workflow for a virtual assistant', excerpt:'A renewal reminder lane can prevent quiet expirations while keeping pricing, negotiation, eligibility, and contract interpretation with the account owner.', audience:'a subscription or recurring-service business', workflow:'customer renewal reminders', record:'renewal readiness queue', inputs:'account ID, agreement source, renewal date, notice window, approved terms, usage summary source, account owner, customer response, and next action', boundary:'Stop when terms conflict, pricing is questioned, cancellation is requested, usage is disputed, a concession is sought, or the agreement does not clearly support the reminder.', example:'A customer replies that an earlier email promised a lower renewal price. The assistant attaches both sources and routes the discrepancy without confirming either price.', metric:'renewals identified, reminders sent on time, source conflicts, owner decisions, cancellation requests routed, and outcomes recorded', image:'/images/blog-2026-08-20/filipino-assistant-service-recovery-routing.png' },
  { slug:'virtual-assistant-candidate-application-completeness-review', title:'Delegate candidate application completeness checks to a virtual assistant', excerpt:'A completeness review can keep recruiting records organised without allowing an assistant to rank candidates or infer missing personal information.', audience:'a recruiting team processing applications at volume', workflow:'application completeness review', record:'candidate document checklist', inputs:'candidate ID, consent state, required document type, received status, file source, role, recruiter, permitted reminder, accessibility request route, and retention state', boundary:'Stop before assessing merit, inferring protected traits, rejecting a person, interpreting credentials, requesting unnecessary data, or handling accommodation details outside the approved route.', example:'A résumé lacks a date the form normally requests. The assistant asks only for the approved missing item and does not infer age or employment gaps.', metric:'complete packets, approved reminders, unnecessary-data catches, accessibility escalations, recruiter review time, and checklist corrections', image:'/images/blog-2026-08-20/assistant-training-sample-review.png' },
  { slug:'virtual-assistant-vendor-onboarding-document-check', title:'Use a virtual assistant for vendor onboarding document checks', excerpt:'A documented vendor intake gate makes missing evidence visible while leaving approval, risk acceptance, and commercial decisions with specialists.', audience:'a business adding suppliers or independent contractors', workflow:'vendor onboarding document review', record:'vendor readiness checklist', inputs:'vendor legal name, requester, agreement status, tax form status, insurance source, security review state, payment-detail verification, owner, and unresolved exception', boundary:'Stop for name mismatches, changed bank details, missing agreements, sanctions or security concerns, coverage interpretation, or requests to start work before approval.', example:'A vendor emails bank details from a different domain after submitting its form. The assistant freezes the field and routes independent verification to finance.', metric:'complete vendor packets, identity mismatches, payment-detail exceptions, overdue reviewers, premature-start requests, and approved vendors', image:'/images/blog-2026-08-20/remote-project-dependency-register.png' },
  { slug:'virtual-assistant-review-response-drafting', title:'Create a review-response drafting lane for a virtual assistant', excerpt:'A review workflow can help a business respond consistently without fabricating events, exposing customer data, or promising an unapproved remedy.', audience:'a service business receiving public customer reviews', workflow:'public review response drafting', record:'review response queue', inputs:'platform, review URL, reviewer display name, verified customer match state, public claims, internal owner, approved facts, draft, escalation reason, and publish approval', boundary:'Stop for threats, legal claims, health or safety allegations, personal data, refund demands, unverifiable events, or any response that admits fault or promises compensation.', example:'A reviewer describes an order the team cannot match to a record. The assistant drafts a privacy-safe invitation to contact support rather than denying the experience.', metric:'response time, drafts approved, privacy edits, unverifiable reviews, specialist escalations, and reopened customer cases', image:'/images/blog-2026-08-20/outsourced-vendor-research-evidence-map.png' },
  { slug:'virtual-assistant-expense-report-preflight-check', title:'Run expense-report preflight checks with a virtual assistant', excerpt:'A preflight checklist can reduce finance rework while keeping reimbursement, tax treatment, and policy exceptions with authorised reviewers.', audience:'a growing company processing employee expenses', workflow:'expense report preflight review', record:'expense completeness queue', inputs:'report ID, submitter, period, receipt state, currency, business-purpose field, policy category, duplicate signal, exception note, and finance owner', boundary:'Stop for missing or altered evidence, personal or disputed charges, duplicate uncertainty, tax questions, policy exceptions, manager conflicts, or requests to change an amount.', example:'Two meals on the same day have identical totals but different receipts. The assistant flags the duplicate signal and preserves both records for finance review.', metric:'complete reports, missing receipts, duplicate signals, policy exceptions, resubmissions, and finance review time', image:'/images/blog-2026-08-20/delegated-invoice-exception-notes.png' },
];

const makePost = (x: Spec): BlogPost => ({
  slug:x.slug, title:x.title, excerpt:x.excerpt, minutes:9, published:'2026-09-22',
  image:{url:x.image,alt:`Operational workflow illustration for ${x.workflow}`},
  takeaway:`Define a source-linked ${x.record}, a narrow action boundary, and a named owner before delegating ${x.workflow}.`,
  sections:[
    {heading:`Start with the customer decision, not a list of tasks`,paragraphs:[`${x.excerpt} This matters for ${x.audience} because “follow up” or “keep this updated” can hide several different decisions. Write down the result the business needs, the evidence the assistant may use, and the person who owns every consequential choice.`, `A useful delegation brief separates preparation from authority. The assistant can gather approved facts, update a queue, draft a bounded message, and surface an exception. The owner still decides price, policy, legal meaning, sensitive disclosure, access, money, or a commitment to a customer. That distinction makes the role more useful because routine work can move without accidental promises.`]},
    {heading:`Define the ${x.record}`,paragraphs:[`Build one ${x.record} with ${x.inputs}. Each field should have a purpose. If a field will not change routing, prove completion, or help the reviewer decide, leave it out. Fewer well-defined fields are safer than a large form that invites private or speculative notes.`, `Name the source beside every important value. A date from an approved system is different from a date mentioned in an email, and both are different from an assistant’s assumption. Use plain states such as new, waiting for evidence, ready for review, approved, declined, and closed. A blank approval field never means approved.`]},
    {heading:`Write the authority boundary in observable terms`,paragraphs:[`${x.boundary} Put that stopping rule in the operating checklist and show the assistant the safe state in which to leave the item. “Use judgment” is not a boundary; a condition, prohibited action, owner, and response window are.`, `Tool access does not expand decision authority. The ability to edit a CRM, scheduling tool, spreadsheet, help desk, or accounting system only enables the documented step. Use the least access needed, separate draft from publish where the platform allows it, and review permissions when the lane changes.`]},
    {heading:`Design intake that survives a handoff`,paragraphs:[`Require a stable identifier, the requester’s exact wording where relevant, the source checked, the current state, and the next named actor. A colleague starting later should not need private chat history to understand what happened. In a Philippines-based support model, include the canonical time zone and the owner’s review window so a local date display does not alter a deadline.`, `Do not make completeness a reason to collect unnecessary personal data. Record only what the approved workflow needs, store it in the approved system, and link rather than duplicate sensitive documents. If information arrives through the wrong channel, preserve the minimum needed for routing and follow the company’s security or privacy procedure.`]},
    {heading:`Test the routine with a realistic exception`,paragraphs:[`${x.example} This is the kind of case that reveals whether the workflow protects the customer and the business when the happy path stops. Test examples before launch: a missing source, a conflicting record, an urgent request, an identity mismatch, and an owner who is temporarily unavailable.`, `For each test, ask four questions: What can the assistant verify? What must remain unchanged? Who receives the escalation? What evidence lets that person decide? Revise the checklist until two reviewers would route the same case the same way. The goal is repeatable restraint as well as speed.`]},
    {heading:`Create messages that do not overpromise`,paragraphs:[`Give the assistant approved message components for acknowledgment, a factual status update, a request for a missing item, and an escalation notice. The wording should identify what was received, what is still needed, and when the next update is expected without implying an outcome that has not been approved.`, `Avoid scripts that pretend every case is identical. Let the assistant select only from approved statements supported by the record. When the customer asks a new question, attach it to the item and route it. A fast but unsupported answer creates more work than a precise acknowledgment with a real next step.`]},
    {heading:`Plan the owner review window`,paragraphs:[`Delegation fails when prepared decisions wait in an invisible queue. Assign a primary reviewer, a backup for defined conditions, and a realistic review window based on consequence. The assistant should know when to remind, when to use the backup route, and when the item must remain paused.`, `Batch ordinary questions at a predictable time and interrupt only for the written urgent conditions. This keeps the owner from becoming the bottleneck while preventing urgency from turning into permission. Record the reviewer’s answer, any conditions or expiry, and whether it applies only to this case or changes the standing procedure.`]},
    {heading:`Measure quality before volume`,paragraphs:[`Review ${x.metric}. Interpret the counts together. Fewer escalations may mean clearer inputs, or they may mean the assistant is making hidden decisions. Faster closure may reflect a better process, or it may hide items closed without customer confirmation.`, `Sample ordinary completed items as well as every high-consequence exception during the launch period. Check source fidelity, correct status, minimal data handling, boundary compliance, message accuracy, and a reconstructable close. Only compare speed after those basics pass.`]},
    {heading:`Launch with a small, representative sample`,paragraphs:[`Choose a sample that includes ordinary requests, missing information, conflicts, and at least one stopping condition. Keep consequential actions in draft or review mode. The manager should compare the assistant’s record with the original source and explain corrections against the written rule rather than relying on preference.`, `Update the procedure when the same ambiguity repeats, but preserve the prior version and effective date. One owner exception is not automatically a new standing rule. A strong first week produces a clearer workflow, not merely a larger completed count.`]},
    {heading:`Turn the workflow into a hiring brief`,paragraphs:[`When evaluating an assistant, describe the systems, volume range, work hours, communication channel, review owner, and boundary cases in addition to the task name. Ask candidates to work through a sample and explain what they would verify, record, escalate, and leave unchanged.`, `OutsourcingAssistant.com can help map the role around this workflow and the surrounding administrative work. Bring the current process, example requests, tools, time-zone coverage, and approval map to a staffing conversation. The aim is a role that removes repeatable preparation from the owner while keeping business decisions with accountable people.`]}
  ],
  faqs:[
    {q:`What can a virtual assistant own in ${x.workflow}?`,a:`Source-linked intake, approved follow-up, status maintenance, preparation, and escalation can be delegated when the workflow defines them clearly.`},
    {q:'What should remain with the business owner or specialist?',a:'Keep consequential judgment, money, contractual or legal interpretation, sensitive disclosure, policy exceptions, and customer commitments with the authorised person.'},
    {q:'How should the first week be reviewed?',a:'Use a representative sample, inspect source fidelity and boundary decisions, correct the written rule, and expand access only after the sample is reliable.'}
  ],
  citations:[
    {name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework',note:'Primary framework for governance, roles, access, and risk-management context.'},
    {name:'U.S. Small Business Administration: Hire and manage employees',url:'https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees',note:'Primary small-business guidance for defining roles and managing staff.'},
    {name:'Federal Trade Commission: Protecting personal information',url:'https://www.ftc.gov/business-guidance/privacy-security/protecting-personal-information',note:'Primary guidance for limiting, protecting, and disposing of personal information.'}
  ],
  internalLinks:[
    {href:'/resources/assistant-sop-handoff-checklist',label:'Build the assistant handoff checklist'},
    {href:'/services',label:'Review virtual assistant service options'},
    {href:'/contact',label:'Discuss a role built around this workflow'}
  ],
  cta:{href:'/contact',label:'Plan the assistant role'}
});

export const dailyBlogBatch20260922: BlogPost[] = specs.map(makePost);
