import type { BlogPost } from './data';

type Spec = { slug:string; title:string; excerpt:string; lane:string; artifact:string; inputs:string; boundary:string; example:string; image:string };
const specs: Spec[] = [
  {slug:'virtual-assistant-daily-priority-reset',title:'Run a daily priority reset with a virtual assistant',excerpt:'A ten-minute reset keeps yesterday’s assumptions out of today’s queue.',lane:'daily operations',artifact:'priority reset note',inputs:'open work, today’s deadlines, dependencies, and the owner’s stated priorities',boundary:'The assistant may reorder routine preparation inside written rules; only the owner can cancel work or change a customer commitment.',example:'A rush request arrives while two promised deliverables are open. The assistant flags the collision and offers two sequences instead of silently choosing.',image:'/images/blog-2026-08-20/cross-timezone-queue-status-note.png'},
  {slug:'assistant-inbox-vip-sender-rulebook',title:'Create inbox VIP rules an assistant can apply safely',excerpt:'VIP labels work when they describe handling rules, not personal importance.',lane:'inbox operations',artifact:'VIP sender rulebook',inputs:'approved senders, message types, response windows, privacy limits, and escalation routes',boundary:'The assistant can label and prepare a draft, but cannot infer urgency, disclose private mail, or promise a response for the owner.',example:'A known investor writes from a new address. The assistant verifies through an approved channel before treating the message as trusted.',image:'/images/blog-2026-08-20/remote-meeting-preparation-brief.png'},
  {slug:'customer-support-macro-change-log',title:'Keep a change log for assistant-used support macros',excerpt:'A small macro log prevents yesterday’s approved reply from becoming today’s policy mistake.',lane:'customer support',artifact:'macro change log',inputs:'current macro, policy source, approver, effective date, affected ticket types, and rollback note',boundary:'The assistant may suggest clearer wording; refunds, guarantees, policy changes, and legal claims require the named owner.',example:'Shipping terms change for one region. The assistant marks the old macro inactive and routes the regional replacement for approval.',image:'/images/blog-2026-08-20/filipino-assistant-service-recovery-routing.png'},
  {slug:'crm-lost-lead-reason-review',title:'Review lost-lead reasons without letting CRM labels become guesses',excerpt:'A reviewable lost-lead queue separates evidence from a convenient dropdown choice.',lane:'sales operations',artifact:'lost-lead review queue',inputs:'last contact, stated objection, opportunity stage, owner, source message, and permitted reason codes',boundary:'The assistant may classify explicit evidence and flag ambiguity; the sales owner decides disputed causes and forecasting changes.',example:'A prospect stops replying after asking about price. The record stays “no response,” not “too expensive,” unless the prospect actually said so.',image:'/images/blog-2026-08-21/filipino-assistant-data-cleanup-scope.png'},
  {slug:'executive-assistant-travel-document-check',title:'Use a travel-document check without turning an assistant into an adviser',excerpt:'Travel preparation is safer when document facts, official sources, and traveler decisions stay separate.',lane:'executive support',artifact:'travel document check',inputs:'traveler-confirmed nationality, itinerary, official destination guidance, document expiry, and verification time',boundary:'The assistant can gather official links and identify missing information; the traveler owns eligibility decisions and professional advice.',example:'Two government pages appear to disagree about validity. The assistant preserves both links and escalates instead of summarizing a definitive answer.',image:'/images/blog-2026-08-20/outsourced-vendor-research-evidence-map.png'},
  {slug:'vendor-insurance-certificate-review-queue',title:'Build a vendor insurance certificate review queue',excerpt:'A certificate queue can expose missing dates and names without asking an assistant to judge coverage.',lane:'vendor administration',artifact:'certificate review queue',inputs:'vendor legal name, certificate, policy dates, requested limits, contract reference, and reviewer',boundary:'The assistant may check completeness and exact matches; a qualified owner decides whether coverage satisfies the contract.',example:'The certificate names a trading name while the contract uses a legal entity. The assistant records the mismatch and pauses acceptance.',image:'/images/blog-2026-08-20/delegated-invoice-exception-notes.png'},
  {slug:'assistant-meeting-pre-read-deadline',title:'Set a pre-read deadline an assistant can enforce consistently',excerpt:'A pre-read cutoff protects review time only when late material has a defined route.',lane:'meeting administration',artifact:'pre-read readiness board',inputs:'meeting time, cutoff, required documents, document owners, version, and late-item rule',boundary:'The assistant can chase inputs and mark readiness; the meeting owner decides whether to proceed, defer, or accept late material.',example:'A finance appendix lands after cutoff. It is linked as late and routed to the chair rather than quietly merged into the approved pack.',image:'/images/blog-2026-08-21/outsourced-assistant-meeting-prep-packet.png'},
  {slug:'ecommerce-return-photo-intake',title:'Structure return-photo intake for an ecommerce assistant',excerpt:'A consistent photo record speeds review without allowing images alone to decide a refund.',lane:'ecommerce support',artifact:'return evidence packet',inputs:'order ID, requested remedy, received time, customer description, approved photo categories, and policy version',boundary:'The assistant may check that evidence is present and legible; refund eligibility and fraud decisions remain with the authorised owner.',example:'A photo shows damaged packaging but not the item. The assistant requests the missing approved view and keeps the claim pending.',image:'/images/blog-2026-08-20/assistant-training-sample-review.png'},
  {slug:'bookkeeping-assistant-recurring-charge-watch',title:'Create a recurring-charge watchlist for bookkeeping support',excerpt:'A watchlist highlights changing subscriptions while keeping cancellation and payment authority separate.',lane:'bookkeeping support',artifact:'recurring-charge watchlist',inputs:'merchant, amount, cadence, cost center, prior approval, variance, and renewal date',boundary:'The assistant may reconcile and flag charges; only authorised staff may cancel services, dispute transactions, or move money.',example:'A software charge rises 18 percent. The assistant links the invoices and contract date, then asks the budget owner to decide.',image:'/images/blog-2026-08-20/delegated-invoice-exception-notes.png'},
  {slug:'recruiting-assistant-candidate-consent-log',title:'Maintain a candidate consent log for recruiting support',excerpt:'A consent log helps a recruiting assistant use candidate information only for the stated hiring purpose.',lane:'recruiting operations',artifact:'candidate consent log',inputs:'candidate identity, source, stated purpose, permitted contact, recorded date, retention rule, and owner',boundary:'The assistant can maintain the record and prepare approved messages; hiring decisions and sensitive-data exceptions stay with HR.',example:'A manager asks to reuse an old résumé for a new role. The assistant checks the recorded purpose and routes any new outreach for approval.',image:'/images/blog-2026-08-20/least-privilege-tool-onboarding-assistant.png'},
  {slug:'property-management-maintenance-triage-note',title:'Design a maintenance triage note for a property assistant',excerpt:'A structured note makes repair facts visible without delegating safety judgments or spending decisions.',lane:'property operations',artifact:'maintenance triage note',inputs:'property, reporter, observed condition, access constraints, photos, existing vendor instruction, and callback details',boundary:'The assistant can record and route facts; emergencies, habitability decisions, vendor commitments, and spend approval follow owner policy.',example:'A tenant reports a water stain but no active leak. The assistant uses the written safety route, preserves the description, and does not diagnose.',image:'/images/blog-2026-08-20/remote-project-dependency-register.png'},
  {slug:'content-assistant-citation-recheck-calendar',title:'Build a citation recheck calendar for daily articles',excerpt:'Citation maintenance works best when volatile claims are reviewed sooner than durable background sources.',lane:'content operations',artifact:'citation recheck calendar',inputs:'article URL, claim, source URL, source date, volatility label, next check, and editorial owner',boundary:'The assistant may verify links and surface changed wording; the editor decides whether evidence still supports the published claim.',example:'A government guidance page has moved and its wording changed. The assistant captures the new page and flags the affected sentence for review.',image:'/images/blog-2026-08-20/outsourced-article-outline-approval.png'}
];

const makePost = (x:Spec): BlogPost => ({
  slug:x.slug,title:x.title,excerpt:x.excerpt,minutes:8,published:'2026-09-04',image:{url:x.image,alt:`Illustration for ${x.title}`},
  takeaway:`Use a ${x.artifact} to make ${x.lane} reconstructable. Keep consequential decisions with a named owner.`,
  sections:[
    {heading:`Define the ${x.artifact}`,paragraphs:[`${x.excerpt} Start by naming the queue, its daily finish line, and the person who accepts exceptions. A useful routine should let a colleague understand the state without searching private chat.`,`For OutsourcingAssistant.com teams working with a Philippines-based assistant, write the time zone and next review window into the routine. Overnight progress is valuable only when the morning owner can see what changed and what is waiting.`]},
    {heading:'Collect the minimum useful evidence',paragraphs:[`The working record should include ${x.inputs}. Link the source rather than copying an unsupported conclusion into the tracker. Mark missing and conflicting inputs plainly.`,`Use the least sensitive record that still supports the task. A queue is not a reason to retain unrelated customer, candidate, employee, or payment data.`]},
    {heading:'Write the decision boundary as an action',paragraphs:[x.boundary,`Turn that limit into visible verbs: prepare, verify, pause, and route. Tool access does not widen authority, and an unanswered message does not count as approval.`]},
    {heading:'Practice one awkward case',paragraphs:[x.example,`Record the evidence, last safe action, decision needed, and next owner. Awkward examples are more useful than perfect demonstrations because they show where the stop rule actually operates.`]},
    {heading:'Hand off across time zones',paragraphs:[`At shift end, the assistant should state what is complete, what remains uncertain, who holds the next action, and when that person is expected to review it. “Pending” without an owner is not a usable state.`,`If timing becomes urgent, use the pre-approved escalation channel. Urgency can change the route and review window; it cannot create permission.`]},
    {heading:'Review and improve the routine',paragraphs:[`Each week, sample ordinary items as well as every exception. Check source fidelity, correct routing, privacy, and whether the final state can be reconstructed. Review speed only after those gates pass.`,`When the same question returns, improve the ${x.artifact} or add an approved example. Keep the old rule’s date so the team can explain why earlier work followed different guidance.`]}
  ],
  faqs:[{q:`What can the assistant own in ${x.lane}?`,a:`The assistant can own repeatable preparation, evidence capture, permitted updates, and routing inside the written ${x.artifact}.`},{q:'What should the owner retain?',a:'The owner retains commitments, policy decisions, access changes, sensitive judgments, money movement, and exceptions outside the approved lane.'},{q:'How should quality be checked?',a:'Sample routine work against its source record and review every consequential exception.'}],
  citations:[{name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework',note:'General governance and access-control context.'},{name:'U.S. Small Business Administration hiring guidance',url:'https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees',note:'General small-business management context.'}],
  internalLinks:[{href:'/resources/assistant-sop-handoff-checklist',label:'Use the assistant SOP handoff checklist'},{href:'/services',label:'Review outsourcing support services'}],cta:{href:'/contact',label:'Discuss a bounded assistant workflow'}
});

export const dailyBlogBatch20260904: BlogPost[] = specs.map(makePost);
