import type { BlogPost } from './data';

type Spec = { slug:string; title:string; excerpt:string; lane:string; artifact:string; inputs:string; stop:string; scenario:string; image:string };
const specs: Spec[] = [
  {slug:'assistant-refund-request-evidence-brief',title:'Prepare a refund evidence brief without promising the outcome',excerpt:'A bounded evidence brief helps support teams review refund requests while keeping policy interpretation and payment authority with the owner.',lane:'refund support',artifact:'refund evidence brief',inputs:'case ID, order record, request wording, delivery evidence, applicable policy version, prior remedies, amount requested, and decision owner',stop:'The records conflict, the request falls outside the written policy, or any response would promise money or admit liability.',scenario:'A customer reports a missing parcel while the carrier marks it delivered. The assistant preserves both records and asks the support owner to decide the remedy.',image:'/images/blog-2026-08-20/filipino-assistant-service-recovery-routing.png'},
  {slug:'virtual-assistant-recurring-meeting-attendee-audit',title:'Audit recurring-meeting attendees before the invitation becomes permanent',excerpt:'A periodic attendee audit prevents old access and unnecessary calendar load from persisting through an inherited recurring series.',lane:'calendar operations',artifact:'recurring-attendee audit',inputs:'series owner, meeting purpose, current attendees, required roles, guest status, linked documents, next occurrence, and review date',stop:'Removing or adding someone could affect confidentiality, decision authority, customer commitments, or protected calendar time.',scenario:'A former contractor remains on a monthly operating review. The assistant flags the inherited invitation and linked folder access for the series owner.',image:'/images/blog-2026-08-21/filipino-virtual-assistant-calendar-timezone-rules.png'},
  {slug:'outsourced-procurement-quote-expiry-tracker',title:'Track supplier quote expiry without selecting the vendor',excerpt:'A quote-expiry tracker surfaces decision windows and comparable source fields without turning administrative preparation into supplier selection.',lane:'procurement administration',artifact:'quote-expiry tracker',inputs:'supplier, quote reference, issue date, expiry, stated scope, currency, taxes, exclusions, source file, and buyer',stop:'Quotes describe different scope, contain unstated assumptions, or require a commercial preference, negotiation, or purchase commitment.',scenario:'The lowest quote excludes installation while two others include it. The assistant records the scope difference instead of ranking the bids by headline price.',image:'/images/blog-2026-08-21/outsourced-assistant-vendor-follow-up.png'},
  {slug:'filipino-assistant-customer-timezone-preference-record',title:'Record customer time-zone preferences before scheduling follow-up',excerpt:'A source-linked preference record reduces avoidable scheduling mistakes without asking a Filipino assistant to infer availability from location.',lane:'customer scheduling',artifact:'time-zone preference record',inputs:'customer wording, stated zone, preferred windows, excluded dates, daylight-saving note, source message, last confirmation, and owner',stop:'The zone is missing or ambiguous, the proposed slot crosses a stated boundary, or moving the meeting would alter a commitment.',scenario:'A customer writes “morning my time” from a company with offices in three countries. The assistant asks for the zone rather than guessing from the email signature.',image:'/images/research-2026-08-21/philippines-assistant-article-handoff-window.png'},
  {slug:'executive-assistant-briefing-source-freeze',title:'Set a source freeze for an executive briefing pack',excerpt:'A visible source-freeze time tells the executive which facts were checked and which late changes still require review.',lane:'executive briefing',artifact:'briefing source-freeze note',inputs:'meeting, decision questions, source owners, source versions, checked time, late updates, unresolved conflicts, and executive reviewer',stop:'A late change affects a key figure, legal position, confidential disclosure, recommendation, or the decision the meeting must make.',scenario:'Finance updates a forecast after the pack is assembled. The assistant labels the affected page and routes the new figure instead of silently replacing it.',image:'/images/blog-2026-08-20/remote-meeting-preparation-brief.png'},
  {slug:'assistant-password-reset-request-verification-handoff',title:'Route password-reset requests through a verification handoff',excerpt:'A verification handoff keeps an assistant from treating urgency or familiarity as proof of identity.',lane:'access support',artifact:'reset verification handoff',inputs:'request channel, claimed identity, affected account, approved verification route, verification state, urgency claim, access owner, and ticket ID',stop:'The requester uses a new channel, asks to bypass verification, targets privileged access, or cannot complete the approved identity check.',scenario:'A manager messages from a personal number during travel and asks for an immediate reset. The assistant opens the approved support route and does not disclose reset details in chat.',image:'/images/blog-2026-08-20/least-privilege-tool-onboarding-assistant.png'},
  {slug:'remote-assistant-contract-renewal-date-register',title:'Maintain a contract-renewal date register without giving legal advice',excerpt:'A renewal register can make notice windows visible while reserving contract interpretation and renewal choices for authorised reviewers.',lane:'contract administration',artifact:'renewal date register',inputs:'agreement name, counterparty, signed version, stated term, notice wording, date source, responsible owner, reminder date, and review status',stop:'Versions conflict, the clause is ambiguous, calculating the deadline requires interpretation, or a notice would create or end obligations.',scenario:'A signed amendment changes the service period but not the renewal paragraph. The assistant links both documents and asks counsel or the contract owner to establish the controlling date.',image:'/images/blog-2026-08-20/shared-drive-filing-conventions-assistant.png'},
  {slug:'content-assistant-quote-permission-ledger',title:'Keep a permission ledger for quotations in assistant-drafted articles',excerpt:'A quotation ledger preserves source, scope, and permission evidence before attributed words enter a public article.',lane:'content production',artifact:'quotation permission ledger',inputs:'exact quotation, speaker, original source, publication context, permission basis, permitted edits, approval evidence, and editor',stop:'Attribution is uncertain, the quote contains sensitive information, permission is narrower than the planned use, or edits could change meaning.',scenario:'A customer approved a quote for a case study but the team wants it in an advertorial. The assistant records the scope mismatch and pauses reuse.',image:'/images/blog-2026-08-20/outsourced-article-outline-approval.png'},
  {slug:'recruiting-assistant-candidate-withdrawal-record',title:'Close a candidate withdrawal with a minimal, reviewable record',excerpt:'A minimal withdrawal record closes recruiting tasks without inventing a reason or retaining unnecessary candidate information.',lane:'recruiting administration',artifact:'candidate withdrawal record',inputs:'candidate ID, exact withdrawal message, received time, open interviews, affected reviewers, system status, retention rule, and recruiter',stop:'The reason includes sensitive information, the candidate asks for deletion, or closing the record could conflict with an active offer or legal hold.',scenario:'A candidate withdraws after mentioning a family health matter. The assistant records the withdrawal status without circulating the personal explanation.',image:'/images/blog-2026-08-20/assistant-training-sample-review.png'},
  {slug:'assistant-invoice-bank-detail-change-check',title:'Add an independent check to supplier bank-detail changes',excerpt:'A bank-detail change check separates record preparation from verification and payment authority.',lane:'accounts payable support',artifact:'bank-detail change check',inputs:'supplier ID, change request, original channel, existing verified contact, independent verification result, effective date, pending invoices, and finance owner',stop:'The request arrives by an unverified route, contact details changed together, verification fails, or payment is already queued.',scenario:'An invoice footer shows a new account and asks for same-day payment. The assistant quarantines the change and routes independent verification through the existing supplier record.',image:'/images/blog-2026-08-20/delegated-invoice-exception-notes.png'},
  {slug:'project-assistant-decision-log-reversal-note',title:'Document a decision reversal without rewriting the project history',excerpt:'A reversal note preserves what changed, why it changed, and which downstream work needs review.',lane:'project administration',artifact:'decision reversal note',inputs:'original decision, original evidence, decision date, change request, new evidence, authorised decider, affected work, and effective time',stop:'The new instruction lacks an authorised owner, conflicts with another active decision, or would erase evidence needed to understand completed work.',scenario:'A launch sequence changes after a compliance review. The assistant links the superseding decision and identifies affected tasks rather than editing the earlier record as though it never existed.',image:'/images/blog-2026-08-20/remote-project-dependency-register.png'},
  {slug:'virtual-assistant-customer-export-scope-check',title:'Check export scope before an assistant downloads customer data',excerpt:'An export-scope check limits fields, rows, destination, and retention before customer information leaves its source system.',lane:'data administration',artifact:'customer export scope check',inputs:'business purpose, approved requester, source system, required fields, population filter, destination, access group, retention time, and deletion owner',stop:'The purpose is vague, sensitive fields exceed the task, the destination is unapproved, or the export population cannot be bounded.',scenario:'Marketing asks for “all customer data” to reconcile event attendees. The assistant narrows the request to approved identifiers and the relevant event population.',image:'/images/blog-2026-08-21/filipino-assistant-data-cleanup-scope.png'}
];

const makePost=(x:Spec):BlogPost=>({slug:x.slug,title:x.title,excerpt:x.excerpt,minutes:8,published:'2026-09-09',image:{url:x.image,alt:`Operational illustration for ${x.title}`},takeaway:`Use a ${x.artifact} to keep ${x.lane} traceable while the named owner retains consequential authority.`,sections:[
 {heading:`Define the ${x.artifact}`,paragraphs:[`${x.excerpt} State the allowed output, source system, and approving owner before work begins.`,`For OutsourcingAssistant.com routines shared across Philippine and owner time zones, include the next safe review window and the state that should remain unchanged while waiting.`]},
 {heading:'Build the record from evidence',paragraphs:[`Capture ${x.inputs}. Keep a link to the authoritative record and copy only the information required for this decision.`,`Distinguish observed facts, reported statements, calculations, and assumptions. A completed field should never hide missing or contradictory evidence.`]},
 {heading:'Make the stopping condition explicit',paragraphs:[`${x.stop} Preserve the last verified state and route one focused question to the authorised owner.`,`Access to a tool permits the documented preparation step only. It does not confer authority to spend, disclose, interpret policy, alter access, or make a business commitment.`]},
 {heading:'Test the exception path',paragraphs:[x.scenario,`The escalation should identify the source, conflict, consequence of waiting, safest reversible state, owner, and response deadline. Urgency affects routing speed, not the evidence standard.`]},
 {heading:'Hand off across shifts',paragraphs:[`Close each work window with a clear state: ready, waiting, blocked, approved, superseded, or closed. Name the next actor and retain enough evidence for independent reconstruction.`,`The incoming reviewer should see which preparation is complete, what remains uncertain, and which action still requires approval without relying on private chat context.`]},
 {heading:'Review and improve the routine',paragraphs:[`Sample ordinary items and every exception for source fidelity, data minimisation, boundary compliance, and closure quality. Only then compare turnaround time.`,`When an ambiguity repeats, add an approved example to the ${x.artifact}, record its effective date, and preserve the earlier instruction for historical work.`]}
],faqs:[{q:`What can an assistant own in ${x.lane}?`,a:`Source-linked preparation, status tracking, and bounded routing described in the ${x.artifact}.`},{q:'When must the assistant stop?',a:x.stop},{q:'What completes the handoff?',a:'A verified source, explicit uncertainty, safe current state, named decision owner, and review time.'}],citations:[{name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework',note:'Governance and risk-management context.'},{name:'U.S. Small Business Administration management guidance',url:'https://www.sba.gov/business-guide/manage-your-business',note:'General small-business operations context.'}],internalLinks:[{href:'/resources/assistant-sop-handoff-checklist',label:'Build an assistant SOP handoff'},{href:'/services',label:'Explore bounded assistant services'}],cta:{href:'/contact',label:'Discuss the routine'}});

export const dailyBlogBatch20260909: BlogPost[] = specs.map(makePost);
