import type { BlogPost } from './data';

type Spec = { slug:string; title:string; excerpt:string; lane:string; artifact:string; inputs:string; stop:string; scenario:string; image:string };
const specs: Spec[] = [
  {slug:'assistant-inbox-vip-sender-rule-review',title:'Review VIP sender rules before an assistant triages the inbox',excerpt:'A practical sender-rule review keeps an executive inbox moving without turning a label into permission to disclose, promise, or pay.',lane:'inbox triage',artifact:'VIP sender rule sheet',inputs:'known address, relationship, usual request type, permitted action, exception owner, and review date',stop:'A familiar name arrives from a new address or asks for money, credentials, confidential files, or an unusual commitment.',scenario:'A long-standing supplier appears from a personal address asking for an urgent wire confirmation. The assistant preserves the message and verifies it through the established contact route.',image:'/images/blog-2026-08-20/cross-timezone-queue-status-note.png'},
  {slug:'virtual-assistant-calendar-hold-expiry-routine',title:'Give tentative calendar holds an expiry routine',excerpt:'An expiry routine prevents provisional holds from quietly consuming the calendar after the underlying request has gone cold.',lane:'calendar administration',artifact:'tentative-hold register',inputs:'requester, purpose, proposed slot, competing holds, decision owner, expiry time, and status',stop:'A hold reaches expiry without an owner decision or conflicts with protected travel, preparation, or personal time.',scenario:'Two prospects ask for the same afternoon. The assistant records both options and the decision deadline instead of choosing which opportunity matters more.',image:'/images/blog-2026-08-21/filipino-virtual-assistant-calendar-timezone-rules.png'},
  {slug:'outsourced-support-chargeback-evidence-packet',title:'Build a chargeback evidence packet without arguing the case',excerpt:'A bounded support routine can assemble transaction records while keeping representations and financial decisions with authorised staff.',lane:'customer support',artifact:'chargeback evidence packet',inputs:'case ID, notice date, transaction record, delivery evidence, customer correspondence, policy version, deadline, and reviewer',stop:'The record is incomplete, contradictory, legally sensitive, or asks the assistant to state a conclusion the evidence does not establish.',scenario:'Tracking shows delivery but the customer reports non-receipt. The assistant preserves both facts and routes the contradiction without claiming fraud.',image:'/images/blog-2026-08-20/filipino-assistant-service-recovery-routing.png'},
  {slug:'assistant-vendor-insurance-certificate-chase',title:'Run a vendor insurance-certificate chase with clear limits',excerpt:'A certificate chase can collect the current document and route gaps without asking an assistant to judge insurance adequacy.',lane:'vendor administration',artifact:'certificate follow-up log',inputs:'vendor, required document name, requested period, request history, file received, stated expiry, contract owner, and status',stop:'The document is missing, altered, expired, names the wrong entity, or requires an adequacy or coverage decision.',scenario:'A vendor supplies a certificate with a future policy date but work starts tomorrow. The assistant flags the mismatch for the contract owner.',image:'/images/blog-2026-08-21/outsourced-assistant-vendor-follow-up.png'},
  {slug:'filipino-assistant-crm-consent-note-handoff',title:'Preserve consent notes during a Filipino assistant CRM handoff',excerpt:'A source-linked handoff keeps contact preferences visible while reserving legal interpretation and campaign approval for the owner.',lane:'CRM administration',artifact:'consent-note handoff',inputs:'contact ID, source record, stated preference, channel, captured date, last change, active workflow, and owner',stop:'Sources disagree, the preference is ambiguous, or a requested campaign would override an existing restriction.',scenario:'A form permits email updates while a later support ticket asks for no marketing. The assistant links both records and pauses campaign enrollment.',image:'/images/blog-2026-08-21/filipino-assistant-data-cleanup-scope.png'},
  {slug:'executive-assistant-travel-disruption-watch',title:'Set up a travel disruption watch that does not rebook by assumption',excerpt:'A disruption watch can surface verified changes and prepare options while the traveller keeps control of cost and itinerary tradeoffs.',lane:'travel coordination',artifact:'travel disruption watch',inputs:'official booking reference, carrier alert, affected segment, connection risk, verified options, fare conditions, traveller preference, and decision deadline',stop:'Any option changes cost, route, class, passenger details, entry requirements, or a protected commitment.',scenario:'A delayed first flight threatens a connection. The assistant checks the carrier record and prepares two options without cancelling the original itinerary.',image:'/images/blog-2026-08-20/remote-meeting-preparation-brief.png'},
  {slug:'assistant-meeting-transcript-retention-check',title:'Add a retention check before filing an assistant-prepared transcript',excerpt:'A retention check keeps meeting records useful without treating every transcript as a permanent company document.',lane:'meeting administration',artifact:'transcript retention check',inputs:'meeting owner, attendee notice, recording source, sensitivity, approved destination, retention period, access group, and deletion owner',stop:'Notice is unclear, sensitive material exceeds the meeting purpose, or no authorised owner has set storage and retention.',scenario:'A routine project call drifts into employee health details. The assistant pauses broad filing and asks the meeting owner where the record belongs.',image:'/images/blog-2026-08-20/shared-drive-filing-conventions-assistant.png'},
  {slug:'outsourced-bookkeeping-credit-note-match',title:'Match supplier credit notes without posting an accounting decision',excerpt:'A matching worksheet can connect a credit note to its invoice while leaving ledger treatment and payment changes to authorised finance staff.',lane:'bookkeeping support',artifact:'credit-note match worksheet',inputs:'supplier, credit-note number, invoice reference, dates, amounts, currency, reason stated, open balance, and finance owner',stop:'References do not agree, currency differs, the invoice is already settled, or applying the credit would change a payment.',scenario:'A credit note names the correct invoice but uses a different currency. The assistant records the mismatch rather than forcing the amounts to reconcile.',image:'/images/blog-2026-08-20/delegated-invoice-exception-notes.png'},
  {slug:'remote-assistant-shared-link-expiry-audit',title:'Audit shared-link expiry before a remote assistant closes the task',excerpt:'A small closure check catches public or lingering file links after the collaboration they supported has ended.',lane:'document operations',artifact:'shared-link expiry audit',inputs:'file owner, link URL, intended recipients, access mode, business purpose, creation date, expiry, and closure evidence',stop:'The link is public, ownership is unknown, sensitive files are exposed, or removing access could interrupt active work.',scenario:'A proposal folder is still open to anyone with the link after the pitch ends. The assistant captures the current state and asks the owner to approve closure.',image:'/images/blog-2026-08-20/least-privilege-tool-onboarding-assistant.png'},
  {slug:'content-assistant-statistic-context-card',title:'Give every article statistic a context card',excerpt:'A context card stops a striking number from losing its population, period, definition, and source during outsourced drafting.',lane:'content operations',artifact:'statistic context card',inputs:'exact figure, unit, population, geography, period, definition, source URL, publication date, and limitation',stop:'The denominator is missing, the source is secondary when a primary record exists, or the number is applied outside its measured scope.',scenario:'A global remote-work survey is offered as proof about Filipino assistants. The assistant records the geographic mismatch and narrows the wording.',image:'/images/blog-2026-08-20/outsourced-article-outline-approval.png'},
  {slug:'recruiting-assistant-reference-check-intake',title:'Separate reference-check intake from hiring judgment',excerpt:'A structured intake lets a recruiting assistant schedule and record approved questions without deciding what a reference means for employment.',lane:'recruiting operations',artifact:'reference-check intake record',inputs:'candidate consent status, referee details, relationship, approved questions, response channel, verbatim answers, unresolved gaps, and hiring owner',stop:'Consent is absent, the referee volunteers sensitive information, or the assistant is asked to recommend a hiring outcome.',scenario:'A referee mentions an unrequested medical detail. The assistant limits the record and escalates privately rather than circulating the comment.',image:'/images/blog-2026-08-20/assistant-training-sample-review.png'},
  {slug:'project-assistant-dependency-date-confidence',title:'Label confidence before an assistant updates a dependency date',excerpt:'A date-confidence label distinguishes a confirmed commitment from a forecast, assumption, or unanswered follow-up.',lane:'project administration',artifact:'dependency date record',inputs:'dependency, source, date stated, statement type, assumptions, downstream effect, next confirmation, and owner',stop:'The date is inferred, conflicts with another source, moves a committed milestone, or would create a customer promise.',scenario:'A vendor says parts should arrive next week but gives no dispatch confirmation. The assistant records a forecast, not a committed delivery date.',image:'/images/blog-2026-08-20/remote-project-dependency-register.png'}
];

const makePost = (x:Spec): BlogPost => ({slug:x.slug,title:x.title,excerpt:x.excerpt,minutes:8,published:'2026-09-08',image:{url:x.image,alt:`Illustration supporting ${x.title}`},takeaway:`Use a ${x.artifact} to make ${x.lane} reviewable, and keep consequential decisions with the named owner.`,sections:[
 {heading:`Start with the ${x.artifact}`,paragraphs:[`${x.excerpt} Write the permitted outcome and the reviewer before the first item enters the queue.`, `For an OutsourcingAssistant.com workflow spanning Philippine and owner time zones, include the next review window so an overnight pause has an explicit owner.`]},
 {heading:'Capture the source record',paragraphs:[`Record ${x.inputs}. Link to the authoritative system instead of copying more personal or commercial data than the task requires.`, `Mark facts, reported statements, forecasts, and assumptions separately. A tidy field is not evidence that the underlying claim is true.`]},
 {heading:'Turn the boundary into a stop rule',paragraphs:[`${x.stop} The assistant should preserve the last verified state, pause the consequential action, and send one narrow question to the authorised owner.`, `Tool access permits preparation only within the written lane. It does not grant authority over payments, legal conclusions, sensitive disclosure, policy exceptions, or business commitments.`]},
 {heading:'Walk through a realistic exception',paragraphs:[x.scenario, `The handoff should show what was observed, what remains uncertain, the safest available next action, the owner, and the response deadline. Urgency changes the escalation speed, not the authority boundary.`]},
 {heading:'Close the loop across shifts',paragraphs:[`At shift end, label the item ready, waiting, blocked, approved, or closed and say who acts next. Attach the evidence needed to reconstruct the state without private-chat context.`, `The incoming reviewer should be able to distinguish work completed by the assistant from a decision still waiting for approval.`]},
 {heading:'Review the routine with a small sample',paragraphs:[`Each week, sample routine items and inspect every exception for source fidelity, data minimisation, correct routing, and closure. Measure speed only after those controls pass.`, `When the same ambiguity recurs, update the ${x.artifact} with an approved example and effective date. Keep the earlier rule visible so prior work remains understandable.`]}
],faqs:[{q:`What can the assistant own in ${x.lane}?`,a:`Evidence capture, bounded preparation, status updates, and routing described in the ${x.artifact}.`},{q:'What should remain with the owner?',a:'Consequential judgments, commitments, money movement, sensitive disclosure, access changes, and policy exceptions.'},{q:'What makes the handoff complete?',a:'A source-linked status, visible uncertainty, named next owner, permitted next action, and review time.'}],citations:[{name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework',note:'Governance and risk-management context.'},{name:'U.S. Small Business Administration hiring and management guidance',url:'https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees',note:'General small-business management context.'}],internalLinks:[{href:'/resources/assistant-sop-handoff-checklist',label:'Build an assistant SOP handoff'},{href:'/services',label:'Review bounded assistant services'}],cta:{href:'/contact',label:'Discuss the workflow'}});

export const dailyBlogBatch20260908: BlogPost[] = specs.map(makePost);
