import type { BlogPost } from './data';

type Spec = {
  slug: string; title: string; audience: string; question: string; workflow: string;
  proof: string; boundary: string; decision: string; published: '2026-08-18';
};

const records: Spec[] = [
  ['filipino-assistant-daily-content-briefs','Build daily content briefs with a Filipino assistant','a site owner who wants a dependable article routine','how to turn a reader question into a brief another writer can use','state the reader, decision, source list, outline, and approval questions before drafting','the brief separates verified facts, examples, and claims needing review','publishing unsupported claims, copying competing pages, or choosing the final editorial angle','which facts must be verified before the draft moves forward'],
  ['filipino-assistant-editorial-calendar-maintenance','Maintain an editorial calendar with a Filipino assistant','an operator coordinating recurring blog work across several topics','how to keep assignments, dates, owners, and dependencies visible','compare every calendar item with its approved brief and record the next handoff','each entry links to a brief, owner, status, and dated review note','changing priorities, promising publication, or moving an approved deadline without the owner','whether a gap is a missing brief, missing review, or real capacity issue'],
  ['filipino-assistant-article-source-checking','Run source checking for assistant-written articles','a content manager who needs useful articles grounded in reliable material','which statements require a source and which are clearly framed examples','mark claims, locate primary references, and attach a note explaining how each source is used','a reviewer can trace every material claim to a source or see it labeled as an example','inventing citations, treating a search snippet as proof, or giving professional advice','whether a source supports the exact claim rather than a nearby idea'],
  ['filipino-assistant-blog-outline-review','Review blog outlines before drafting begins','an owner who wants fewer rewrites from outsourced content','whether an outline answers a real reader question in a useful order','test the promise, headings, examples, boundaries, and conclusion against the approved brief','the outline shows what the reader will decide or do after each section','rewriting the business strategy, approving unsupported claims, or copying a competitor structure','whether the outline is sufficiently specific to the company niche'],
  ['filipino-assistant-content-fact-table','Create a content fact table for repeatable article work','a small team that needs one safe place for approved business facts','how to prevent old descriptions and unverified claims entering new drafts','record each fact, source, owner, review date, allowed wording, and prohibited inference','every reusable fact has a source and a visible stale or review state','inventing credentials, results, testimonials, locations, or pricing','whether a fact is current, scoped, and safe for public copy'],
  ['filipino-assistant-blog-internal-link-audit','Audit internal links in outsourced blog drafts','a site owner trying to make articles easier to navigate','which related pages genuinely help the reader continue','compare each proposed link with the section promise and confirm the destination still exists','the link has a relevant label, working destination, and reason it belongs','adding promotional links unrelated to the question or claiming a service outcome','whether the reader benefits more from a link than from another sentence'],
  ['filipino-assistant-article-refresh-queue','Operate an article refresh queue without date shifting','an editor managing older pages that may need review','which pages need evidence, clarity, structure, or link maintenance','classify the issue, preserve the original route, assign an owner, and record the proposed change','each queued item names the observed problem and the evidence for its priority','pretending a rewrite is a new article, changing publication history, or deleting useful context','whether the page needs a factual correction or a broader editorial decision'],
  ['filipino-assistant-reader-question-mining','Mine reader questions for practical article ideas','a founder who wants topics based on recurring operator problems','which questions reveal a decision worth answering publicly','group real questions by intent, remove private details, and write a distinct working thesis','each idea preserves the question while naming the audience and useful answer','inventing customer stories, exposing private messages, or treating frequency as proof','whether the topic solves a real problem for the defined audience'],
  ['filipino-assistant-article-brief-approval','Set an approval gate for article briefs','a content owner who reviews outsourced work in short windows','what must be approved before research and drafting consume time','present the audience, thesis, evidence plan, risks, structure, and open questions in one record','the approval note says approved, revise, or blocked and explains the reason','silently approving by calendar age, publishing without review, or making claims for the owner','whether the brief has enough direction to produce a bounded draft'],
  ['filipino-assistant-blog-draft-style-check','Check outsourced blog drafts for style and reader clarity','an editor who wants consistent, plain-language guidance','where a draft becomes vague, promotional, repetitive, or hard to act on','sample the introduction, transitions, examples, boundaries, and close against a style checklist','each correction points to a sentence and describes the clearer reader need','flattening every article into one voice, changing the thesis, or adding invented authority','whether the edit improves understanding without changing the factual meaning'],
  ['filipino-assistant-content-compliance-review','Review public article copy for prohibited claims','a company preparing practical outsourcing guidance for publication','how to catch unsupported promises before an article is public','scan claims about outcomes, credentials, locations, pricing, testimonials, and professional advice','the review log records the exact phrase, risk category, and approved resolution','creating legal conclusions, guaranteeing results, or removing an issue without owner review','whether a claim is supported, qualified, and within the site’s public boundaries'],
  ['filipino-assistant-blog-meta-data-check','Check article metadata before an outsourced post is released','a site operator responsible for accurate routes and dates','whether title, description, canonical, date, and structured data agree','compare the source record, rendered route, metadata, and sitemap entry using one checklist','the route, visible date, canonical, and JSON-LD all identify the same article','changing a route to hide a duplicate, inventing a date, or treating build output as editorial approval','whether the public identity of the article is truthful and stable'],
  ['filipino-assistant-content-qa-handoff','Prepare a content QA handoff for owner review','a distributed editorial team working across different review windows','what a reviewer needs to verify without reconstructing the work','bundle the brief, source notes, draft, checks, open questions, and next action','the handoff distinguishes completed checks from pending judgment','declaring quality complete, hiding unresolved questions, or changing source evidence','which remaining issue can block publication and who owns it'],
  ['filipino-assistant-blog-topic-deduplication','Deduplicate blog topics before assigning new articles','an editor with a growing archive and limited writing capacity','whether a new idea is genuinely different from an existing article','compare reader question, thesis, route, examples, and conclusion rather than title alone','the decision records the nearest existing topic and the meaningful distinction','renaming an old article, lightly paraphrasing it, or treating a new date as originality','whether the proposed article adds a different answer, not another keyword variation'],
  ['filipino-assistant-article-outline-examples','Choose useful examples for assistant-work articles','a writer explaining delegation without inventing company history','which scenario makes the operating boundary concrete','use bounded hypothetical cases with stated assumptions and contrast routine work with escalation','examples are clearly examples and show input, action, review, and exception','fabricating clients, results, testimonials, credentials, or identifiable private facts','whether the example teaches a decision the reader can adapt safely'],
  ['filipino-assistant-blog-image-alt-review','Review image alt text for outsourced blog pages','a site owner keeping article pages accessible and descriptive','how to describe an image without adding claims the image cannot support','inspect the image purpose, write concise descriptive text, and compare it with nearby copy','alt text explains relevant content without keyword stuffing or repeated headline text','describing unshown results, people, credentials, or location details','whether the text serves someone who cannot see the image'],
  ['filipino-assistant-content-calendar-risk-log','Keep an editorial risk log alongside the content calendar','an operator balancing daily publishing with careful review','which content risks need attention before a deadline','log risk, affected article, evidence, owner, mitigation, and review state','each risk has a concrete next action rather than a vague warning','hiding risk to preserve a date, approving its own mitigation, or changing scope silently','whether the risk concerns facts, originality, access, route identity, or approval'],
  ['filipino-assistant-blog-revision-tracking','Track article revisions without losing editorial history','a team that needs to know why a public draft changed','how to distinguish a correction, improvement, and new assignment','record the source version, reason, reviewer, changed sections, and resulting decision','a reader of the log can tell what changed without comparing every file manually','rewriting history, deleting evidence, or calling a revision a new route','whether the change alters the article’s thesis or only improves its expression'],
  ['filipino-assistant-assistant-content-access','Set least-privilege access for an outsourced content assistant','a founder delegating research and drafting while protecting business systems','which tools and folders are actually needed for one content lane','map each task to view, comment, draft, publish, or admin permission and start narrow','the access record names account, purpose, approver, review date, and exit step','sharing owner passwords, granting publication by default, or exposing unrelated records','whether the assistant can finish the task without unnecessary access'],
  ['filipino-assistant-blog-publishing-checklist','Build a final blog publishing checklist for assistant work','an owner who wants a reliable last review before public release','what must be true for an article to be considered ready','check originality, word count, date, route, links, metadata, sources, and prohibited topics','the checklist produces a dated evidence note with unresolved items visible','submitting forms, triggering deployment, or claiming live verification without authorization','whether every release criterion has a measured answer'],
  ['filipino-assistant-content-performance-notes','Prepare factual content performance notes','a site owner reviewing published articles without overstating results','how to summarize observed page data for an owner’s decision','copy approved measurements with period, source, limitations, and comparison context','each number links to its source and separates observation from interpretation','inventing traffic, promising rankings, or presenting correlation as causation','which editorial decision the data can inform and which it cannot'],
  ['filipino-assistant-blog-archive-indexing','Index a blog archive so useful guidance remains findable','a content team with many assistant-work articles and related routes','how to organize pages without hiding older or distinct material','record route, topic, audience, date, related questions, and review state in the native index','the index preserves canonical identity and lets a reviewer find the source record','deleting older work, changing dates, or replacing an article with a summary','whether the grouping helps readers choose the next relevant guide']
].map(([slug,title,audience,question,workflow,proof,boundary,decision]) => ({slug,title,audience,question,workflow,proof,boundary,decision,published:'2026-08-18' as const}));

function makePost(r: Spec): BlogPost {
  return {
    slug: r.slug, title: r.title, published: r.published, minutes: 10,
    excerpt: `A practical Outsourcing Assistant guide for ${r.audience}, focused on ${r.question}.`,
    takeaway: `Keep ${r.question} visible in a bounded workflow: ${r.workflow}.`,
    sections: [
      { heading: 'Define the reader and the decision', body: `A useful content operation starts with a real reader rather than a keyword. For ${r.audience}, write down ${r.question}. That sentence gives the article a job. It also protects the assistant from producing a broad summary that sounds polished but does not help anyone choose a next step. The brief should name the reader’s starting situation, the decision or problem they face, and the boundary around the answer. If the owner cannot state those three things, pause the assignment and record the missing context. A narrow question is easier to research, easier to review, and more likely to remain useful after publication.` },
      { heading: 'Turn the question into a bounded brief', body: `The brief should explain what the article will cover and what it will leave out. Begin with ${r.workflow}. Add the intended structure, examples that are allowed, source types to consult, and a short list of claims that need confirmation. The assistant can make the record orderly, identify gaps, and suggest questions for the owner. The owner remains responsible for the business position and any claim that could be read as a guarantee or professional advice. Put the approved brief beside the draft so a reviewer can compare the finished article with the original assignment instead of judging it against an unspoken expectation.` },
      { heading: 'Research without manufacturing certainty', body: `Research notes should distinguish a source’s actual statement from the assistant’s explanation. For each important point, capture the source, publication or update date when available, the relevant passage in your own words, and the limit on what it proves. If a source is unavailable or ambiguous, mark the gap. Do not fill it with a plausible number, a broad industry claim, or a sentence borrowed from another page. This is especially important when the article discusses outsourcing, access, customer data, hiring, or business decisions. A short, qualified answer with traceable evidence is more useful than confident copy that an owner must later unwind.` },
      { heading: 'Make the operating example honest', body: `Examples make guidance concrete, but they should not pretend to be company history. Use a clearly labeled hypothetical situation with an input, a routine action, a review point, and an exception. Show what a Filipino or Philippines-based assistant may prepare, then show where the owner or manager decides. In this article’s lane, the meaningful control is ${r.boundary}. Keep private messages, invented clients, fabricated results, and unsupported credentials out of the example. A good scenario teaches a reader how to structure work without implying that OutsourcingAssistant.com has observed a particular outcome or endorses a universal method.` },
      { heading: 'Review for originality and usefulness', body: `A new article must add a distinct answer, not merely a new title around an old body. Compare its reader question, thesis, examples, headings, and conclusion with the existing archive before assigning or approving it. Topic similarity is not automatically a problem; interchangeable articles are. The reviewer should ask whether the article changes the decision, supplies a different operating model, or addresses a different risk. Remove repeated introductions and generic advice. Keep the company niche central through the work examples, role boundaries, and handoff details, so the page remains about outsourcing assistant work rather than becoming a general productivity essay.` },
      { heading: 'Use a measurable review record', body: `The owner review should leave evidence. Record the route, title, brief, source notes, word count, date binding, visible date, canonical, structured data result, and any open editorial questions. For this workflow, the useful proof is ${r.proof}. A checklist is not a substitute for judgment, but it prevents easy omissions and gives the owner a fast way to see what still needs attention. Keep failed checks visible until resolved. Never turn a calendar deadline into an approval, and never treat a successful build as evidence that the copy is accurate or original.` },
      { heading: 'Protect access and approval lines', body: `Content assistants need tools that match their actual task. Start with the smallest permission that supports research, drafting, and review preparation. Separate source folders, drafts, and public publishing access where the tools permit it. Keep owner passwords, irreversible changes, publication approval, and sensitive records with authorized people. If the assistant encounters ${r.boundary}, the correct action is to preserve context, state the missing decision, and escalate. A clear pause rule keeps speed from becoming a hidden policy change and makes the collaboration easier to audit.` },
      { heading: 'Close with a useful next action', body: `The conclusion should answer the reader’s original question and give a proportionate next step. It might be a brief template, a review sample, a source-checking pass, or an owner decision. Avoid a generic invitation that changes the article into a sales page. For the team, close the work item with the approved route, reviewer, unresolved questions, and next review date. The key decision remains ${r.decision}. When the article teaches that decision clearly, the assistant’s work is easier to assess and the owner can improve the routine from real corrections rather than from memory.` }
      ,{ heading: 'Keep the routine learnable', body: `A daily article routine should become clearer after each reviewed item. Save the correction that mattered, the question that recurred, and the example that resolved it. Then decide whether the fix belongs in the brief, the source register, the checklist, or the reviewer’s training. Do not respond to every correction by adding another broad rule; a short example with a named boundary is often more useful. For ${r.audience}, the practical goal is a handoff that another authorized person can understand and continue. That means completed work, waiting work, evidence, and the next decision remain visible together. The assistant can maintain that record, while the owner decides which process changes are approved.` }
    ],
    faqs: [
      { q: `What is the first step for ${r.title.toLowerCase()}?`, a: `Start by defining the reader, the finished decision, the approved source material, and the owner who reviews exceptions. Then use a small sample before widening the workflow.` },
      { q: 'What should an outsourced assistant do when evidence is missing?', a: 'Mark the gap, preserve the source context, and escalate through the agreed review path. A missing fact should remain missing rather than becoming an assumption.' },
      { q: 'How can an owner tell whether the article is ready?', a: `Check the brief, originality, source notes, route identity, visible and structured date, word count, and prohibited-topic review. The record should show ${r.proof}.` }
    ],
    internalLinks: [{ href: '/resources/assistant-sop-handoff-checklist', label: 'Assistant SOP handoff checklist' }, { href: '/services', label: 'Outsourcing Assistant services' }]
  };
}

export const dailyBlogBatch20260818: BlogPost[] = records.map(makePost);
