import type { BlogPost } from './data';

type Spec = { slug: string; title: string; risk: string; inputs: string; workflow: string; boundary: string; example: string };
const specs: Spec[] = [
  ['virtual-assistant-password-reset-request-triage','Triage password-reset requests with a virtual assistant','A routine reset request can be an account-takeover attempt or expose recovery information.','requester identity, account, request channel, known contact method, recent events, and system alert','preserve the request, compare it with the account record, and prepare an independent verification packet','Never reset credentials, disclose recovery data, or change authentication factors.','A senior employee requests an urgent reset from a new phone number. The assistant routes verification through the known directory entry.'],
  ['outsourced-purchase-order-match-review','Prepare a purchase-order match review before invoice approval','An invoice can appear valid while quantity, price, receipt, or supplier details conflict with the purchase order.','invoice, purchase order, receipt record, vendor record, currency, and exception owner','compare the records field by field, label variances, and assemble unresolved evidence','Never approve payment, alter banking data, or resolve a price variance by assumption.','The invoice quantity exceeds the receiving record by two units. The assistant sends both originals and the variance to the buyer.'],
  ['assistant-calendar-delegate-permission-review','Review calendar delegate permissions for an executive assistant','Old or broad calendar permissions can expose private events and allow unintended changes.','calendar owner, delegate list, permission level, purpose, last use, and review date','inventory grants, connect each grant to active work, and prepare owner decisions','Never expand permissions, reveal private-event details, or remove access without authorization.','A former project assistant retains edit access. The reviewer records the stale grant for the calendar owner.'],
  ['virtual-assistant-customer-consent-record-check','Check customer consent records before delegated outreach','A campaign list can conflict with the consent source, permitted channel, or later withdrawal.','contact identifier, consent event, source, channel, purpose, timestamp, and suppression history','trace eligibility to its source and separate supported contacts from conflicts','Never infer consent, restore a suppressed contact, or launch outreach.','The CRM allows email but a later suppression log shows an unsubscribe. The assistant excludes and flags the record.'],
  ['outsourced-shared-inbox-sla-clock-routine','Run a shared-inbox SLA clock without hiding waiting time','One response-time number can hide time waiting on customers, systems, or owner decisions.','received time, category, readiness time, dependency state, owner request, response time, and closure reason','record state changes and report active work separately from dependency waiting','Never backdate events, close unresolved cases, or pause a clock to improve the metric.','A refund packet is ready in twelve minutes but waits overnight for approval. The record separates both intervals.'],
  ['executive-assistant-meeting-guest-verification','Verify unfamiliar meeting guests before calendar acceptance','An unexpected invitation can reveal availability, introduce an untrusted link, or displace protected time.','organizer address, attendees, purpose, prior correspondence, domain, link, and executive preference','compare the invitation with trusted records and prepare accept, decline, or clarify options','Never open suspicious attachments, disclose private availability, or accept a sensitive meeting without approval.','An invitation copies a client name from a misspelled domain. The assistant verifies through the saved client contact.'],
  ['assistant-crm-stage-change-evidence-log','Keep an evidence log for assistant-prepared CRM stage changes','An unsupported stage change can distort forecasts and trigger the wrong automation.','record identifier, current and proposed stages, qualifying event, source note, automation impact, and owner','cite the supporting event, preview downstream actions, and queue the proposal','Never invent qualification, mark revenue won, or trigger contractual follow-up.','A prospect asks for pricing but has not agreed to scope. The assistant proposes discovery rather than committed.'],
  ['remote-assistant-document-version-release-check','Use a document-version release check for remote assistant work','A polished file can be the wrong version, contain comments, or lack final approval.','document identifier, source folder, version, change summary, comment status, approver, and destination','compare the candidate with the approved source and prepare a release note','Never overwrite the source, accept another person’s comments, or publish without approval.','A PDF labeled final differs from the approved document. The assistant stops distribution and provides a comparison.'],
  ['outsourced-refund-evidence-packet-checklist','Build a refund evidence packet without granting payment authority','An incomplete packet can cause delay, inconsistent treatment, or an unauthorized promise.','customer request, order, payment status, delivery evidence, policy version, prior credits, and exception category','assemble records, map facts to policy, and route a decision-ready packet','Never promise an outcome, move money, or override a fraud or dispute hold.','A full refund is requested after a partial credit. The assistant shows both transactions for the refund owner.'],
  ['virtual-assistant-vendor-bank-change-screening','Screen vendor bank-change messages before finance review','A convincing bank-change message can redirect a legitimate payment to a fraudulent account.','original message, sender address, vendor record, prior instructions, known verification channel, and effective date','quarantine the change, record discrepancies, and start verification through the established contact','Never edit banking fields, trust new contact details in the request, or confirm payment.','A supplier requests new routing details before today’s run. The assistant routes the case to finance unchanged.'],
  ['assistant-content-brief-claim-boundary-map','Map claim boundaries in an assistant-prepared content brief','A broad outline can turn limited evidence into a universal, causal, or promotional claim.','reader question, proposed claim, source passage, date, population, method, limitations, and editor','link claims to evidence, state supported scope, and mark assumptions','Never invent citations, erase limitations, or publish claims beyond the evidence.','A small survey supports a preference among respondents, not all companies. The assistant narrows the headline.'],
  ['cross-timezone-assistant-blocker-aging-review','Review blocker aging across a cross-time-zone assistant queue','Old blocked work can look like poor execution when the next action belongs elsewhere.','item, blocked time, reason, evidence-ready time, next owner, review window, reminders, and consequence','group blockers by owner and cause and surface items nearing a real deadline','Never fabricate progress, silently reassign accountability, or bypass approval.','A contract summary waits two days for legal interpretation. The report attributes the wait to the decision state.'],
].map(([slug,title,risk,inputs,workflow,boundary,example]) => ({slug,title,risk,inputs,workflow,boundary,example} as Spec));

const citations = [
  { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework', note: 'Governance and review context.' },
  { name: 'CISA Secure Our World', url: 'https://www.cisa.gov/secure-our-world', note: 'Verification and account safeguards.' },
  { name: 'SBA hiring guidance', url: 'https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees', note: 'General management context.' },
];
const make = (s: Spec): BlogPost => ({
  slug:s.slug,title:s.title,published:'2026-09-02',minutes:9,
  excerpt:`A practical OutsourcingAssistant.com routine for this operating risk: ${s.risk}`,
  image:{url:'/assistant-collaboration.jpg',alt:`A team reviewing ${s.title.toLowerCase()}`},
  takeaway:`The assistant should ${s.workflow}. The named owner retains consequential authority.`,
  sections:[
    {heading:'Define the decision before the task',body:`${s.risk} Name the intended result, accountable owner, and actions that remain proposals.`},
    {heading:'Assemble the source packet',body:`Collect ${s.inputs}. Keep originals and label absent, stale, or contradictory information.`},
    {heading:'Move through visible states',body:`The assistant should ${s.workflow}. Track received, checking, blocked, ready for review, approved, and closed separately.`},
    {heading:'Apply the authority boundary',body:s.boundary},
    {heading:'Walk through a realistic exception',body:`${s.example} Record the evidence, stop point, and next decision owner.`},
    {heading:'Design the time-zone handoff',body:'State the Philippine Time work window and owner review window. Include what changed, evidence checked, open question, consequence of waiting, and next permitted action.'},
    {heading:'Review reconstructable samples',body:`Sample ordinary work and every high-consequence exception. A reviewer should be able to recreate why the assistant had to ${s.workflow}.`},
    {heading:'Improve the routine safely',body:'When a question repeats, revise the checklist or examples. Change access or authority only through an explicit owner-approved update.'},
  ],
  faqs:[
    {q:'What can the assistant complete independently?',a:'The assistant can collect, compare, document, and prepare work inside the written lane. The named owner retains exceptions and consequential decisions.'},
    {q:'What belongs in the exception handoff?',a:`Include ${s.inputs}, the conflict, boundary reached, requested decision, and next safe action.`},
    {q:'How should this routine be reviewed?',a:'Review initial samples closely, retain evidence for corrections, and inspect every exception until the process is stable.'},
  ],citations,
  internalLinks:[{href:'/resources/assistant-sop-handoff-checklist',label:'Use the assistant SOP handoff checklist'},{href:'/services',label:'Review outsourcing support services'}],
  cta:{href:'/contact',label:'Plan a controlled assistant workflow'},
});
export const dailyBlogBatch20260902: BlogPost[] = specs.map(make);
