import type { BlogPost } from './data';

type Spec = {
  slug: string; title: string; excerpt: string; audience: string; workflow: string;
  record: string; inputs: string; boundary: string; example: string; metric: string; image: string;
};

const specs: Spec[] = [
  { slug:'home-services-virtual-assistant-estimate-follow-up', title:'How a virtual assistant can follow up on home-service estimates', excerpt:'A structured estimate follow-up lane helps home-service companies stay responsive without letting an assistant change price, scope, or availability.', audience:'a plumbing, HVAC, electrical, roofing, landscaping, or other home-service team', workflow:'estimate follow-up', record:'estimate follow-up register', inputs:'customer name, approved estimate version, service address, sent date, stated validity window, last contact, customer question, estimator, and next permitted action', boundary:'Pause when the customer asks for a discount, adds work, disputes a line item, requests a firm start date, or supplies information that changes the approved scope.', example:'A homeowner replies that a second contractor included disposal in a lower quote. The assistant records the comparison and routes it to the estimator instead of matching the price or adding disposal.', metric:'responses received, qualified owner decisions, stale estimates, incorrect-version contacts, and follow-ups completed within the approved cadence', image:'/images/blog-2026-08-20/cross-timezone-queue-status-note.png' },
  { slug:'healthcare-office-virtual-assistant-appointment-waitlist', title:'Build a safe appointment waitlist workflow for a healthcare virtual assistant', excerpt:'A bounded waitlist routine can fill cancelled appointments while leaving clinical priority, privacy exceptions, and care decisions with authorised staff.', audience:'a healthcare office using remote administrative support', workflow:'appointment waitlist administration', record:'waitlist contact log', inputs:'patient identifier, approved contact channel, requested appointment type, clinician, acceptable windows, last offer, response deadline, scheduling owner, and privacy notes required by policy', boundary:'Stop when clinical urgency is mentioned, identity cannot be verified, the requested visit type differs, protected details would be exposed, or staff must decide who receives priority.', example:'A patient on the routine-cleaning list reports new pain while answering an opening. The assistant does not assess the symptom or book the routine slot; the message is routed through the office’s clinical pathway.', metric:'openings offered, verified responses, declined slots, unresolved identity checks, clinical escalations, and bookings confirmed by the approved rule', image:'/images/blog-2026-08-20/remote-meeting-preparation-brief.png' },
  { slug:'real-estate-virtual-assistant-listing-inquiry-routing', title:'Route real-estate listing inquiries with a virtual assistant', excerpt:'A listing-inquiry workflow can collect practical scheduling details without allowing an assistant to steer prospects, interpret contracts, or invent property facts.', audience:'a real-estate team handling buyer or renter inquiries', workflow:'listing inquiry routing', record:'listing inquiry brief', inputs:'listing ID, inquiry source, prospect-provided contact details, requested viewing window, stated needs, approved property facts, assigned agent, consent status, and response state', boundary:'Pause for questions about protected characteristics, legal terms, negotiation, suitability, undisclosed property facts, or any request to favour or exclude a person.', example:'A prospect asks whether a neighbourhood is “good for families.” The assistant avoids a subjective or demographic answer, points to approved neutral property information, and routes the question to the licensed agent.', metric:'inquiries acknowledged, complete scheduling briefs, source attribution, duplicate leads, policy escalations, and agent response time', image:'/images/blog-2026-08-20/shared-drive-filing-conventions-assistant.png' },
  { slug:'agency-virtual-assistant-client-asset-intake', title:'Use a virtual assistant to organise client assets before agency work starts', excerpt:'A clear asset-intake gate prevents missing files and old approvals from quietly becoming campaign inputs.', audience:'a marketing, design, web, or creative agency', workflow:'client asset intake', record:'client asset register', inputs:'project, deliverable, requested asset, file owner, received version, usage permission, brand approval state, due date, storage location, and unresolved question', boundary:'Stop when ownership or usage permission is unclear, versions conflict, sensitive data appears, a file changes the agreed scope, or creative approval is implied rather than recorded.', example:'A client uploads a customer photograph from an old campaign but supplies no reuse permission. The assistant labels it unavailable for production and asks the account owner for evidence.', metric:'required assets received, current approved versions, permission gaps, files rejected for security or format reasons, and items awaiting client action', image:'/images/blog-2026-08-20/outsourced-article-outline-approval.png' },
  { slug:'saas-virtual-assistant-trial-account-support', title:'Design a SaaS trial-support lane for a virtual assistant', excerpt:'An assistant can resolve documented setup questions and preserve product feedback without promising features, extending commercial terms, or accessing more customer data than needed.', audience:'a SaaS company supporting trial users', workflow:'trial account support', record:'trial support case', inputs:'account ID, verified requester, plan or trial state, documented question category, approved help article, reproduction notes, data accessed, next owner, and response deadline', boundary:'Escalate security reports, billing or extension requests, roadmap questions, data exports, production changes, and cases where the documentation does not match current behaviour.', example:'A trial user asks whether a missing integration will ship before their trial ends. The assistant records the use case and routes the commercial and roadmap question instead of promising a date.', metric:'documented questions resolved, escalations by category, outdated help content, repeat contacts, access exceptions, and cases closed with user confirmation', image:'/images/blog-2026-08-20/least-privilege-tool-onboarding-assistant.png' },
  { slug:'construction-virtual-assistant-change-order-intake', title:'Prepare construction change-order intake with a virtual assistant', excerpt:'A change-order intake packet can organise field evidence while keeping cost, schedule, contract, and safety decisions with the project team.', audience:'a contractor or construction project office', workflow:'change-order intake', record:'change request packet', inputs:'project and location, requester, dated description, drawings or photographs, related instruction, affected trade, schedule concern, cost evidence received, contract owner, and status', boundary:'Stop when work would begin without authorisation, safety is implicated, instructions conflict, pricing is missing, contractual meaning is disputed, or the request changes a committed completion date.', example:'A site message asks a subcontractor to move an opening and “sort the paperwork later.” The assistant preserves the message and routes the unapproved scope change rather than marking it scheduled.', metric:'complete request packets, missing evidence, time to owner review, superseded drawings caught, unauthorised-start warnings, and approved or rejected outcomes', image:'/images/blog-2026-08-20/remote-project-dependency-register.png' },
  { slug:'insurance-certificate-tracking-virtual-assistant', title:'Track certificates of insurance with a virtual assistant', excerpt:'A certificate tracker can make expirations and missing documents visible without asking an assistant to decide whether coverage is legally or commercially sufficient.', audience:'a business that collects certificates from vendors or contractors', workflow:'certificate tracking', record:'certificate evidence register', inputs:'vendor, project or agreement, document source, insurer or producer shown, policy dates, named holder, stated limits, endorsement request, reviewer, and next follow-up', boundary:'Pause when the document appears altered, names do not match, coverage interpretation is required, an endorsement is missing, work may begin before review, or a vendor asks the assistant to waive a requirement.', example:'A vendor sends a certificate with the right project name but an expired policy period. The assistant records the mismatch and asks the risk owner to decide the next step.', metric:'current documents, expirations approaching under the approved window, unmatched entities, missing endorsements, reviewer decisions, and vendors still blocked', image:'/images/blog-2026-08-20/delegated-invoice-exception-notes.png' },
  { slug:'nonprofit-virtual-assistant-donation-acknowledgment-preparation', title:'Prepare nonprofit donation acknowledgments with a virtual assistant', excerpt:'A source-linked acknowledgment routine helps a nonprofit respond promptly while reserving tax wording, restrictions, and corrections for authorised reviewers.', audience:'a nonprofit processing gifts and donor correspondence', workflow:'donation acknowledgment preparation', record:'gift acknowledgment queue', inputs:'gift record ID, donor display preference, received date, amount or property description from the source, campaign, restriction shown, goods or services record, template version, and finance reviewer', boundary:'Stop for disputed amounts, noncash valuation, conditional gifts, unclear restrictions, refunds, tax questions, or any mismatch between the payment source and donor record.', example:'A donor asks the acknowledgment to state a value for donated equipment. The assistant records the request but does not supply a valuation; finance receives the source documents and question.', metric:'source-matched drafts, returned corrections, unresolved restrictions, duplicate acknowledgments prevented, approval age, and sent records linked to the gift system', image:'/images/blog-2026-08-20/filipino-assistant-service-recovery-routing.png' },
  { slug:'recruiting-virtual-assistant-reference-check-scheduling', title:'Coordinate reference-check scheduling with a virtual assistant', excerpt:'A scheduling lane keeps recruiting moving while preventing an assistant from evaluating references or collecting information outside the approved process.', audience:'a recruiting team arranging candidate reference conversations', workflow:'reference-check coordination', record:'reference scheduling log', inputs:'candidate ID, candidate consent state, reference-provided contact details, approved outreach template, interviewer, available windows, time zone, channel, status, and retention rule', boundary:'Stop when consent is missing, identity is uncertain, the reference volunteers sensitive information, the process differs by candidate without an approved reason, or anyone asks the assistant to judge the feedback.', example:'A reference replies with medical details about the candidate while choosing a time. The assistant limits the scheduling record and routes the message under the recruiting team’s privacy procedure.', metric:'consent verified, references contacted, appointments confirmed, identity exceptions, unneeded data removed under policy, and scheduling delays by owner', image:'/images/blog-2026-08-20/assistant-training-sample-review.png' },
  { slug:'property-management-virtual-assistant-maintenance-work-order', title:'Create a maintenance work-order triage lane for a property-management virtual assistant', excerpt:'A documented intake lane helps property teams route maintenance requests without asking an assistant to diagnose hazards, choose vendors, or authorise spend.', audience:'a property manager handling resident maintenance requests', workflow:'maintenance request intake', record:'maintenance intake record', inputs:'property and unit identifier, verified contact, resident wording, received time, approved category, photographs volunteered through the approved channel, access constraints, current status, and duty manager', boundary:'Escalate immediately under the property’s rule when safety, water, fire, gas, security, habitability, vulnerable occupants, or uncertain severity is mentioned; do not diagnose or downgrade.', example:'A resident reports a “small ceiling stain” that is spreading near a light fitting. The assistant preserves the exact description and uses the urgent route instead of deciding that it can wait.', metric:'requests acknowledged, urgent routes used, duplicate work orders, missing access details, vendor decisions pending, resident updates sent, and closure confirmed', image:'/images/blog-2026-08-20/remote-project-dependency-register.png' },
  { slug:'ecommerce-virtual-assistant-inventory-exception-queue', title:'Manage an ecommerce inventory-exception queue with a virtual assistant', excerpt:'An exception queue lets an ecommerce assistant reconcile evidence without silently changing stock, cancelling orders, or promising replenishment.', audience:'an ecommerce operation using storefront, warehouse, and supplier records', workflow:'inventory exception review', record:'inventory exception record', inputs:'SKU, storefront quantity, warehouse record, open orders, pending receipts, last sync time, evidence source, proposed correction, customer impact, and inventory owner', boundary:'Stop when systems disagree, a correction would oversell or cancel an order, bundled products complicate quantity, a supplier date is unconfirmed, or a write-off or purchase decision is needed.', example:'The storefront shows five units while the warehouse scan shows three and four orders are open. The assistant freezes no orders and invents no quantity; the conflicting evidence goes to the inventory owner.', metric:'exceptions resolved with source evidence, repeated sync failures, customer-impact cases, manual changes approved, stale supplier dates, and reopened discrepancies', image:'/images/blog-2026-08-20/outsourced-vendor-research-evidence-map.png' },
  { slug:'bookkeeping-virtual-assistant-month-end-document-chase', title:'Run a month-end document chase with a bookkeeping virtual assistant', excerpt:'A controlled document queue helps finance close its records without allowing an assistant to invent classifications, change transactions, or give accounting advice.', audience:'a small business or finance team preparing month-end records', workflow:'month-end document follow-up', record:'missing-document register', inputs:'transaction or account reference, period, document requested, source system, responsible person, request date, approved reminder cadence, response, exception reason, and finance owner', boundary:'Stop for disputed transactions, personal or unusually sensitive documents, classification questions, tax treatment, journal changes, write-offs, or requests to bypass the approved storage channel.', example:'A manager replies that a bank charge was “probably travel” but provides no receipt. The assistant records the statement as unverified and leaves classification to finance.', metric:'documents received and matched, aged gaps, duplicate requests, unsafe-channel attempts, unresolved classifications, and items formally waived by finance', image:'/images/blog-2026-08-20/delegated-invoice-exception-notes.png' },
];

const makePost = (x: Spec): BlogPost => ({
  slug:x.slug, title:x.title, excerpt:x.excerpt, minutes:9, published:'2026-09-18',
  image:{url:x.image,alt:`Operational workflow illustration for ${x.workflow}`},
  takeaway:`Define a source-linked ${x.record}, a narrow action boundary, and a named owner before delegating ${x.workflow}.`,
  sections:[
    {heading:`Start with the customer decision, not a list of tasks`,paragraphs:[`${x.excerpt} This matters for ${x.audience} because “follow up” or “keep this updated” can hide several different decisions. Write down the result the business needs, the evidence the assistant may use, and the person who owns every consequential choice.`, `A useful delegation brief separates preparation from authority. The assistant can gather approved facts, update a queue, draft a bounded message, and surface an exception. The owner still decides price, policy, legal meaning, sensitive disclosure, access, money, or a commitment to a customer. That distinction makes the role more useful because routine work can move without accidental promises.`]},
    {heading:`Define the ${x.record}`,paragraphs:[`Build one ${x.record} with ${x.inputs}. Each field should have a purpose. If a field will not change routing, prove completion, or help the reviewer decide, leave it out. Fewer well-defined fields are safer than a large form that invites private or speculative notes.`, `Name the source beside every important value. A date from an approved system is different from a date mentioned in an email, and both are different from an assistant’s assumption. Use plain states such as new, waiting for evidence, ready for review, approved, declined, and closed. A blank approval field never means approved.`]},
    {heading:`Write the authority boundary in observable terms`,paragraphs:[`${x.boundary} Put that stopping rule in the operating checklist and show the assistant the safe state in which to leave the item. “Use judgment” is not a boundary; a condition, prohibited action, owner, and response window are.`, `Tool access does not expand decision authority. The ability to edit a CRM, scheduling tool, spreadsheet, help desk, or accounting system only enables the documented step. Use the least access needed, separate draft from publish where the platform allows it, and review permissions when the lane changes.`]},
    {heading:`Design intake that survives a handoff`,paragraphs:[`Require a stable identifier, the requester’s exact wording where relevant, the source checked, the current state, and the next named actor. A colleague starting later should not need private chat history to understand what happened. In a Philippines-based support model, include the canonical time zone and the owner’s review window so a local date display does not alter a deadline.`, `Do not make completeness a reason to collect unnecessary personal data. Record only what the approved workflow needs, store it in the approved system, and link rather than duplicate sensitive documents. If information arrives through the wrong channel, preserve the minimum needed for routing and follow the company’s security or privacy procedure.`]},
    {heading:`Test the routine with a realistic exception`,paragraphs:[`${x.example} This is the kind of case that reveals whether the workflow protects the customer and the business when the happy path stops. Test examples before launch: a missing source, a conflicting record, an urgent request, an identity mismatch, and an owner who is temporarily unavailable.`, `For each test, ask four questions: What can the assistant verify? What must remain unchanged? Who receives the escalation? What evidence lets that person decide? Revise the checklist until two reviewers would route the same case the same way. The goal is repeatable restraint as well as speed.`]},
    {heading:`Create messages that do not overpromise`,paragraphs:[`Give the assistant approved message components for acknowledgment, a factual status update, a request for a missing item, and an escalation notice. The wording should identify what was received, what is still needed, and when the next update is expected without implying an outcome that has not been approved.`, `Avoid scripts that pretend every case is identical. Let the assistant select only from approved statements supported by the record. When the customer asks a new question, attach it to the item and route it. A fast but unsupported answer creates more work than a precise acknowledgment with a real next step.`]},
    {heading:`Plan the owner review window`,paragraphs:[`Delegation fails when prepared decisions wait in an invisible queue. Assign a primary reviewer, a backup for defined conditions, and a realistic review window based on consequence. The assistant should know when to remind, when to use the backup route, and when the item must remain paused.`, `Batch ordinary questions at a predictable time and interrupt only for the written urgent conditions. This keeps the owner from becoming the bottleneck while preventing urgency from turning into permission. Record the reviewer’s answer, any conditions or expiry, and whether it applies only to this case or changes the standing procedure.`]},
    {heading:`Measure quality before volume`,paragraphs:[`Review ${x.metric}. Interpret the counts together. Fewer escalations may mean clearer inputs, or they may mean the assistant is making hidden decisions. Faster closure may reflect a better process, or it may hide items closed without customer confirmation.`, `Sample ordinary completed items as well as every high-consequence exception during the launch period. Check source fidelity, correct status, minimal data handling, boundary compliance, message accuracy, and a reconstructable close. Only compare speed after those basics pass.`]},
    {heading:`Launch with a small, representative sample`,paragraphs:[`Choose a sample that includes ordinary requests, missing information, conflicts, and at least one stopping condition. Keep consequential actions in draft or review mode. The manager should compare the assistant’s record with the original source and explain corrections against the written rule rather than relying on preference.`, `Update the procedure when the same ambiguity repeats, but preserve the prior version and effective date. One owner exception is not automatically a new standing rule. A strong first week produces a clearer workflow, not merely a larger completed count.`]},
    {heading:`Turn the workflow into a hiring brief`,paragraphs:[`When evaluating an assistant, describe the systems, volume range, work hours, communication channel, review owner, and boundary cases in addition to the task name. Ask candidates to work through a sample and explain what they would verify, record, escalate, and leave unchanged.`, `OutsourcingAssistant.com can help map the role around this workflow and the surrounding administrative work. Bring the current process, example requests, tools, time-zone coverage, and approval map to a staffing conversation. The aim is a role that removes repeatable preparation from the owner while keeping business decisions with accountable people.`]}
  ],
  faqs:[
    {q:`What can a virtual assistant own in ${x.workflow}?`,a:`Source-linked intake, approved follow-up, status maintenance, preparation, and escalation can be delegated when the workflow defines them clearly.`},
    {q:'What should remain with the business owner or specialist?',a:'Keep consequential judgment, money, contractual or legal interpretation, sensitive disclosure, policy exceptions, and customer commitments with the authorised person.'},
    {q:'How should the first week be reviewed?',a:'Use a representative sample, inspect source fidelity and boundary decisions, correct the written rule, and expand access only after the sample is reliable.'}
  ],
  citations:[
    {name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework',note:'Primary framework for governance, roles, access, and risk-management context.'},
    {name:'U.S. Small Business Administration: Hire and manage employees',url:'https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees',note:'Primary small-business guidance for defining roles and managing staff.'},
    {name:'Federal Trade Commission: Protecting personal information',url:'https://www.ftc.gov/business-guidance/privacy-security/protecting-personal-information',note:'Primary guidance for limiting, protecting, and disposing of personal information.'}
  ],
  internalLinks:[
    {href:'/resources/assistant-sop-handoff-checklist',label:'Build the assistant handoff checklist'},
    {href:'/services',label:'Review virtual assistant service options'},
    {href:'/contact',label:'Discuss a role built around this workflow'}
  ],
  cta:{href:'/contact',label:'Plan the assistant role'}
});

export const dailyBlogBatch20260918: BlogPost[] = specs.map(makePost);
