import type { BlogPost } from './data';

type RecordSpec = {
  slug: string; title: string; audience: string; focus: string; outcome: string;
  firstStep: string; check: string; boundary: string; published: '2026-08-14';
};

const records: RecordSpec[] = [
  { slug: 'outsourced-assistant-inbox-priority-rules', title: 'Set inbox priority rules that an assistant can follow', audience: 'a founder whose inbox mixes customers, vendors, and personal notices', focus: 'inbox priority rules', outcome: 'a short queue of messages needing attention', firstStep: 'sort messages by consequence and promised response time', check: 'every urgent label has a reason visible in the thread', boundary: 'sending commitments or changing account settings', published: '2026-08-14' },
  { slug: 'outsourced-assistant-calendar-preparation', title: 'Prepare a calendar without taking over the owner’s judgment', audience: 'an operator whose week is crowded with meetings and follow-ups', focus: 'calendar preparation', outcome: 'a day plan with conflicts and decisions clearly marked', firstStep: 'collect meeting purpose, attendees, and required preparation', check: 'suggested changes preserve time zones and protected blocks', boundary: 'moving confidential or high-stakes meetings', published: '2026-08-14' },
  { slug: 'outsourced-assistant-customer-question-library', title: 'Keep a customer question library useful and current', audience: 'a support team answering recurring questions across channels', focus: 'customer question library', outcome: 'approved answers that are easy to find and review', firstStep: 'group real questions by intent rather than by wording', check: 'each answer names its source and review owner', boundary: 'inventing policy, remedies, or guarantees', published: '2026-08-14' },
  { slug: 'outsourced-assistant-sales-call-preparation', title: 'Prepare sales calls with facts instead of assumptions', audience: 'a small sales team that wants better context before conversations', focus: 'sales-call preparation', outcome: 'a concise brief grounded in the prospect record', firstStep: 'collect only approved facts from the original inquiry', check: 'unknown details remain marked unknown', boundary: 'qualifying fit or promising an outcome', published: '2026-08-14' },
  { slug: 'outsourced-assistant-appointment-confirmations', title: 'Make appointment confirmations clear and considerate', audience: 'a service business confirming appointments with busy customers', focus: 'appointment confirmations', outcome: 'customers receiving the right time, place, and preparation note', firstStep: 'compare the approved booking record with the message', check: 'the time zone and cancellation instructions match', boundary: 'offering exceptions or medical guidance', published: '2026-08-14' },
  { slug: 'outsourced-assistant-file-naming-standards', title: 'Use file naming standards people will actually follow', audience: 'a distributed team that loses time searching shared folders', focus: 'file naming standards', outcome: 'records that can be located without opening every file', firstStep: 'choose names based on purpose, date, and owner', check: 'a new teammate can find a sample without coaching', boundary: 'deleting records or changing retention requirements', published: '2026-08-14' },
  { slug: 'outsourced-assistant-meeting-action-register', title: 'Turn meeting decisions into a dependable action register', audience: 'a growing team that needs ownership after recurring meetings', focus: 'meeting action registers', outcome: 'decisions, owners, and due dates visible in one place', firstStep: 'separate decisions from suggestions and discussion notes', check: 'each action links to the meeting or approved source', boundary: 'rewriting decisions or assigning unapproved owners', published: '2026-08-14' },
  { slug: 'outsourced-assistant-vendor-invoice-matching', title: 'Match vendor invoices to records before review', audience: 'an operations team handling recurring supplier invoices', focus: 'vendor invoice matching', outcome: 'review packets with missing or conflicting evidence flagged', firstStep: 'compare supplier, date, amount, and purchase reference', check: 'differences are shown rather than silently corrected', boundary: 'approving payment or changing bank details', published: '2026-08-14' },
  { slug: 'outsourced-assistant-customer-onboarding-records', title: 'Keep customer onboarding records easy to understand', audience: 'a service team guiding new customers through first steps', focus: 'customer onboarding records', outcome: 'a visible list of received, pending, and approved items', firstStep: 'define the minimum information needed for each stage', check: 'every status points to a source or owner', boundary: 'accepting terms or making suitability decisions', published: '2026-08-14' },
  { slug: 'outsourced-assistant-service-area-records', title: 'Maintain service-area records without overpromising coverage', audience: 'a local business receiving inquiries from several locations', focus: 'service-area records', outcome: 'current locations ready for an owner to confirm', firstStep: 'map locations to the approved service-area source', check: 'borderline requests are marked for review', boundary: 'promising availability or interpreting local rules', published: '2026-08-14' },
  { slug: 'outsourced-assistant-customer-feedback-coding', title: 'Code customer feedback without flattening what people said', audience: 'a business trying to learn from customer comments', focus: 'customer feedback coding', outcome: 'themes that retain the original comment and context', firstStep: 'create a small label set before reviewing a sample', check: 'labels can be traced back to the original wording', boundary: 'editing testimony or presenting themes as research findings', published: '2026-08-14' },
  { slug: 'outsourced-assistant-contact-consent-records', title: 'Keep contact-consent records understandable', audience: 'a team communicating with contacts across several channels', focus: 'contact-consent records', outcome: 'clear evidence of what communication was permitted', firstStep: 'record source, date, channel, and stated preference', check: 'a message cannot be sent when the permission is unclear', boundary: 'overriding opt-outs or making legal determinations', published: '2026-08-14' },
  { slug: 'outsourced-assistant-returns-case-preparation', title: 'Prepare return cases without deciding the remedy', audience: 'an online seller handling routine return questions', focus: 'return case preparation', outcome: 'complete cases ready for an authorized review', firstStep: 'match the customer request to the order and policy source', check: 'item, order, date, and requested remedy agree', boundary: 'approving refunds, exceptions, or chargebacks', published: '2026-08-14' },
  { slug: 'outsourced-assistant-event-registration-records', title: 'Keep event registration records ready for the host', audience: 'a team coordinating a small educational or community event', focus: 'event registration records', outcome: 'a current roster with questions and access needs flagged', firstStep: 'capture the approved registration fields and source', check: 'changes preserve the registration timestamp and note', boundary: 'admitting people against policy or revealing private details', published: '2026-08-14' },
  { slug: 'outsourced-assistant-website-contact-details-review', title: 'Review website contact details before visitors rely on them', audience: 'a business with contact information spread across its site', focus: 'website contact-detail review', outcome: 'a short list of confirmed or questionable details', firstStep: 'compare each page against the named business source', check: 'phone, email, hours, and links are checked separately', boundary: 'publishing unapproved claims or changing legal notices', published: '2026-08-14' },
  { slug: 'outsourced-assistant-client-status-notes', title: 'Write client status notes that reduce follow-up questions', audience: 'a professional service team managing several active accounts', focus: 'client status notes', outcome: 'a factual snapshot of progress, blockers, and next owners', firstStep: 'separate completed work from waiting and proposed work', check: 'each statement has a date or source record', boundary: 'changing scope or giving professional advice', published: '2026-08-14' },
  { slug: 'outsourced-assistant-duplicate-record-review', title: 'Review duplicate records without losing history', audience: 'a team whose customer or vendor database has repeated entries', focus: 'duplicate-record review', outcome: 'possible matches ready for an owner’s merge decision', firstStep: 'compare stable identifiers before comparing names alone', check: 'every proposed match retains both source records', boundary: 'deleting history or merging uncertain identities', published: '2026-08-14' },
  { slug: 'outsourced-assistant-renewal-notice-preparation', title: 'Prepare renewal notices from the records that govern them', audience: 'a service business tracking recurring customer agreements', focus: 'renewal notice preparation', outcome: 'draft notices tied to the current agreement and date', firstStep: 'locate the approved term, notice window, and contact path', check: 'the draft matches the latest signed record', boundary: 'changing terms or negotiating continuation', published: '2026-08-14' },
  { slug: 'outsourced-assistant-local-business-directory-updates', title: 'Update local business directory details carefully', audience: 'a local operator maintaining listings in several directories', focus: 'directory detail updates', outcome: 'consistent public details with changes documented', firstStep: 'establish one approved source for name, address, and hours', check: 'each change is recorded with the directory and date', boundary: 'creating listings or making claims the owner has not approved', published: '2026-08-14' },
  { slug: 'outsourced-assistant-shared-calendar-permissions', title: 'Review shared-calendar permissions as responsibilities change', audience: 'a team where several people coordinate through shared calendars', focus: 'shared-calendar permissions', outcome: 'calendar access that matches current responsibilities', firstStep: 'list calendars, users, and the purpose of each permission', check: 'a sample user sees only the agreed detail level', boundary: 'accessing private events or changing owner settings', published: '2026-08-14' },
  { slug: 'outsourced-assistant-customer-address-verification', title: 'Verify customer addresses without guessing missing details', audience: 'a business sending documents or goods to customers', focus: 'customer address verification', outcome: 'address records with clear evidence and unresolved gaps', firstStep: 'compare the submitted address with the approved customer record', check: 'unconfirmed unit, postal, or country details stay visible', boundary: 'altering an address or inferring identity', published: '2026-08-14' },
  { slug: 'outsourced-assistant-business-records-archive-review', title: 'Review business records for archiving without deleting them', audience: 'a small company with folders full of completed work', focus: 'records archive review', outcome: 'a proposed archive list with owners and reasons', firstStep: 'group records by status, owner, and approved retention rule', check: 'every proposed move can be reversed and explained', boundary: 'deleting records or interpreting retention law', published: '2026-08-14' }
];

function makePost(record: RecordSpec): BlogPost {
  return {
    slug: record.slug,
    title: record.title,
    published: record.published,
    minutes: 8,
    excerpt: `A practical guide for ${record.audience}: structure ${record.focus} so the result is useful, reviewable, and within a clear owner boundary.`,
    takeaway: `Define ${record.outcome} before handing off ${record.focus}; begin with ${record.firstStep}, and keep ${record.boundary} with the owner.`,
    sections: [
      { heading: 'Define the finished record', body: `For ${record.focus}, finished work is ${record.outcome}. Write that result into the brief, name the source of truth, and identify the person who reviews it. A precise finish line makes support useful without inviting guesses.` },
      { heading: 'Start with a bounded request', body: `Begin with ${record.firstStep}. Provide one approved example and one exception. This gives the assistant enough context to prepare dependable work while leaving judgment with the person who owns the decision.` },
      { heading: 'Use a check that catches drift', body: `Apply this check before expanding the lane: ${record.check}. Review a small sample, record corrections, and update the example when the same question returns.` },
      { heading: 'Protect the decision boundary', body: `Pause when work reaches ${record.boundary}. Preserve the relevant context, state what is missing, and route it to the named owner. A clear boundary is part of good service, not a delay.` },
      { heading: 'Leave a readable handoff', body: `End with completed items, items waiting for review, open questions, and the next action. Keep the note beside the source record so the owner can understand status without reconstructing it from messages.` },
      { heading: 'Improve from real corrections', body: `After the first few cycles, look for repeated corrections in ${record.focus}. Improve the brief, permission, or example that caused the confusion. Small evidence-based changes make the next handoff easier to trust.` }
    ],
    faqs: [
      { q: `What if ${record.focus} is unclear?`, a: 'Pause, record the missing context, and use the agreed escalation path. Do not guess at a customer-facing or irreversible decision.' },
      { q: 'What should the owner review first?', a: 'Review a small initial sample closely, then use a consistent sample only after accuracy and escalation judgment are stable.' },
      { q: 'What belongs in the handoff?', a: 'Include the trigger, source of truth, finished result, examples, approval boundary, and route for questions.' }
    ],
    internalLinks: [{ href: '/resources/assistant-sop-handoff-checklist', label: 'Assistant handoff checklist' }, { href: '/services', label: 'Outsourced assistant services' }]
  };
}

export const dailyBlogBatch20260814: BlogPost[] = records.map(makePost);
