import type { BlogPost } from './data';

const published = '2026-08-31';
const citations = [
  { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework', note: 'Governance, access, and review context.' },
  { name: 'CISA Secure Our World', url: 'https://www.cisa.gov/secure-our-world', note: 'Plain-language account and phishing safeguards.' },
  { name: 'U.S. Small Business Administration hiring guidance', url: 'https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees', note: 'General hiring and management context.' },
];

type Spec = { slug: string; title: string; problem: string; input: string; work: string; boundary: string; example: string; measure: string };
const specs: Spec[] = [
  { slug: 'virtual-assistant-password-reset-request-log', title: 'Build a password reset request log for a virtual assistant', problem: 'password reset messages can look routine while changing control of an account', input: 'the requester, account, known contact channel, time received, and stated reason', work: 'record the request, compare it with the approved account list, and prepare a verification note', boundary: 'The assistant must not change recovery details or disclose a code. An account owner verifies the request through a known channel and performs or approves the reset.', example: 'A supplier emails a new phone number and asks for a code. The assistant logs the message and calls the number already stored in the vendor record, not the number in the email.', measure: 'Track requests verified, requests rejected, owner response time, and any incomplete records.' },
  { slug: 'executive-assistant-meeting-decision-register', title: 'Use a meeting decision register after executive calls', problem: 'meeting notes become hard to use when decisions, ideas, and open questions are mixed together', input: 'the approved recording or notes, attendee list, agenda, and named meeting owner', work: 'separate decisions from actions, attach an owner and due date, and flag wording that needs confirmation', boundary: 'The assistant records what was said but does not invent agreement, assign authority, or circulate sensitive notes beyond the approved group.', example: '“Explore a September launch” stays an open question until the executive confirms a date; it is not entered as a commitment.', measure: 'Review confirmed decisions, corrected entries, overdue actions, and questions returned to the meeting owner.' },
  { slug: 'customer-support-refund-evidence-packet', title: 'Prepare a refund evidence packet without granting refund authority', problem: 'a support queue can pressure an assistant to decide before the order record is complete', input: 'the order, customer message, delivery record, policy version, prior contacts, and requested remedy', work: 'assemble the timeline, match the request to the approved policy, and draft a neutral reply', boundary: 'The assistant does not approve exceptions, move money, or promise an outcome unless the written authority table allows that exact action.', example: 'A late-delivery request includes a partial tracking history. The assistant gathers the missing carrier event and routes the complete packet to the refund owner.', measure: 'Count complete packets, missing-evidence returns, decision time after handoff, and policy exceptions.' },
  { slug: 'crm-merge-candidate-review-queue', title: 'Create a CRM merge-candidate review queue', problem: 'duplicate records are easy to spot but risky to merge when histories or ownership differ', input: 'record IDs, source systems, email and phone fields, activity history, owner, and consent status', work: 'identify likely matches, preserve field provenance, and propose a surviving record', boundary: 'The assistant must not merge records with conflicting consent, account ownership, legal holds, or material transaction history without owner approval.', example: 'Two contacts share an email but belong to different business units. The assistant marks the collision instead of assuming they are one person.', measure: 'Track proposed pairs, approved merges, rejected matches, restored fields, and downstream report checks.' },
  { slug: 'vendor-bank-detail-change-verification', title: 'Verify vendor bank-detail changes before accounts payable updates', problem: 'an authentic-looking message can redirect a legitimate payment', input: 'the original vendor record, change request, invoice, approved callback method, and accounts-payable owner', work: 'preserve the request, compare identifiers, and schedule independent verification', boundary: 'A virtual assistant never changes payment instructions or confirms that a transfer will occur. The authorized finance owner makes the change after verification.', example: 'An invoice footer shows a new account. The assistant pauses invoice preparation and contacts the vendor through the number already on file.', measure: 'Review attempted changes, verification outcomes, blocked payments, and time to owner decision.' },
  { slug: 'calendar-delegate-private-event-screening', title: 'Screen private calendar events with delegated access', problem: 'calendar cleanup can expose personal or restricted details that are irrelevant to the task', input: 'calendar permissions, privacy labels, approved working hours, meeting categories, and escalation rules', work: 'prepare conflicts from permitted fields and leave private descriptions unopened where the platform allows', boundary: 'The assistant does not reveal attendee names, copy private notes, or move a protected event without the calendar owner.', example: 'A private block conflicts with a sales call. The assistant reports that the time is unavailable without naming the private event.', measure: 'Audit protected-event access, conflict accuracy, owner corrections, and unauthorized disclosure incidents.' },
  { slug: 'assistant-shared-mailbox-coverage-map', title: 'Map shared-mailbox coverage for a remote assistant', problem: 'messages fall between shifts when nobody knows which queue or response window applies', input: 'mailbox folders, message types, work hours in Philippine Time, owner coverage, and service targets', work: 'route messages by type, prepare routine drafts, and leave a dated end-of-shift status', boundary: 'The assistant does not make legal, pricing, refund, security, or contractual commitments outside approved templates.', example: 'A routine address correction receives a draft; a threatened chargeback goes to the named support owner with the full thread attached.', measure: 'Measure unassigned messages, first-review time, reopened items, and aged exceptions by queue.' },
  { slug: 'research-assistant-source-access-register', title: 'Keep a source-access register for delegated research', problem: 'research quality suffers when sources disappear or nobody can tell which version supported a claim', input: 'source URL, publisher, publication date, access date, relevant passage, scope, and archive policy', work: 'record each source before drafting and link it to the sentence or decision it supports', boundary: 'The assistant does not bypass paywalls, copy restricted material, or treat a search snippet as evidence.', example: 'A public agency page supplies a definition. The assistant records the page date and scope rather than transferring the definition to a different population.', measure: 'Check broken sources, unsupported claims, scope corrections, and time needed to reconstruct a citation.' },
  { slug: 'virtual-assistant-device-return-checklist', title: 'Run a device return checklist when an assistant role ends', problem: 'offboarding can close an account while leaving files, sessions, or company equipment unresolved', input: 'the asset register, account list, device identifier, shipping method, open work, and offboarding owner', work: 'confirm the inventory, prepare return instructions, preserve business files, and record each completed step', boundary: 'The assistant does not wipe a device, transfer private files, or certify access closure. Authorized IT or the account owner completes those actions.', example: 'The laptop is in transit but the account is already disabled. The checklist keeps shipment status separate from session revocation evidence.', measure: 'Track assets recovered, accounts disabled, sessions revoked, open tasks transferred, and exceptions with owners.' },
  { slug: 'lead-qualification-unknown-field-policy', title: 'Write an unknown-field policy for delegated lead qualification', problem: 'blank CRM fields tempt assistants to infer budget, authority, location, or intent', input: 'the approved qualification fields, source message, form data, CRM history, and routing rules', work: 'copy verified facts, mark unknowns plainly, and draft one approved follow-up question when useful', boundary: 'The assistant does not guess protected traits, purchasing authority, fit, or deal value, and does not reject a lead outside the written rule.', example: 'A founder title does not prove budget authority. The record stays “unknown” until the prospect or an approved source confirms it.', measure: 'Review inferred-field corrections, unanswered questions, routing accuracy, and lead records returned for evidence.' },
  { slug: 'assistant-recurring-report-cutoff-rules', title: 'Set cutoff rules for an assistant-prepared recurring report', problem: 'a weekly report can look final even when late data and unresolved corrections are hidden', input: 'the reporting period, source systems, extraction time, known gaps, prior corrections, and report owner', work: 'freeze the stated period, reconcile totals, annotate missing inputs, and prepare a variance note', boundary: 'The assistant cannot silently estimate missing values or change the definition of a metric to meet the deadline.', example: 'Two invoices arrive after cutoff. The report names them as late items for the next period instead of quietly changing the closed total.', measure: 'Track late inputs, reconciliation differences, reopened reports, and owner-approved adjustments.' },
  { slug: 'outsourced-sop-example-library-governance', title: 'Govern an SOP example library for outsourced work', problem: 'old examples can quietly override the current procedure when assistants copy them', input: 'the active SOP, example owner, creation date, applicable scenario, redactions, and review date', work: 'label each example, remove stale copies, connect it to the current rule, and flag contradictions', boundary: 'An example illustrates a rule; it does not create a new permission or exception. The process owner approves any policy change.', example: 'An old email shows a discount that is no longer authorized. It remains archived for history but is removed from the training set.', measure: 'Audit stale examples, contradictory guidance, review age, and corrections traced to the library.' },
];

const makePost = (s: Spec): BlogPost => ({
  slug: s.slug, title: s.title,
  excerpt: `A practical OutsourcingAssistant.com routine addressing this risk: ${s.problem}. It includes a clear evidence trail and owner approval boundary.`,
  minutes: 9, published,
  image: { url: '/assistant-collaboration.jpg', alt: `A team reviewing the ${s.title.toLowerCase()} workflow` },
  takeaway: `${s.work}. Keep consequential decisions with the named owner.`,
  sections: [
    { heading: 'Name the risk before assigning the task', body: `${s.problem[0].toUpperCase()}${s.problem.slice(1)}. Write the expected result in one sentence and identify who owns the final decision. A Philippines-based assistant can prepare the record during an earlier work window, but elapsed time and a polished draft do not create authority.` },
    { heading: 'Collect the minimum useful record', body: `Start with ${s.input}. Keep the original request beside the working note. If an input is missing or contradictory, mark it as unknown and route a narrow question. Do not fill a blank with a likely answer.` },
    { heading: 'Give the assistant a bounded sequence', body: `The delegated lane is to ${s.work}. Use separate states for received, checking, waiting, prepared, approved, and closed. This makes the handoff readable and prevents “done” from being confused with “approved.”` },
    { heading: 'Keep the approval line plain', body: s.boundary },
    { heading: 'Test the rule with a realistic case', body: `${s.example} The example belongs in training only after private details are removed and the process owner confirms that it still matches the current rule.` },
    { heading: 'Review evidence, not confidence', body: `${s.measure} Sample both ordinary work and exceptions. A confident note with a missing source should be returned; a careful escalation with complete evidence is useful work.` },
    { heading: 'Make the time-zone handoff easy to resume', body: 'The end-of-shift note should state what changed, what did not change, the evidence checked, the decision still needed, the next permitted action, and the owner’s review window. Silence means waiting. It never means approval.' },
    { heading: 'Tighten the routine after real use', body: 'When the same question appears twice, repair the SOP or example library. Expand access only after reviewed samples show that the current lane is stable. Remove access that the task no longer needs, and preserve the approval record with the work.' },
  ],
  faqs: [
    { q: 'Can the assistant complete this process without owner review?', a: 'The assistant can complete the documented preparation steps. Any exception or consequential action stays with the named owner unless a written authority table says otherwise.' },
    { q: 'What belongs in the handoff note?', a: 'Include the request, evidence checked, current state, open question, next permitted action, owner, and review window.' },
    { q: 'How often should the routine be reviewed?', a: 'Review early samples closely, then use a regular sample and exception review. Revisit the procedure whenever authority, tools, or source records change.' },
  ],
  citations,
  internalLinks: [{ href: '/resources/assistant-sop-handoff-checklist', label: 'Use the assistant SOP handoff checklist' }, { href: '/services', label: 'Review outsourcing support services' }],
  cta: { href: '/contact', label: 'Plan a controlled assistant workflow' },
});

export const dailyBlogBatch20260831: BlogPost[] = specs.map(makePost);
