import type { BlogPost } from './data';

const published = '2026-08-23';
type RecordSpec = { slug: string; title: string; audience: string; decision: string; inputs: string; sequence: string; hazard: string; measure: string; example: string; };

const records: RecordSpec[] = [
  ['assistant-daily-content-brief-intake','Turn a daily article idea into a usable assistant brief','an owner who has ideas in messages but needs a repeatable article queue','whether a topic is specific enough to research and draft','the reader question, business context, approved service language, evidence limit, and reviewer','capture the question, narrow the promise, list sources to check, and record the approval gate','publishing an attractive topic that has no audience decision or supportable conclusion','brief completeness, source coverage, returned questions, and approval time','a brief about inbox delegation becomes a decision guide with a defined reader, not a generic listicle'],
  ['assistant-source-packet-research-routine','Build a source packet before an assistant drafts a blog article','a site owner who wants sourced outsourcing guidance without handing over editorial judgment','whether the available evidence supports the intended claim','official guidance, dated reports, company-approved facts, and notes about what each source cannot prove','search by claim, save the relevant passage, record date and scope, then mark inference separately','treating a search result, anecdote, or vendor promise as proof of a business outcome','source-to-claim links, missing-evidence flags, and reviewer corrections','a claim about access control is connected to NIST guidance while the article avoids promising security'],
  ['assistant-article-outline-approval','Approve an article outline without losing the owner boundary','an operator reviewing outlines prepared by a Philippines-based assistant','whether the structure answers one practical outsourcing decision','working title, audience, thesis, section questions, evidence plan, links, and red lines','check the decision, test section order, remove overlap, and approve only the bounded structure','allowing an outline to smuggle in pricing, guarantees, or professional advice','outline return reasons, duplicated sections, and claims changed before drafting','a support-queue outline keeps refund authority with the owner while explaining the assistant intake lane'],
  ['assistant-editorial-fact-check-register','Use a fact-check register for recurring assistant content','an editor maintaining a daily publishing routine across several service topics','which statements require a source, owner confirmation, or removal','claim text, source URL, date, scope, confidence note, and responsible reviewer','split facts from examples, verify each external statement, and close unresolved rows before approval','leaving plausible but unsupported numbers, credentials, testimonials, or results in public copy','open claims at review, correction categories, and time from flag to resolution','a staffing workflow can describe role boundaries without inventing a client result or headcount'],
  ['assistant-content-calendar-dependency-map','Map dependencies in a daily content calendar','a founder coordinating research, drafting, editing, images, and publishing across time zones','what must be ready before an article can move to the next state','topic owner, source packet, draft, image decision, links, date, reviewer, and route','show prerequisites, assign the next decision, and keep blocked items visible rather than silently late','declaring an article ready because the prose is finished while its date or route is unresolved','blocked-age, dependency completion, and same-day release accuracy','a missing source keeps one article in review without holding unrelated approved work'],
  ['assistant-article-duplicate-topic-check','Check a topic for overlap before assigning it to an assistant','an editor with a growing blog about Filipino talent and delegated operations','whether a proposed article adds a new reader decision rather than renaming an old one','existing titles, slugs, theses, section questions, examples, and conclusions','compare the proposed identity, state the new angle, and reject shallow rewrites','re-dating an old route, swapping nouns, or repeating the same paragraph framework','overlap findings, rejected topics, and genuinely new route identities','“calendar handoff” and “calendar access review” differ because one governs scheduling work and the other governs permission evidence'],
  ['assistant-blog-image-brief-review','Review a blog hero-image brief for truthful outsourcing guidance','a site owner commissioning visuals for articles about assistant workflows','whether the image supports the article without inventing a scene or company fact','visual subject, accessibility description, exclusions, route, and relationship to the thesis','describe the operating situation, remove unverifiable details, check contrast, and record the asset path','using a stock-like image that implies a client, location, result, or credential not stated in copy','brief-to-image match, accessibility corrections, and asset-route checks','a queue diagram can show review states without pretending to depict a real customer team'],
  ['assistant-visible-date-publishing-check','Make visible and structured article dates agree','an operator publishing a same-day batch from a data-driven Next.js blog','whether route, visible time element, metadata, and sitemap share one date','literal published value, formatted display date, canonical route, JSON-LD, and sitemap lastmod','set the source date, render it, inspect structured data, and compare the generated sitemap','showing an old date in the page while claiming a new campaign date in a registry','routes passing all date checks and any mismatches repaired before push','August 23, 2026 appears in the reader-facing time element and 2026-08-23 appears in BlogPosting data'],
  ['assistant-article-word-count-substance','Measure article length without padding an assistant draft','an editor who needs long-form articles that remain useful to founders and operators','whether every section adds reasoning, examples, or a safe implementation choice','body text, section purpose, reader question, examples, and unresolved boundary','count prose, remove duplicated filler, add missing explanation, and reread for decision value','repeating a slogan, hiding production mechanics in public copy, or inflating word count with empty sentences','substantive words, unique section purpose, and returned passages','a CRM cleanup article explains field provenance, deletion risk, review evidence, and escalation instead of repeating “use an SOP”'],
  ['assistant-escalation-copy-review','Write escalation guidance an outsourced assistant can actually follow','a manager defining hard stops for remote administrative work','which requests can be completed, drafted, paused, or routed','task examples, authority limits, evidence needed, owner, channel, and response expectation','classify the request, preserve context, state the missing decision, and route it to the named owner','letting urgency, customer pressure, or time-zone gaps turn a draft role into an approval role','correct routing, incomplete-context returns, and unresolved exception age','a bank-detail change is preserved and independently verified rather than answered from the incoming message'],
  ['assistant-article-internal-link-audit','Audit internal links so daily articles form a useful learning path','a content operator connecting readers from a workflow question to the next planning resource','whether each link advances the same decision and names its destination honestly','source route, target route, anchor label, context, and fallback if the page changes','test the target, rewrite vague labels, remove promotional detours, and keep the path proportional','linking every article to the same contact call or claiming a resource explains something it does not','broken links, misleading labels, and reader path completion','an article about SOPs points to the handoff checklist because it helps the reader define inputs and approvals'],
  ['assistant-publish-queue-handoff-note','Create a handoff note that keeps article work moving across shifts','an owner and Philippines-based assistant working in different review windows','what the next person must know to resume without searching private messages','route, state, completed checks, open questions, source gaps, owner, and next review window','separate done from approved, attach evidence, name the blocker, and leave one concrete next action','turning a polished draft into a publication claim while dates, sources, or permissions remain open','handoff completeness, resumed-work time, and state-transition errors','a note says “draft ready; date check open; editor owns decision by next review” instead of “finished”'],
].map(([slug,title,audience,decision,inputs,sequence,hazard,measure,example]) => ({slug,title,audience,decision,inputs,sequence,hazard,measure,example}));

function makePost(r: RecordSpec): BlogPost {
  const intro = `For ${r.audience}, the useful question is ${r.decision}. OutsourcingAssistant.com readers are not helped by a broad promise that an assistant can “handle content.” They need to know which repeatable actions can be prepared, which evidence makes the work reviewable, and which judgment remains with the owner. This guide treats a Philippines-based assistant as a capable operator inside a defined lane: the assistant can gather, organize, draft, compare, and report; an authorized owner approves claims, access, commitments, and publication.`;
  const sections = [
    ['Start with the reader decision', `${intro} Begin with one decision rather than a category. ${r.example} State what a reader should be able to decide after reading, then state what the article will not decide. This keeps the topic central to practical outsourcing instead of drifting into abstract productivity advice. A narrow decision also gives the editor a useful test: if a proposed paragraph does not help the reader understand the work, evidence, risk, or next action, it belongs in another article or should be removed.`],
    ['Name the inputs and their owners', `A reliable lane begins with ${r.inputs}. Put each input beside its source and owner. The assistant should know whether a fact comes from an approved service page, a public authority, an existing operating record, or a hypothetical example. “Find something about this” is not a sufficient brief because it hides the evidence standard and invites accidental invention. The owner supplies missing business facts and approves sensitive wording; the assistant records what is unavailable instead of filling the gap with a plausible detail. That small discipline makes remote handoff safer across time zones.`],
    ['Design the work as observable steps', `Use this sequence: ${r.sequence}. Each step should leave a visible artifact such as a brief, source row, comparison note, draft, correction record, or approval state. Observable work is easier to train than a personality-based instruction such as “use good judgment.” It also lets a manager separate a weak source packet from a weak draft. For recurring blog work, the queue should show prepared, researching, evidence ready, drafting, editorial review, revision requested, approved, and published as different states. An assistant may advance preparation states when the finish line is clear; the editor owns public approval.`],
    ['Protect the boundary', `The hard stop is ${r.hazard}. Write it in plain language and put it beside the task, not in a policy document nobody opens. A Filipino assistant can flag the request, preserve the relevant context, prepare a draft, and route it to the named reviewer. The assistant should not create a credential, promise a result, infer a customer story, publish pricing, or turn a general source into professional advice. The owner also needs an escalation channel that works during the assistant's Philippine work window. If the owner is unavailable, waiting with a clear note is safer than improvising authority.`],
    ['Use examples without inventing facts', `Examples make a routine teachable, but they must be labeled honestly. Use a hypothetical queue, an anonymized field list, or a generic decision tree; do not imply that an unnamed company achieved a result. In this lane, ${r.example}. Show the input, the assistant's bounded action, the evidence left behind, and the decision reserved for the owner. That format teaches a process without manufacturing a testimonial. It also helps the editor catch unsupported claims before they reach the public page. Where a source is time-sensitive, include its date and scope so the reader can judge whether it still applies.`],
    ['Review quality for the actual risk', `A review should measure ${r.measure}. Counting completed drafts alone rewards motion, not usefulness. Sample whether the article answers its opening question, preserves the niche of outsourced assistant work, names a real owner boundary, and links factual statements to support. Review route, title, excerpt, date, canonical, structured data, visible wording, and sitemap entry as one public identity. When a correction recurs, improve the brief or checklist rather than relying on memory. A short correction log gives the next assistant better examples and tells the owner whether the lane is ready for a larger workload.`],
    ['Handle exceptions and handoffs', `A time-zone handoff should tell the next person what is complete, what is waiting, and what decision is needed. Separate “drafted” from “approved,” and separate “source found” from “claim verified.” Record the route, source paths, open questions, and next owner in one place. If a dependency is missing, mark the article blocked and continue unrelated work rather than quietly changing the scope. This is especially important for a daily publishing routine: a fast queue is not a trustworthy queue if the next reviewer cannot reconstruct why a statement, date, image, or link was accepted.`],
    ['Expand only after a clean sample', `Start with a small sample of ${r.decision.toLowerCase()} work and review it closely. Expand one responsibility at a time after the assistant consistently follows the lane, raises uncertainty, and leaves usable evidence. Access should follow the task, not the title: research access is not publishing access, and drafting access is not approval authority. Keep an owner for each exception and a date for reviewing the rule. The purpose of delegation is dependable capacity for founders and operators, not the disappearance of accountability. A bounded lane that can be inspected is a stronger foundation than a large role nobody can evaluate.`],
    ['Close with a safe next action', `The practical next action is to write a one-page version of this routine: reader decision, inputs, sequence, examples, hard stops, evidence, reviewer, and handoff note. Test it on one real but low-risk work item. Ask whether a new assistant could tell what to do, what not to do, and where to put uncertainty without asking a private-message scavenger hunt. Then have the owner review the result against the original decision. If the answer is still unclear, narrow the brief before adding tools or permissions. That is how OutsourcingAssistant.com turns daily article creation into a repeatable support routine while keeping consequential judgment with the authorized owner.`]
  ];
  return { slug: r.slug, title: r.title, published, excerpt: `A practical OutsourcingAssistant guide to ${r.decision.toLowerCase()}, with bounded assistant work, evidence, and owner review.`, minutes: 11, takeaway: `Define the decision, make the assistant's work observable, and keep ${r.hazard} with the authorized owner.`, sections: sections.map(([heading,body]) => ({heading,body})), faqs: [
    { q: 'What can the assistant own?', a: 'The assistant can perform the documented preparation and routine actions, record evidence, and escalate anything outside the approved lane.' },
    { q: 'What should the owner review?', a: 'The owner reviews claims, sensitive data, access changes, commitments, exceptions, and the final public identity of the article.' },
    { q: 'What proves the routine is ready to expand?', a: 'A clean sample with traceable inputs, correct escalation, useful handoffs, and no unresolved boundary or date errors.' }
  ], internalLinks: [{ href: '/resources/assistant-sop-handoff-checklist', label: 'Use the assistant SOP handoff checklist' }, { href: '/services', label: 'Review assistant services' }, { href: '/contact', label: 'Plan a bounded staffing role' }] };
}

export const dailyBlogBatch20260823: BlogPost[] = records.map(makePost);
