import type { BlogPost } from './data';

type Spec = { slug:string; title:string; excerpt:string; lane:string; artifact:string; inputs:string; boundary:string; example:string; image:string };
const specs: Spec[] = [
  {slug:'assistant-monday-workload-reconciliation',title:'Reconcile Monday workload before an assistant starts the queue',excerpt:'A short Monday reconciliation exposes stale tasks, new deadlines, and owner decisions before work fans out.',lane:'weekly operations',artifact:'Monday workload reconciliation',inputs:'open tasks, promised dates, blockers, changed priorities, and decision owners',boundary:'The assistant may verify status and propose an order; the owner changes commitments, cancels work, or accepts deadline risk.',example:'Two Friday tasks remain open and a client request arrives Monday. The assistant shows the collision and asks the owner to choose the sequence.',image:'/images/blog-2026-08-20/cross-timezone-queue-status-note.png'},
  {slug:'virtual-assistant-password-reset-intake',title:'Give a virtual assistant a safe password-reset intake lane',excerpt:'A bounded intake routine captures the request without letting urgency bypass identity and access controls.',lane:'access support',artifact:'password-reset intake record',inputs:'requester, affected account, approved contact route, observed issue, time, and access owner',boundary:'The assistant may capture and route the request; only an authorised administrator verifies identity, resets credentials, or changes recovery methods.',example:'A senior employee asks through a new chat account. The assistant uses the directory-listed route and does not send a reset link.',image:'/images/blog-2026-08-20/least-privilege-tool-onboarding-assistant.png'},
  {slug:'outsourced-customer-complaint-evidence-pack',title:'Build a customer-complaint evidence pack before escalation',excerpt:'A consistent evidence pack helps the owner review a complaint without forcing the assistant to decide fault or remedy.',lane:'customer support',artifact:'complaint evidence pack',inputs:'customer statement, order or case ID, timeline, prior replies, policy version, requested remedy, and owner',boundary:'The assistant can organise facts and draft a neutral acknowledgement; fault, refunds, legal positions, and goodwill commitments stay with approved staff.',example:'A customer says a promise was made by phone. The assistant records the claim and searches approved notes without treating an absent note as proof either way.',image:'/images/blog-2026-08-20/filipino-assistant-service-recovery-routing.png'},
  {slug:'assistant-calendar-invite-identity-check',title:'Check identity before an assistant accepts an unfamiliar calendar invite',excerpt:'An invite check separates scheduling preparation from trust, disclosure, and executive commitment.',lane:'calendar support',artifact:'invite identity check',inputs:'sender address, stated organisation, meeting purpose, attendees, links, prior relationship, and executive preference',boundary:'The assistant may research and prepare a recommendation; the executive decides attendance and any disclosure to an unfamiliar party.',example:'A familiar company name appears on a look-alike domain. The assistant flags the mismatch and verifies through a known contact route.',image:'/images/blog-2026-08-20/remote-meeting-preparation-brief.png'},
  {slug:'crm-duplicate-contact-merge-proposal',title:'Prepare CRM duplicate-contact merges without erasing evidence',excerpt:'A merge proposal preserves source records and ambiguity until the CRM owner approves the surviving identity.',lane:'CRM administration',artifact:'duplicate-contact merge proposal',inputs:'record IDs, matching fields, source systems, activity history, conflicts, proposed survivor, and reviewer',boundary:'The assistant may identify likely duplicates and prepare a comparison; the CRM owner approves merges, deletions, and field precedence.',example:'Two contacts share an email but have different employers. The assistant preserves both and flags the conflict instead of merging on one field.',image:'/images/blog-2026-08-21/filipino-assistant-data-cleanup-scope.png'},
  {slug:'bookkeeping-support-missing-receipt-chase',title:'Run a missing-receipt chase without inventing expense evidence',excerpt:'A receipt queue makes follow-up visible while keeping coding, approval, and tax judgments with the right owner.',lane:'bookkeeping support',artifact:'missing-receipt queue',inputs:'transaction date, merchant, amount, cardholder, request history, deadline, and bookkeeping owner',boundary:'The assistant may request and file evidence; authorised staff decide coding, deductibility, reimbursement, and exceptions.',example:'The cardholder remembers a meal but cannot find a receipt. The assistant records the statement separately and routes the exception for review.',image:'/images/blog-2026-08-20/delegated-invoice-exception-notes.png'},
  {slug:'vendor-bank-detail-change-verification',title:'Verify vendor bank-detail changes outside the request channel',excerpt:'A second-channel check gives an assistant a clear stop rule for a high-consequence vendor update.',lane:'vendor administration',artifact:'bank-detail verification record',inputs:'vendor legal name, request source, existing contact on file, callback result, approver, and effective date',boundary:'The assistant may collect evidence and arrange verification; only authorised finance staff change payment details or release funds.',example:'An invoice email announces a new account. The assistant calls the established number on file rather than any number in the message.',image:'/images/blog-2026-08-20/outsourced-vendor-research-evidence-map.png'},
  {slug:'recruiting-assistant-interview-accommodation-route',title:'Route interview accommodation requests with care',excerpt:'A narrow recruiting routine can preserve the candidate’s request while limiting disclosure and decision-making.',lane:'recruiting operations',artifact:'accommodation request route',inputs:'candidate request in their words, interview stage, timing, approved HR contact, disclosure limit, and status',boundary:'The assistant may acknowledge and route the request privately; HR or another authorised owner determines the response and any legal obligations.',example:'A candidate shares medical detail that is not needed for scheduling. The assistant records only the requested adjustment and restricts access.',image:'/images/blog-2026-08-20/assistant-training-sample-review.png'},
  {slug:'property-assistant-key-access-log',title:'Keep a key-access log for delegated property support',excerpt:'A practical key log connects each access event to a purpose, approver, holder, and confirmed return.',lane:'property operations',artifact:'key-access log',inputs:'property, key or credential ID, purpose, recipient, approver, issue time, expected return, and closure',boundary:'The assistant may maintain the log and chase confirmations; the property owner controls authorisation, emergency entry, and access exceptions.',example:'A contractor asks to keep a key overnight. The assistant pauses the request and routes it to the property owner.',image:'/images/blog-2026-08-20/remote-project-dependency-register.png'},
  {slug:'content-assistant-source-claim-map',title:'Map each article claim to its source before drafting',excerpt:'A claim map keeps sourced facts, editorial interpretation, and unsupported assumptions visibly separate.',lane:'content operations',artifact:'source-claim map',inputs:'claim text, source URL, publisher, publication date, relevant scope, supporting passage, and limitation',boundary:'The assistant may collect and summarise evidence; the editor decides whether the claim is supported and suitable for publication.',example:'A global survey is used to discuss a small Philippine team. The assistant records the population mismatch instead of implying a local result.',image:'/images/blog-2026-08-20/outsourced-article-outline-approval.png'},
  {slug:'executive-assistant-confidential-deck-distribution',title:'Control confidential deck distribution with an assistant',excerpt:'A recipient check and version log reduce accidental disclosure without making the assistant the confidentiality owner.',lane:'executive support',artifact:'deck distribution record',inputs:'approved version, recipient list, email domains, access setting, expiry, sender, and approval evidence',boundary:'The assistant may prepare the distribution and verify recipients; the executive or legal owner approves disclosure and confidentiality exceptions.',example:'A forwarded thread adds an external adviser. The assistant stops and obtains explicit approval before granting access.',image:'/images/blog-2026-08-20/shared-drive-filing-conventions-assistant.png'},
  {slug:'support-assistant-refund-deadline-watch',title:'Use a refund-deadline watch without delegating the refund decision',excerpt:'A deadline watch surfaces expiring cases while leaving eligibility and money movement with authorised staff.',lane:'customer support',artifact:'refund-deadline watch',inputs:'case ID, purchase date, policy version, request date, stated facts, deadline, evidence gaps, and decision owner',boundary:'The assistant may calculate dates from the approved policy and request missing evidence; authorised staff determine eligibility and issue funds.',example:'A request arrives near the deadline with a disputed delivery date. The assistant flags both dates and routes the ambiguity.',image:'/images/blog-2026-08-20/filipino-assistant-service-recovery-routing.png'}
];

const makePost=(x:Spec):BlogPost=>({slug:x.slug,title:x.title,excerpt:x.excerpt,minutes:8,published:'2026-09-07',image:{url:x.image,alt:`Illustration for ${x.title}`},takeaway:`Use a ${x.artifact} so ${x.lane} remains reviewable while consequential decisions stay with a named owner.`,sections:[
 {heading:`Define the ${x.artifact}`,paragraphs:[`${x.excerpt} Name the queue, its finish line, and the person who owns exceptions before work begins.`, `For an OutsourcingAssistant.com team working across Philippine and owner time zones, record the next review window so waiting is intentional rather than invisible.`]},
 {heading:'Capture only the evidence the task needs',paragraphs:[`Record ${x.inputs}. Link the authoritative record and mark missing or conflicting details instead of filling gaps from memory.`,`Use the least sensitive information that supports the next safe action. The convenience of a shared tracker does not justify copying unrelated personal, financial, or customer data.`]},
 {heading:'Turn the authority limit into a stop rule',paragraphs:[x.boundary,`Write the permitted verbs beside the queue: check, prepare, pause, and route. Access to a tool never creates approval, and silence is not consent.`]},
 {heading:'Rehearse an awkward case',paragraphs:[x.example,`The record should preserve what was observed, the last safe action, the open question, and the next owner. This makes exceptions teachable without pretending one example is a universal rule.`]},
 {heading:'Make the handoff reconstructable',paragraphs:[`At shift end, state what changed, what remains uncertain, where the evidence lives, and who acts next. A status without an owner and review time is incomplete.`,`Urgency may shorten the review window or change the escalation route. It does not widen the assistant’s authority.`]},
 {heading:'Sample and improve the routine',paragraphs:[`Each week, review routine items and every consequential exception for source fidelity, privacy, correct routing, and closure. Measure speed only after those controls pass.`,`When a question repeats, update the ${x.artifact} with an approved example and effective date. Preserve the earlier rule so previous actions remain understandable.`]}
],faqs:[{q:`What can the assistant own in ${x.lane}?`,a:`Repeatable evidence capture, permitted preparation, status updates, and routing inside the written ${x.artifact}.`},{q:'What remains with the owner?',a:'Commitments, sensitive judgments, access changes, money movement, policy decisions, and exceptions outside the approved lane.'},{q:'How should the routine be reviewed?',a:'Sample ordinary work against its source record and review every consequential exception.'}],citations:[{name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework',note:'Governance and risk-management context.'},{name:'U.S. Small Business Administration hiring guidance',url:'https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees',note:'General small-business management context.'}],internalLinks:[{href:'/resources/assistant-sop-handoff-checklist',label:'Use the assistant SOP handoff checklist'},{href:'/services',label:'Review outsourcing support services'}],cta:{href:'/contact',label:'Discuss a bounded assistant workflow'}});

export const dailyBlogBatch20260907: BlogPost[] = specs.map(makePost);
