import type { BlogPost } from './data';

type RecordSpec = {
  slug: string;
  title: string;
  audience: string;
  problem: string;
  workflow: string;
  evidence: string;
  boundary: string;
  published: '2026-08-17';
};

const records: RecordSpec[] = [
  { slug: 'philippines-virtual-assistant-inbox-escalation-map', title: 'Build an inbox escalation map for a Philippines-based virtual assistant', audience: 'a founder whose customer and vendor messages arrive in one crowded inbox', problem: 'deciding which messages can wait and which need an owner today', workflow: 'label the sender, consequence, promised response, and next owner before drafting', evidence: 'an escalation note includes the original thread, reason, and due window', boundary: 'payment changes, legal threats, account recovery, and final commitments', published: '2026-08-17' },
  { slug: 'philippines-virtual-assistant-crm-status-hygiene', title: 'Keep CRM status fields reliable with a Philippines-based assistant', audience: 'a small sales team whose pipeline reports no longer match the conversations', problem: 'separating a real next step from an optimistic or stale status', workflow: 'compare the latest approved interaction with the allowed status definitions', evidence: 'every changed record has a dated source note and a named next action', boundary: 'inventing qualification, changing forecast judgment, or promising fit', published: '2026-08-17' },
  { slug: 'philippines-virtual-assistant-support-macro-review', title: 'Review support macros with a Philippines-based assistant', audience: 'a support lead maintaining saved replies for recurring customer questions', problem: 'finding answers that have drifted from the current approved policy', workflow: 'sample real tickets, compare each macro with its source, and mark uncertain language', evidence: 'a macro is linked to an owner, review date, and example ticket', boundary: 'creating policy, granting exceptions, or giving regulated advice', published: '2026-08-17' },
  { slug: 'philippines-virtual-assistant-recruiting-brief-intake', title: 'Turn a hiring request into a usable brief with a Philippines-based assistant', audience: 'an operator who receives hiring requests in scattered messages and documents', problem: 'capturing the work, schedule, tools, and decision rights before search begins', workflow: 'normalize the request into tasks, required experience, examples, and open questions', evidence: 'the brief distinguishes must-have work from preferences and unknowns', boundary: 'making employment decisions, inventing credentials, or promising availability', published: '2026-08-17' },
  { slug: 'philippines-virtual-assistant-candidate-interview-notes', title: 'Organize candidate interview notes with a Philippines-based assistant', audience: 'a founder comparing several candidates for a remote assistant lane', problem: 'keeping evidence separate from impressions during a hiring decision', workflow: 'transcribe approved notes into the same question-and-evidence format for each candidate', evidence: 'each comparison points to a recorded answer rather than a vague score', boundary: 'ranking protected characteristics, making the hire, or fabricating references', published: '2026-08-17' },
  { slug: 'philippines-virtual-assistant-sop-version-control', title: 'Give a Philippines-based assistant a usable SOP version-control routine', audience: 'a distributed team whose operating instructions change as exceptions are resolved', problem: 'ensuring the active checklist is the one people actually use', workflow: 'compare proposed edits with the approved source, record the change, and flag conflicts', evidence: 'the live SOP shows owner, revision date, and reason for the change', boundary: 'approving policy, deleting history, or silently changing a control', published: '2026-08-17' },
  { slug: 'philippines-virtual-assistant-weekly-operations-report', title: 'Design a weekly operations report for a Philippines-based assistant', audience: 'an owner who needs visibility into recurring back-office work without more meetings', problem: 'reporting completed work and blockers without disguising missing data', workflow: 'count finished items, corrections, exceptions, and waiting decisions from source queues', evidence: 'each number links to a queue or record and unknowns remain visible', boundary: 'editing results, setting company targets, or interpreting financial performance', published: '2026-08-17' },
  { slug: 'philippines-virtual-assistant-vendor-onboarding-checklist', title: 'Run a vendor onboarding checklist with a Philippines-based assistant', audience: 'an operations team adding suppliers while trying to keep records consistent', problem: 'checking that required documents and contacts are present before a vendor is active', workflow: 'collect approved fields, match them to source documents, and route gaps to the owner', evidence: 'the checklist shows received, verified, and waiting states separately', boundary: 'approving suppliers, changing bank details, or accepting contractual terms', published: '2026-08-17' },
  { slug: 'philippines-virtual-assistant-ecommerce-catalog-audit', title: 'Audit an ecommerce catalog with a Philippines-based assistant', audience: 'an online store with product records maintained across a spreadsheet and storefront', problem: 'finding mismatched titles, attributes, images, and availability without inventing facts', workflow: 'compare each field with the approved product source and log the exact discrepancy', evidence: 'a reviewer can trace every proposed edit to a source record', boundary: 'creating product claims, changing safety information, or publishing unapproved edits', published: '2026-08-17' },
  { slug: 'philippines-virtual-assistant-order-exception-queue', title: 'Create an order-exception queue for a Philippines-based support assistant', audience: 'a commerce team handling late, damaged, or incomplete orders', problem: 'giving unusual orders enough context without letting routine support guess a remedy', workflow: 'capture order facts, customer request, carrier evidence, and the policy path for review', evidence: 'each case names the missing decision and its authorized owner', boundary: 'promising refunds, changing delivery instructions, or contacting a carrier outside policy', published: '2026-08-17' },
  { slug: 'philippines-virtual-assistant-real-estate-lead-intake', title: 'Structure real-estate lead intake for a Philippines-based assistant', audience: 'a real-estate operator receiving inquiries through portals, email, and phone notes', problem: 'recording useful preferences without turning an assistant into an advisor', workflow: 'capture the prospect’s stated criteria, source, timing, and requested follow-up', evidence: 'unknown budget, availability, and property details stay marked unknown', boundary: 'offering property advice, screening protected traits, or negotiating terms', published: '2026-08-17' },
  { slug: 'philippines-virtual-assistant-agency-client-reporting', title: 'Prepare agency client reporting with a Philippines-based assistant', audience: 'an agency owner assembling recurring status updates from several delivery tools', problem: 'turning scattered activity into a factual client-ready draft', workflow: 'collect approved metrics, link deliverables, and list decisions still needed', evidence: 'the draft separates activity, outcome, explanation, and next action', boundary: 'inflating performance, changing attribution, or making a client promise', published: '2026-08-17' },
  { slug: 'philippines-virtual-assistant-coach-session-followup', title: 'Handle coach session follow-up with a Philippines-based assistant', audience: 'a coach who needs consistent administrative follow-up after scheduled sessions', problem: 'keeping reminders and resources orderly without crossing into coaching', workflow: 'match the approved session record to the next administrative message and due date', evidence: 'the follow-up identifies the source session and uses only approved resources', boundary: 'giving advice, interpreting a client’s situation, or changing a care plan', published: '2026-08-17' },
  { slug: 'philippines-virtual-assistant-home-service-job-board', title: 'Maintain a home-service job board with a Philippines-based assistant', audience: 'a home-service operator coordinating inquiries, visits, and technician notes', problem: 'showing which jobs are ready, waiting, or blocked before the next dispatch decision', workflow: 'reconcile customer details, address, requested work, appointment state, and technician update', evidence: 'each job has a current source and an explicit next owner', boundary: 'diagnosing work, quoting unapproved terms, or guaranteeing arrival', published: '2026-08-17' },
  { slug: 'philippines-virtual-assistant-healthcare-office-intake-admin', title: 'Set safe administrative intake boundaries for a Philippines-based assistant', audience: 'a healthcare office separating clerical intake from professional decisions', problem: 'collecting complete administrative details while protecting sensitive information', workflow: 'use the office-approved fields, confirm the preferred contact path, and flag missing consent', evidence: 'the record shows what was provided without adding an interpretation', boundary: 'triage, diagnosis, treatment guidance, or disclosure decisions', published: '2026-08-17' },
  { slug: 'philippines-virtual-assistant-legal-intake-packet', title: 'Prepare a legal intake packet with a Philippines-based assistant', audience: 'a legal team organizing prospective-client information before attorney review', problem: 'making an intake packet complete without implying a legal conclusion', workflow: 'sort the submitted facts, dates, documents, and questions into the firm’s approved fields', evidence: 'missing facts and unverified statements remain clearly labeled', boundary: 'legal advice, conflict decisions, eligibility judgments, or promises', published: '2026-08-17' },
  { slug: 'philippines-virtual-assistant-finance-document-index', title: 'Build a finance document index with a Philippines-based assistant', audience: 'a small business gathering receipts and statements for authorized review', problem: 'making source documents findable without turning indexing into accounting judgment', workflow: 'name, date, source, period, and document type each item using the approved convention', evidence: 'every index row opens the original file and exposes missing periods', boundary: 'categorizing uncertain transactions, approving payments, or giving tax advice', published: '2026-08-17' },
  { slug: 'philippines-virtual-assistant-access-review-calendar', title: 'Run an access-review calendar with a Philippines-based assistant', audience: 'a growing team that needs regular checks on remote-worker permissions', problem: 'making stale access visible before a role or project changes', workflow: 'list the user, system, permission, business purpose, reviewer, and review date', evidence: 'the reviewer records keep, narrow, remove, or investigate for each entry', boundary: 'granting exceptions, handling secrets, or deciding security policy', published: '2026-08-17' },
  { slug: 'philippines-virtual-assistant-customer-renewal-prep', title: 'Prepare customer renewal work with a Philippines-based assistant', audience: 'a service owner tracking upcoming agreement decisions across accounts', problem: 'starting renewal conversations from the correct record and date', workflow: 'match the current agreement, notice window, contact, and open service items', evidence: 'each draft cites the governing record and flags conflicting dates', boundary: 'changing terms, negotiating, or representing a renewal as agreed', published: '2026-08-17' },
  { slug: 'philippines-virtual-assistant-local-seo-listing-audit', title: 'Audit local-search listings with a Philippines-based assistant', audience: 'a local operator whose business details appear in several public directories', problem: 'finding inconsistent public facts without publishing an unapproved correction', workflow: 'compare name, contact details, hours, and service description against one approved source', evidence: 'each discrepancy records the directory, observed text, and recommended owner action', boundary: 'inventing local claims, responding to reviews as the owner, or changing legal details', published: '2026-08-17' },
  { slug: 'philippines-virtual-assistant-content-brief-research', title: 'Prepare a niche content brief with a Philippines-based assistant', audience: 'a site owner who wants useful articles grounded in real customer questions', problem: 'turning a topic idea into a brief with a clear audience, evidence, and editorial limit', workflow: 'define the question, inspect approved source material, list claims to verify, and map the reader decision', evidence: 'the brief separates sourced facts, examples, and questions requiring owner review', boundary: 'publishing unsupported claims, copying another article, or making professional promises', published: '2026-08-17' },
  { slug: 'philippines-virtual-assistant-remote-team-handoff', title: 'Make a remote-team handoff readable across Philippines time', audience: 'an owner and Philippines-based assistant working in different review windows', problem: 'preventing unfinished work from disappearing between shifts', workflow: 'record completed items, drafts, blockers, decisions needed, and the next review window', evidence: 'a new reader can resume from the note without searching private messages', boundary: 'declaring blocked work complete, changing priorities, or bypassing the owner', published: '2026-08-17' }
];

function makePost(record: RecordSpec): BlogPost {
  return {
    slug: record.slug,
    title: record.title,
    published: record.published,
    minutes: 9,
    excerpt: `A practical guide for ${record.audience}, focused on ${record.problem} with a clear handoff for Philippines-based support.`,
    takeaway: `Define the decision boundary before delegating: ${record.workflow}. Keep ${record.boundary} with the named owner.`,
    sections: [
      { heading: 'Name the real operating problem', body: `For ${record.audience}, the hard part is ${record.problem}. Start by writing what a useful finished record looks like and who reviews it. A narrow outcome lets a Philippines-based assistant prepare repeatable work without guessing at the business decision.` },
      { heading: 'Give the assistant a workable input', body: `The first pass should ${record.workflow}. Put the source of truth, required fields, examples, and due window in the brief. If a field is unavailable, the assistant should mark it missing rather than fill it from an assumption.` },
      { heading: 'Check evidence before expanding the lane', body: `Use a small reviewed sample before making this routine larger. The practical signal is ${record.evidence}. Keep corrections beside the example that caused the confusion so the next handoff improves for a reason the team can see.` },
      { heading: 'Keep the owner decision visible', body: `Stop when work reaches ${record.boundary}. Preserve the original context, state the question that needs a decision, and route it to the approved owner. Escalation is part of a dependable outsourcing arrangement, not a failure to finish.` },
      { heading: 'Make the cross-time-zone handoff readable', body: `End each cycle with completed items, waiting items, exceptions, and the next action. Name the owner-review window in the Philippines-based workflow so neither person has to infer whether a quiet queue is complete or simply unattended.` },
      { heading: 'Improve from corrections, not anecdotes', body: `After several cycles, group repeated corrections by missing field, unclear example, access problem, or decision boundary. Change one part of the brief at a time and review another small sample. This keeps the service useful while preserving the owner’s control over exceptions.` }
    ],
    faqs: [
      { q: `What should the assistant do when ${record.problem} is ambiguous?`, a: 'Pause the item, preserve the source context, describe the missing decision, and send it to the named reviewer. Do not turn an incomplete request into a confident action.' },
      { q: 'How much should the owner review at first?', a: 'Review a small first batch closely, including exceptions. Move to sampling only after the assistant is consistently using the source, finish line, and escalation rule.' },
      { q: 'What belongs in the handoff note?', a: 'Include the input source, completed result, unresolved question, evidence link, approval boundary, and next owner or review window.' }
    ],
    internalLinks: [{ href: '/resources/assistant-sop-handoff-checklist', label: 'Assistant SOP handoff checklist' }, { href: '/services', label: 'Philippines assistant staffing services' }]
  };
}

export const dailyBlogBatch20260817: BlogPost[] = records.map(makePost);
