import type { BlogPost } from './data';

type Spec = {
  slug: string; title: string; audience: string; focus: string; result: string;
  first: string; boundary: string; object: string; failure: string; lens: string;
};

const specs: Spec[] = [
  ['outsourced-assistant-weekly-capacity-map','Build a weekly capacity map for an outsourced assistant','an owner whose assistant receives requests from several parts of the business','weekly capacity mapping','a visible plan that distinguishes committed work, flexible work, and work that cannot fit','list recurring duties beside their trigger and expected effort','promising an extra deadline without an owner decision','the Monday planning note','a request arrives after the week is already full','capacity is a planning constraint, not a test of loyalty'],
  ['filipino-virtual-assistant-escalation-ladder','Design an escalation ladder for a Filipino virtual assistant','a distributed team that needs questions to reach the right person','escalation ladders','questions arriving with enough context for a fast and safe decision','name the question types, first reviewer, backup reviewer, and stop condition','making a consequential decision because a reviewer is quiet','the escalation card','a customer, payment, or policy question leaves the normal lane','good escalation reduces uncertainty without transferring authority'],
  ['outsourced-assistant-knowledge-base-review','Review a knowledge base before an assistant relies on it','a support lead whose instructions have accumulated across documents and chat','knowledge-base review','a short set of current instructions with owners and review dates','sample the questions the assistant actually receives and trace each answer','inventing an answer when the source is missing or contradictory','the source register','two documents appear to give different answers','an assistant can only be consistent when the source is legible'],
  ['remote-assistant-shift-handoff','Write a shift handoff that survives a time-zone gap','a founder who needs work to continue while they are offline','shift handoffs','a next-day queue that another person can continue without reconstructing context','separate finished work, waiting work, blocked work, and observed risk','treating silence or an unread note as approval','the end-of-shift brief','a deadline approaches while the owner is unavailable','a handoff is an operating record, not a status performance'],
  ['outsourced-assistant-approval-queue','Create an approval queue for customer-facing drafts','a service team that wants assistance with replies while retaining final judgment','approval queues','draft replies grouped by urgency, evidence, and decision needed','capture the original question and proposed response beside the source','sending a promise, refund, or exception without approval','the response queue','a draft needs policy interpretation or a new commitment','review is strongest when the question is visible before the draft'],
  ['filipino-assistant-data-cleanup-scope','Scope data cleanup so a Filipino assistant does not erase history','an operations owner with duplicate, stale, or inconsistent records','data cleanup','a proposed correction list that preserves history and makes uncertainty obvious','define stable identifiers, allowed edits, and a reversible review sample','deleting records or merging uncertain identities','the correction log','two records look similar but cannot be proven to match','clean data is more than fewer rows'],
  ['outsourced-assistant-research-brief','Give an outsourced assistant a research brief with an evidence boundary','a founder who needs prepared research without unsupported conclusions','research briefs','a decision-ready evidence packet with source limits and open questions','state the decision, acceptable sources, date range, and required citation note','presenting interpretation as fact or advice','the evidence table','a source is plausible but does not establish the requested claim','research support should clarify the decision, not impersonate it'],
  ['outsourced-assistant-meeting-prep-packet','Prepare a meeting packet without turning notes into commitments','an executive who wants meetings to start with shared context','meeting packets','a compact packet containing purpose, facts, questions, and pending choices','collect approved facts and label proposals separately','speaking for the owner or recording an unapproved decision','the pre-read','participants disagree about the desired outcome','preparation earns trust by showing what is known and unknown'],
  ['outsourced-assistant-vendor-follow-up','Run vendor follow-up with a clear promise boundary','an operations team coordinating suppliers and external partners','vendor follow-up','a dated trail of requests, replies, dependencies, and owner decisions','use the approved contact path and record the exact request','negotiating terms or changing payment instructions','the vendor tracker','a supplier asks for a new term or urgent payment change','persistence is useful only when the request remains accurate'],
  ['outsourced-assistant-quality-sample-plan','Choose quality samples for a newly delegated routine','a manager who needs to inspect work without reviewing every item forever','quality sampling','a sample plan that catches ordinary mistakes and meaningful exceptions','define the population, sample reason, review fields, and correction action','declaring quality from a tiny or cherry-picked sample','the review sheet','the routine changes while the sample still uses an old rule','sampling is a decision aid, not a guarantee'],
  ['filipino-virtual-assistant-calendar-timezone-rules','Set calendar and time-zone rules for a Filipino virtual assistant','a cross-border team coordinating meetings with customers and owners','calendar time-zone rules','appointments that preserve the intended local time and preparation window','write the canonical time zone, daylight-saving rule, and confirmation format','moving a high-stakes meeting without owner approval','the booking record','a participant gives a time without naming a zone','time is part of the task scope, not a formatting detail'],
  ['outsourced-assistant-role-reset','Reset an outsourced assistant role when the task list has drifted','an owner whose assistant has gradually inherited unrelated requests','role reset','a current role brief that restores priorities, limits, and review rhythm','compare actual requests with the original outcome and sort them by authority','quietly accepting new responsibilities with no access or training review','the role inventory','a recurring favor has become an assumed responsibility','clarity protects both the owner and the assistant']
].map(([slug,title,audience,focus,result,first,boundary,object,failure,lens])=>({slug,title,audience,focus,result,first,boundary,object,failure,lens}));

const headings = ['Name the decision','Describe the starting material','Set the safe first move','Make evidence visible','Separate routine from exception','Design the review moment','Write the cross-time-zone handoff','Check the permission boundary','Learn from correction','Close with the owner action'];

function paragraph(s: Spec, i: number): string {
  const starts = [
    `For ${s.focus}, begin with the decision the owner needs to make rather than with a broad request to “help.” ${s.audience} needs ${s.result}. Write that outcome in one sentence, then list what will count as ready for review. The description should be concrete enough that an assistant can prepare the work and a second person can inspect it without guessing. ${s.lens} matters because a queue can look busy while still hiding the actual choice.`,
    `The starting material for ${s.focus} is ${s.object}. Record where it came from, when it was last checked, and which parts are missing. Then apply the first move: ${s.first}. A brief that names the input prevents the assistant from searching every connected tool or treating an old message as current authority. It also gives the owner a fair way to distinguish incomplete input from incomplete work.`,
    `The first safe move should be small enough to reverse. In this case, it means ${s.first}. Give the assistant one ordinary example and one example that must stop. The point is not to script every sentence; it is to show the boundary between preparation and decision. A Philippines-based assistant can work independently inside a defined lane when the lane includes its trigger, source, expected record, and next reviewer.`,
    `Make the evidence visible beside the work. For ${s.focus}, preserve the request, relevant source, action taken, unresolved question, and current state. Do not make the reviewer infer why an item was changed. If a fact is unavailable, label it unavailable. If a statement is an interpretation, label it as a proposed reading. This protects customer-facing copy, internal reporting, and future handoffs from a confident sentence that has no traceable basis.`,
    `Routine work ends when it reaches the agreed result; the exception begins when the request changes its consequence. The important exception here is ${s.failure}. When it appears, pause the consequential step, retain the surrounding context, and ask the named owner a narrow question. The assistant may suggest safe preparation, but it should not convert urgency, repetition, or a missing reply into authority.`,
    `Review should happen at the point where a mistake would become expensive or public. Inspect a representative sample for completeness, source handling, status accuracy, and boundary judgment. For ${s.focus}, ask whether another reviewer could tell what happened and what decision remains. Correct the record itself when necessary, then correct the brief if the same ambiguity could return. A review is useful when it improves the next item, not when it merely assigns blame.`,
    `A time-zone gap makes the handoff part of the work. End the shift with completed items, items waiting on evidence, blocked items, and one explicit next owner. Mention the relevant date, local time, and source record when timing matters. Avoid “please review” as a standalone instruction; state the choice needed. The next person should be able to continue ${s.focus} without opening scattered chats or assuming that silence means approval.`,
    `Tools should follow the role rather than define it. Map each action as view, draft, edit, send, approve, or delete. Grant only what is needed for the current lane, use individual accounts where possible, and retain owner control over irreversible changes. The boundary here is ${s.boundary}. If the role expands, review the new access, training, and approval path together instead of adding a permission as a quick fix.`,
    `After several cycles, review the correction pattern. Was the source unclear, the example incomplete, the status vocabulary inconsistent, or the owner unavailable? Store the answer in ${s.object} or the role brief, and note who approved the change. This is especially important for outsourced support: the assistant should not be judged against a private rule that was never written, while the owner should not have to repeat the same correction forever.`,
    `The owner action is to test one real but bounded item, inspect the evidence, confirm the stop condition, and decide whether the lane is ready for more volume. Do not treat this method as a guarantee or as legal, tax, financial, employment, medical, or security advice. For ${s.focus}, the durable outcome is a clearer handoff: useful preparation from the assistant, visible uncertainty, and consequential judgment retained by the authorized owner.`
  ];
  return starts[i];
}

function makePost(s: Spec, index: number): BlogPost {
  return { slug: s.slug, title: s.title, published: '2026-08-21', minutes: 11,
    excerpt: `A practical OutsourcingAssistant.com guide for ${s.audience}: make ${s.focus} reviewable, useful, and bounded.`,
    takeaway: `${s.result}. Start with ${s.first}, and keep ${s.boundary} with the owner.`,
    image: { url: `/images/blog-2026-08-21/${s.slug}.png`, alt: s.title },
    sections: headings.map((heading, i) => ({ heading, body: paragraph(s, (i + index) % 10) })),
    faqs: [
      { q: `What should the owner define before delegating ${s.focus}?`, a: `Define the input, finished result, source of truth, review point, and the action that remains with the owner: ${s.boundary}.` },
      { q: 'What should happen when the normal path breaks?', a: `Pause the consequential step, keep the relevant evidence, and route a concise question to the named reviewer. Do not guess because the request is urgent.` },
      { q: 'How can a distributed team improve the routine?', a: 'Review a small representative sample, record corrections, and update the brief or example when the same ambiguity returns.' }
    ],
    internalLinks: [{ href: '/resources/assistant-sop-handoff-checklist', label: 'Use the assistant SOP handoff checklist' }, { href: '/services', label: 'Review staffing and support services' }]
  };
}

export const dailyBlogBatch20260821: BlogPost[] = specs.map(makePost);
