import type { BlogPost } from './data';

type Spec = { slug: string; title: string; risk: string; evidence: string; action: string; boundary: string; example: string };
const specs: Spec[] = [
  { slug: 'virtual-assistant-inbox-sender-verification-routine', title: 'Create an inbox sender-verification routine for a virtual assistant', risk: 'A familiar display name can hide a changed address or an impersonated executive.', evidence: 'full sender address, prior thread, known contact record, links, attachments, and requested action', action: 'compare the message with the known record, preserve the original, and prepare an independent verification note', boundary: 'Do not share data or change an account until the owner verifies the request through a channel already on file.', example: 'A message uses the founder’s name but a new domain and asks for a customer export. The assistant records the mismatch and contacts the founder in the approved workspace.' },
  { slug: 'assistant-customer-record-correction-queue', title: 'Run a customer-record correction queue with an approval trail', risk: 'A plausible correction can overwrite accurate history or weaken a consent record.', evidence: 'original request, customer identifier, current fields, source system, history, and data owner', action: 'show the old and proposed values, check the authoritative source, and queue the correction for review', boundary: 'Do not alter identity, consent, financial, or dispute fields when evidence conflicts; the data owner resolves the conflict.', example: 'A customer requests a new email while writing from neither the old nor proposed address. The assistant pauses and routes a verification question.' },
  { slug: 'executive-assistant-travel-option-expiry-log', title: 'Use a travel-option expiry log for executive assistant research', risk: 'A travel recommendation can appear current after a fare, hold, visa rule, or cancellation term changes.', evidence: 'route, traveler constraints, source URL, price, currency, conditions, checked time, and expiry time', action: 'record comparable options, timestamp every check, highlight restrictions, and mark stale options clearly', boundary: 'Do not book, accept nonrefundable terms, or interpret immigration requirements without explicit traveler approval and appropriate advice.', example: 'A lower fare expires before review. The assistant marks it unavailable and refreshes the comparison instead of presenting the old price as bookable.' },
  { slug: 'outsourced-invoice-duplicate-screening-workflow', title: 'Screen possible duplicate invoices before payment review', risk: 'Formatting changes and partial shipments can make the same obligation look like a new invoice.', evidence: 'vendor, invoice number, purchase order, amount, currency, date, line items, and payment history', action: 'normalize identifiers, compare likely matches, attach records, and classify each candidate as distinct, duplicate, or unresolved', boundary: 'Never delete an invoice, approve payment, or change banking details; accounts payable makes the disposition.', example: 'Two invoices have different prefixes but the same purchase order, amount, and lines. The assistant flags the pair and preserves both for finance.' },
  { slug: 'virtual-assistant-contract-renewal-reminder-register', title: 'Build a contract renewal reminder register without granting authority', risk: 'A missed notice date can trigger an unwanted renewal, while a reminder can be mistaken for authority to negotiate.', evidence: 'signed agreement, counterparty, renewal date, notice deadline, notice method, owner, and page reference', action: 'extract dates with citations, schedule staged reminders, and prepare a decision packet before the notice window', boundary: 'Do not interpret ambiguous clauses, send termination notices, or agree to terms; legal or the contract owner decides and sends.', example: 'An agreement lists a renewal date and a separate ninety-day notice rule. The assistant records both with page citations and requests owner confirmation.' },
  { slug: 'assistant-support-macro-change-review', title: 'Review customer-support macro changes before assistants use them', risk: 'A small template edit can introduce an outdated policy or promise across many customer replies.', evidence: 'current macro, proposed wording, reason, policy source, affected queue, owner, and effective date', action: 'show a line-by-line difference, connect claims to policy, test placeholders, and submit the revision for approval', boundary: 'Do not publish wording that changes refund rights, legal terms, security instructions, or customer commitments.', example: 'A draft says every delayed order earns a refund, but policy has a threshold. The assistant returns it to the support owner with the source.' },
  { slug: 'remote-assistant-file-retention-review-list', title: 'Prepare a file-retention review list for remote assistant work', risk: 'Routine cleanup can destroy records that still have business, legal, security, or customer value.', evidence: 'file path, owner, category, creation date, last use, approved schedule, access group, and hold status', action: 'inventory candidates, group them by the approved schedule, and prepare retain, archive, or deletion recommendations', boundary: 'Do not delete records, release a hold, or invent a retention period; the record owner authorizes final action.', example: 'An inactive folder contains documents under an open dispute hold. The assistant removes it from cleanup candidates and alerts the owner.' },
  { slug: 'virtual-assistant-web-form-routing-audit', title: 'Audit web-form routing rules with a virtual assistant', risk: 'A working form can still send urgent, private, or valuable submissions to the wrong queue.', evidence: 'form fields, routing rules, destination inboxes, notification owners, test records, and expected response windows', action: 'submit approved test cases, trace destinations, compare results with the routing map, and record gaps without real customer data', boundary: 'Do not change production routing or treat email delivery as proof that the correct owner reviewed the submission.', example: 'A partnership inquiry reaches general support instead of business development. The assistant documents the path for the site owner.' },
  { slug: 'assistant-sales-call-follow-up-fact-check', title: 'Fact-check assistant-prepared sales call follow-up', risk: 'A concise follow-up can turn a discussion point into a product promise or agreed deadline.', evidence: 'approved notes, permitted recording, attendee list, pricing source, action owners, and open questions', action: 'separate confirmed facts, customer statements, proposals, and unresolved items before drafting follow-up', boundary: 'Do not confirm pricing, scope, terms, dates, or discounts unless the authorized owner approves the exact language.', example: 'A prospect asks if launch is possible in two weeks. The assistant records a question rather than claiming the company committed.' },
  { slug: 'outsourced-order-address-change-checklist', title: 'Use an order address-change checklist before fulfillment', risk: 'An address update can be a correction, a fraud attempt, or too late for the carrier.', evidence: 'order number, requester channel, old and proposed addresses, payment status, fulfillment state, and verification rule', action: 'verify the requester, preserve both addresses, check fulfillment status, and route a complete change packet', boundary: 'Do not override fraud controls, redirect an in-transit package, or promise successful delivery after a change.', example: 'The warehouse has printed the label. The assistant records the cutoff state and sends the case to fulfillment instead of silently editing it.' },
  { slug: 'executive-assistant-delegated-contact-export-control', title: 'Control contact exports delegated to an executive assistant', risk: 'A convenient export can expose personal data beyond its stated purpose and create unmanaged copies.', evidence: 'business purpose, requested fields, eligible contacts, destination, requester, retention date, and approver', action: 'define the minimum population and fields, preview counts, exclude restricted records, and prepare an export request', boundary: 'Do not export an entire address book, transfer it to a personal account, or reuse the file for another purpose.', example: 'An event planner asks for every executive contact. The assistant narrows the request to approved invitees and waits for the data owner.' },
  { slug: 'assistant-daily-article-correction-register', title: 'Keep a daily article correction register for outsourced publishing', risk: 'Small edits can erase the reason for a correction or leave conflicting facts across published pages.', evidence: 'article URL, reported issue, original wording, evidence, proposed wording, severity, editor, and correction time', action: 'capture the report, verify the claim, prepare a scoped edit, and link the correction to its evidence and reviewer', boundary: 'Do not conceal substantive changes, invent sources, or alter publication dates to make old material appear new.', example: 'A source updates a program name but not eligibility. The assistant changes only the name and records why the broader claim stays.' },
];

const citations = [
  { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework', note: 'Governance and review context.' },
  { name: 'CISA Secure Our World', url: 'https://www.cisa.gov/secure-our-world', note: 'Verification and account safeguards.' },
  { name: 'SBA hiring guidance', url: 'https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees', note: 'General management context.' },
];

const make = (s: Spec): BlogPost => ({
  slug: s.slug, title: s.title, published: '2026-09-01', minutes: 9,
  excerpt: `A practical OutsourcingAssistant.com procedure addressing this risk: ${s.risk}`,
  image: { url: '/assistant-collaboration.jpg', alt: `A team reviewing ${s.title.toLowerCase()}` },
  takeaway: `${s.action}. Keep consequential decisions with the named owner.`,
  sections: [
    { heading: 'Name the risk before delegation', body: `${s.risk} Define the desired result and the person who owns the final decision. A completed checklist does not create authority.` },
    { heading: 'Collect a traceable input packet', body: `Start with ${s.evidence}. Preserve the original request and mark missing or conflicting fields as unknown.` },
    { heading: 'Use an observable work sequence', body: `The assistant should ${s.action}. Use received, checking, waiting, ready for review, approved, and closed as separate states.` },
    { heading: 'Make the stop rule explicit', body: s.boundary },
    { heading: 'Test a realistic exception', body: `${s.example} Keep the example only after private details are removed and the owner confirms it matches current policy.` },
    { heading: 'Review evidence instead of confidence', body: 'Sample ordinary items and exceptions. Check source completeness, correction types, owner response time, and work returned after approval.' },
    { heading: 'Write a resumable handoff', body: 'State what changed, evidence checked, unresolved question, next permitted action, owner, and review window. Silence means waiting, not approval.' },
    { heading: 'Repair repeated process gaps', body: 'When the same question appears twice, update the SOP or example library. Expand access only after reviewed work shows the current lane is stable.' },
  ],
  faqs: [
    { q: 'Can the assistant complete this without owner review?', a: 'The assistant can complete preparation. Exceptions and consequential actions remain with the named owner unless written authority explicitly covers them.' },
    { q: 'What belongs in the handoff?', a: 'Include the request, evidence, state, open question, next permitted action, owner, and review window.' },
    { q: 'How often should the routine be checked?', a: 'Review early samples closely, then sample routine work and inspect every exception or authority change.' },
  ],
  citations,
  internalLinks: [{ href: '/resources/assistant-sop-handoff-checklist', label: 'Use the assistant SOP handoff checklist' }, { href: '/services', label: 'Review outsourcing support services' }],
  cta: { href: '/contact', label: 'Plan a controlled assistant workflow' },
});

export const dailyBlogBatch20260901: BlogPost[] = specs.map(make);
