import * as data from './data';
import { Header, Footer, JsonLd } from './components';
const d=data as any, site=d.site||{}, services=(d.services||[]).slice(0,6), posts=(d.blogPosts||[]).slice(0,4), stats=(d.stats||[]).slice(0,3), offer=d.staffingOffer||{};
const title=(x:any)=>typeof x==='string'?x:(x.title||x.name||x.label||x.question||'Ops lane');
const text=(x:any)=>typeof x==='string'?x:(x.desc||x.excerpt||x.note||x.body||'Repeatable work, clear SOPs, review rules, and weekly reporting.');
const slug=(x:any)=>(x.slug||title(x).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,''));
const heroBySlug:any={virtualassistantprovider:{headline:'Hire Managed Virtual Assistants',cta:'Hire Experienced VAs',tagline:'Your next best hire, without screening alone.',benefits:['Clear English communicators','Work in your business hours','Highly skilled and process driven','Take on more over time']},outsourcingassistant:{headline:'Hire Reliable Outsourcing Assistants',cta:'Hire Outsourcing Help',tagline:'Get work off your plate with managed support.',benefits:['Admin and daily operations','Customer support and follow up','Reporting, QA, and task tracking','More responsibility as trust grows']},websitedesignoutsource:{headline:'Hire Website Design Assistants',cta:'Hire Design Support',tagline:'Launch more pages without managing every edit.',benefits:['Landing pages and website updates','Design briefs and production handoff','Mobile, forms, and SEO checks','Steady revision and QA support']}};
const hero=heroBySlug[site.slug]||{headline:`Hire ${site.brand||'Managed Assistants'}`.split(' ').slice(0,8).join(' '),cta:'Start Hiring',tagline:'Your next best hire, without doing it alone.',benefits:['Clear English communicators','Work in your business hours','Highly skilled and process driven','Take on more over time']};

export default function Home(){const schema={'@context':'https://schema.org','@type':'WebSite',name:site.brand,url:`https://${site.domain}`};return <><Header/><main className="ops"><JsonLd data={schema}/>
<section className="hero stealth-hero"><div className="container stealth-hero-grid"><div className="stealth-copy"><h1>{hero.headline}</h1><ul className="hero-list">{hero.benefits.map((b:string,i:number)=><li key={i}><span aria-hidden="true">✓</span>{b}</li>)}</ul><a className="btn primary hero-cta" href="/contact">{hero.cta}</a><p className="cta-tagline">{hero.tagline}</p></div><figure className="hero-photo"><img src={site.heroImage||site.serviceImage||'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1200&q=80'} alt={site.alt||`${site.brand} assistant support`}/></figure></div></section>
<section className="container metric-row">{stats.map((s:any,i:number)=><article key={i}><span>{s.label}</span><b>{s.value}</b><p>{s.note}</p></article>)}</section>
<section className="container section" id="services"><div className="section-head"><p className="eyebrow">Support lanes</p><h2>Turn scattered work into owned queues.</h2><p>Each lane is built with SOPs, tool access, reporting, escalation, and a definition of done.</p></div><div className="lane-grid">{services.map((s:any,i:number)=><a href={`/services/${slug(s)}`} key={i}><span>lane {String(i+1).padStart(2,'0')}</span><h3>{title(s)}</h3><p>{text(s)}</p><b>Inspect lane →</b></a>)}</div></section>
<section className="ops-band"><div className="container band-grid"><div><p className="eyebrow">The managed layer</p><h2>Screening, backup, QA, and reporting sit above the assistant.</h2></div><div>{(offer.included||['role planning','candidate matching','SOP setup','managed support']).slice(0,4).map((x:string,i:number)=><article key={i}><b>{String(i+1).padStart(2,'0')}</b><p>{x}</p></article>)}</div></div></section>
<section className="container section resources"><div className="section-head"><p className="eyebrow">Runbooks</p><h2>Guides for better outsourcing decisions.</h2></div><div className="runbook-grid">{posts.map((p:any,i:number)=><a href={`/blog/${p.slug}`} key={i}><span>{p.minutes||7} min</span><strong>{title(p)}</strong><p>{text(p)}</p></a>)}</div></section>
<section className="container terminal-cta"><code>$ scope --tasks --tools --schedule --qa</code><h2>Build a cleaner staffing queue.</h2><a className="btn primary" href="/contact">Request staffing plan</a></section>
</main><Footer/></>}
