import * as data from './data';
import { Header, Footer, JsonLd } from './components';
const d=data as any, site=d.site||{}, services=(d.services||[]).slice(0,6), posts=(d.blogPosts||[]).slice(0,4), stats=(d.stats||[]).slice(0,3), offer=d.staffingOffer||{};
const title=(x:any)=>typeof x==='string'?x:(x.title||x.name||x.label||x.question||'Ops lane');
const text=(x:any)=>typeof x==='string'?x:(x.desc||x.excerpt||x.note||x.body||'Repeatable work, clear SOPs, review rules, and weekly reporting.');
const slug=(x:any)=>(x.slug||title(x).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,''));
export default function Home(){const schema={'@context':'https://schema.org','@type':'WebSite',name:site.brand,url:`https://${site.domain}`};return <><Header/><main className="ops"><JsonLd data={schema}/>
<section className="ops-hero"><div className="container ops-grid"><div><p className="eyebrow">Operations command center</p><h1>Outsource the repeat work without losing control of the system.</h1><p className="lead">A dark-mode staffing guide for owners who need steady offshore support, clear queues, clean SOPs, and a manager path when work slips.</p><div className="hero-actions"><a className="btn primary" href="/contact">Request staffing plan</a><a className="btn secondary" href="#services">Build the queue</a></div></div><div className="dashboard"><div className="dash-top"><span>handoff queue</span><b>manager online</b></div><div className="bars"><i/><i/><i/></div>{services.slice(0,4).map((s:any,i:number)=><article key={i}><span>{String(i+1).padStart(2,'0')}</span><div><b>{title(s)}</b><p>{text(s)}</p></div><em>{i===0?'Ready':i===1?'QA':'Scope'}</em></article>)}</div></div></section>
<section className="container metric-row">{stats.map((s:any,i:number)=><article key={i}><span>{s.label}</span><b>{s.value}</b><p>{s.note}</p></article>)}</section>
<section className="container section" id="services"><div className="section-head"><p className="eyebrow">Support lanes</p><h2>Turn scattered work into owned queues.</h2><p>Each lane is built with SOPs, tool access, reporting, escalation, and a definition of done.</p></div><div className="lane-grid">{services.map((s:any,i:number)=><a href={`/services/${slug(s)}`} key={i}><span>lane {String(i+1).padStart(2,'0')}</span><h3>{title(s)}</h3><p>{text(s)}</p><b>Inspect lane →</b></a>)}</div></section>
<section className="ops-band"><div className="container band-grid"><div><p className="eyebrow">The managed layer</p><h2>Screening, backup, QA, and reporting sit above the assistant.</h2></div><div>{(offer.included||['role planning','candidate matching','SOP setup','managed support']).slice(0,4).map((x:string,i:number)=><article key={i}><b>{String(i+1).padStart(2,'0')}</b><p>{x}</p></article>)}</div></div></section>
<section className="container section resources"><div className="section-head"><p className="eyebrow">Runbooks</p><h2>Guides for better outsourcing decisions.</h2></div><div className="runbook-grid">{posts.map((p:any,i:number)=><a href={`/blog/${p.slug}`} key={i}><span>{p.minutes||7} min</span><strong>{title(p)}</strong><p>{text(p)}</p></a>)}</div></section>
<section className="container terminal-cta"><code>$ scope --tasks --tools --schedule --qa</code><h2>Build a cleaner staffing queue.</h2><a className="btn primary" href="/contact">Request staffing plan</a></section>
</main><Footer/></>}
