import type { ResearchPost, ResearchSource } from './fleet-content';
import { buildDecisionResearch, type ResearchDecisionSpec } from './research-batch-2026-09-22-run2';

const checked = 'Checked September 23, 2026.';
const sources: readonly ResearchSource[] = [
  { name: 'Google Workspace Learning Center, Manage someone’s calendar', url: 'https://support.google.com/a/users/answer/170963?hl=en', note: `First-party product guidance on delegated calendar access and responding from the correct calendar. ${checked}` },
  { name: 'Microsoft Learn, Give mailbox permissions to another user', url: 'https://learn.microsoft.com/en-us/microsoft-365/admin/add-users/give-mailbox-permissions-to-another-user?view=o365-worldwide', note: `First-party administrator guidance distinguishing mailbox access, Send As, and Send on Behalf permissions. ${checked}` },
  { name: 'Federal Trade Commission, Cybersecurity for Small Business', url: 'https://www.ftc.gov/business-guidance/small-businesses/cybersecurity', note: `Official U.S. business guidance on remote access, vendor security, written requirements, verification, access limitation, and multi-factor authentication. ${checked}` },
  { name: 'NIST Cybersecurity Framework 2.0: Small Business Quick-Start Guide', url: 'https://doi.org/10.6028/NIST.SP.1300', note: `Primary NIST guide used for governance, asset, supplier, protection, detection, response, and recovery concepts; it does not endorse an assistant arrangement. ${checked}` },
  { name: 'NIST SP 800-53 Rev. 5, Security and Privacy Controls', url: 'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final', note: `Primary control catalogue used for least privilege, account management, audit, separation of duties, external services, and contingency concepts. ${checked}` },
];

const specs: readonly ResearchDecisionSpec[] = [
  {
    slug: 'executive-calendar-delegation-readiness-record',
    title: 'An executive calendar delegation readiness record',
    excerpt: 'A buyer-side test of permissions, decision rules, sensitive-event boundaries, and review capacity before an assistant changes a live executive calendar.',
    cluster: 'Executive calendar research',
    question: 'Is a defined calendar lane ready for delegated preparation or action without transferring the executive’s priority decisions?',
    decision: 'whether an assistant may only prepare proposed calendar changes, may execute a narrow class of pre-approved changes, or must wait because the rules, access, or reviewer are not ready',
    unit: 'one calendar request linked to requester identity, source message, time zone, event sensitivity, conflict state, proposed action, authority rule, decision owner, calendar event identifier, and final disposition',
    evidence: 'a consecutive sample of accepted, declined, rescheduled, conflicted, sensitive, travel-linked, and unresolved requests; current sharing settings; event categories; executive preferences; response templates; and reviewer decisions',
    variation: 'internal versus external requests, single versus recurring events, travel buffers, working hours, time zones, confidential titles, delegate visibility, organizer identity, and the consequence of an incorrect acceptance or decline',
    boundary: 'This readiness record can show whether a named calendar lane has explicit controls. It cannot determine an executive’s priorities, guarantee schedule accuracy, authorize access to unrelated email, or prove that delegation improves productivity.',
    test: 'Have the assistant prepare but not send actions for a representative request set, compare each proposal with the owner’s independent decision, and enable only the request classes whose rules and permission path are consistently understood.',
    failure: 'granting broad mailbox or administrator rights for a calendar-only task, treating an available time slot as approval, hiding sensitive event details in copied notes, or letting the assistant infer priority from seniority or persistence',
    owner: 'the executive or named calendar manager who can set priorities, approve sensitive-event handling, and revoke delegated access',
    handoff: '/services/executive-calendar-management', label: 'review executive calendar support',
    related: ['calendar-request-screening', 'assistant-calendar-approval-rules', 'calendar-delegation-controls'],
  },
  {
    slug: 'shared-inbox-delegation-control-study',
    title: 'Testing control readiness for a delegated shared inbox',
    excerpt: 'A reconstruction method for mailbox permissions, sender identity, routing rules, approval boundaries, and exception ownership before delegated replies begin.',
    cluster: 'Inbox delegation research',
    question: 'Can a bounded inbox queue be delegated while preserving sender identity, decision ownership, privacy, and a complete record of unresolved messages?',
    decision: 'whether an assistant may classify only, draft for approval, send on behalf under declared rules, or must stop because access, identity, or escalation controls are incomplete',
    unit: 'one eligible message thread linked to mailbox, received time, sender, sensitivity, category, promised response window, proposed action, approval state, sending identity, exception owner, and closure evidence',
    evidence: 'mailbox permission exports, a consecutive message sample including spam and sensitive cases, routing and retention rules, approved response examples, escalation contacts, sent-item evidence, corrections, and open-thread reconciliation',
    variation: 'personal versus shared mailboxes, Full Access versus sending rights, internal versus external senders, personal data, legal or financial consequence, thread age, attachments, duplicate replies, and after-hours arrivals',
    boundary: 'This study evaluates the readiness of a declared inbox lane. It does not authorize impersonation, provide legal or privacy advice, establish that every message can be delegated, or convert mailbox access into authority to make commitments.',
    test: 'Run classification and draft-only passes over an eligible consecutive sample, reconcile every thread to the source mailbox, compare reviewer decisions, and enable sending only for pre-approved message classes with an auditable identity.',
    failure: 'assuming Full Access includes sending authority, sharing a password, sending from the wrong identity, closing a thread because it was labelled, or excluding difficult and unanswered messages from the review denominator',
    owner: 'the mailbox owner or service manager accountable for response commitments, sensitive cases, approval rules, and access removal',
    handoff: '/services/inbox-triage', label: 'scope an inbox triage lane',
    related: ['delegated-inbox-labeling', 'shared-inbox-escalation-notes', 'support-queue-privacy-controls'],
  },
  {
    slug: 'crm-assistant-change-authority-matrix',
    title: 'Building a CRM change-authority matrix for assistant support',
    excerpt: 'A field-level buyer record for separating evidence collection, proposed edits, approved changes, merges, exports, and consequential CRM decisions.',
    cluster: 'CRM administration research',
    question: 'Which CRM fields and actions can an assistant prepare or execute, with what source evidence, review rule, and rollback path?',
    decision: 'whether each recurring CRM action is read-only, proposal-only, pre-approved execution, case-by-case approval, specialist-controlled, or prohibited for the delegated lane',
    unit: 'one field or action linked to business purpose, authoritative source, allowed values, permission, approval threshold, audit event, downstream dependency, exception route, rollback method, and accountable owner',
    evidence: 'the CRM data dictionary, role and permission exports, sample records, import and merge history, workflow dependencies, duplicate rules, approved sources, audit logs, error corrections, export controls, and owner interviews',
    variation: 'contact versus company records, descriptive versus status fields, manual versus imported changes, merges, deletions, bulk edits, marketing consent, ownership, pipeline stage, financial fields, and downstream automations',
    boundary: 'A change-authority matrix documents local control decisions. It does not establish a lawful basis for data processing, certify CRM accuracy, grant sales or financial authority, or justify collecting data that the business does not need.',
    test: 'Apply the draft matrix to historical normal, duplicate, incomplete, conflicting, and sensitive records in a reversible environment; compare decisions and audit events; then activate only actions with a reliable source and rollback path.',
    failure: 'treating every editable field as delegable, merging on name similarity alone, overwriting an authoritative system with stale notes, bulk-changing records without a rollback file, or allowing exports because screen access already exists',
    owner: 'the CRM business owner, supported by system, privacy, security, marketing, sales, and finance owners for fields within their authority',
    handoff: '/services/crm-administration', label: 'review CRM administration support',
    related: ['crm-field-change-governance', 'crm-duplicate-record-review', 'outsourced-crm-audit-trail'],
  },
  {
    slug: 'outsourced-research-brief-acceptance-protocol',
    title: 'An acceptance protocol for outsourced research briefs',
    excerpt: 'A decision-grade review model for question fit, source authority, claim support, uncertainty, freshness, and owner acceptance in recurring research work.',
    cluster: 'Research briefing operations',
    question: 'What must a research brief show before a buyer can use it to inform a defined operating decision?',
    decision: 'whether a brief is accepted for its declared use, returned for a named evidence gap, narrowed to a weaker conclusion, escalated to a specialist, or rejected as unsuitable',
    unit: 'one material claim linked to the decision question, source title, publisher, URL, publication or version date, checked date, exact support, claim type, uncertainty, contradiction, reviewer decision, and permitted use',
    evidence: 'the approved question and scope, search and exclusion record, primary and authoritative sources, claim-source map, dated extracts or notes, contrary evidence, calculation files, reviewer annotations, revisions, and final acceptance decision',
    variation: 'fact versus analysis or inference, stable versus time-sensitive claims, direct versus indirect support, jurisdiction, sample and population, conflicting definitions, inaccessible sources, commercial incentives, and decision consequence',
    boundary: 'This protocol can make a brief reconstructable for a stated business use. It does not turn desk research into legal, medical, tax, financial, security, or other professional advice and cannot eliminate uncertainty or source error.',
    test: 'Have two reviewers trace the highest-consequence claims to their named sources without private explanation, record disagreements and missing context, and accept only the conclusions whose evidence strength matches the intended decision.',
    failure: 'counting source volume instead of authority and fit, attaching one citation to several unsupported claims, hiding conflicting evidence, presenting inference as fact, or refreshing the checked date without rechecking the underlying source',
    owner: 'the business decision owner who commissioned the brief and can define acceptable uncertainty, with qualified specialist review where the decision requires it',
    handoff: '/services/research-briefing', label: 'scope a research briefing workflow',
    related: ['sourced-brief-acceptance', 'research-evidence-strength-ranking', 'content-research-source-traceability'],
  },
  {
    slug: 'vendor-follow-up-decision-rights-register',
    title: 'A decision-rights register for delegated vendor follow-up',
    excerpt: 'A buyer-side control record for routine chasers, disputed facts, commitments, sensitive changes, escalation, and closure in vendor communication.',
    cluster: 'Vendor follow-up research',
    question: 'Which vendor follow-up actions can an assistant perform without making an unauthorized commercial, financial, security, or delivery commitment?',
    decision: 'whether a follow-up class may be sent from an approved template, requires draft review, must route to a specialist owner, or must remain outside the delegated lane',
    unit: 'one vendor obligation or question linked to contract or order reference, source record, due date, current state, approved wording, sender identity, authority limit, response evidence, exception owner, and verified closure',
    evidence: 'current vendor and owner registers, executed agreements or purchase records, approved contacts, due-date sources, communication history, template versions, disputed cases, access rights, change-verification procedures, and closure acceptance',
    variation: 'information requests versus commitments, ordinary delays versus disputes, bank or contact changes, confidential attachments, regulated suppliers, contract renewals, service incidents, price questions, and cross-border or time-zone dependencies',
    boundary: 'A decision-rights register supports consistent follow-up on a declared vendor lane. It does not interpret contracts, approve purchases, change bank details, accept risk, waive rights, promise payment, or certify vendor security or performance.',
    test: 'Classify a representative history of normal, late, disputed, changed-detail, and security-sensitive cases; independently apply the authority rules; then pilot only routine requests whose source, wording, recipient, and escalation owner are verified.',
    failure: 'treating a reminder as harmless when it implies acceptance, copying bank changes from email into a payment record, using an outdated contact, closing on a promise without evidence, or letting queue age override a specialist stop rule',
    owner: 'the contract, procurement, finance, security, or operating owner accountable for the obligation and authorized to resolve the specific exception',
    handoff: '/services/vendor-follow-up', label: 'define a vendor follow-up lane',
    related: ['vendor-follow-up-authority-limits', 'vendor-record-verification', 'vendor-contact-verification'],
  },
];

export const researchBatch20260923: readonly ResearchPost[] = specs.map(spec => ({
  ...buildDecisionResearch(spec, sources),
  published: '2026-09-23',
  updated: '2026-09-23',
  methodology: buildDecisionResearch(spec, sources).methodology
    .replaceAll('September 22, 2026', 'September 23, 2026'),
}));
