import type { ResearchPost } from './fleet-content';

type Spec = { slug:string; title:string; excerpt:string; cluster:string; question:string; finding:string; method:string; limitation:string; pilot:string };
const specs: Spec[] = [
  ['delegated-queue-blocker-owner-analysis','How should teams analyze blocker ownership in delegated queues?','A bounded study of where work waits after an assistant has prepared evidence for a decision.','Distributed work','which role or dependency owns the event required to move blocked work forward','Blocker age becomes actionable only when the required event, current owner, ready time, review window, and consequence are recorded separately.','Timestamp entry into each blocked state and record the missing event, evidence prepared, owner, reminders, deadline, and transition.','Ownership of the next event does not prove fault; necessary controls and external responses can create delay.','Observe one recurring queue for three weeks, review the ten oldest blockers, and change one reminder or review-window rule.'],
  ['assistant-verification-channel-reliability-study','What makes an assistant verification channel reliable?','Research on whether sensitive requests are verified independently rather than inside a suspect message.','Security research','whether the verification path is established, independent, reachable, and tied to an authorized decision maker','Verification is stronger when the contact route predates the request and the result records identity, authority, time, and the exact change confirmed.','Sample sensitive changes and capture the initiating channel, verification source, verifier identity, response, mismatch, and resulting action.','A familiar channel can be compromised, and successful contact establishes authority only for the decision confirmed.','Review one month of payment, access, and delivery changes and independently recheck a small high-risk sample.'],
  ['outsourced-article-claim-revision-rate','What can claim-revision rates show about outsourced article quality?','A study separating evidence problems from ordinary editing, style changes, and newly available information.','Content research','which claim changes reveal a gap in evidence, scope control, freshness, or editorial instruction','Claim-revision rates are interpretable only when revisions preserve original wording and use reason codes tied to evidence and editorial decisions.','For material claims, record original and revised text, reason, cited evidence, reviewer, publication state, and correction date.','Frequent revision can reflect healthy review or changing facts; rates cannot be compared without compatible definitions.','Code two weeks of revisions, double-review ambiguous reasons, and update one brief field linked to the most common preventable gap.'],
  ['virtual-assistant-approval-packet-completeness','How can approval-packet completeness be measured in virtual assistant workflows?','A method for testing whether a decision owner receives needed facts without reconstructing the case.','Operations research','whether the first approval request includes the decision, evidence, alternatives, boundary, and time constraint','Packet completeness is a field-level observation, not a judgment based on whether the owner answered quickly or agreed.','Define required fields for one approval type, then record presence, correctness, source linkage, clarification requests, and disposition.','A complete packet cannot eliminate legitimate questions, and required fields differ by decision type and consequence.','Score twenty consecutive packets, add one missing high-value field, and observe the next twenty without other changes.'],
  ['assistant-access-review-evidence-coverage','How should evidence coverage be tested during assistant access reviews?','Research on connecting each retained permission to current work, ownership, last use, and business purpose.','Governance research','whether every retained permission has enough evidence to justify its scope and duration','Coverage should count permissions with complete evidence while keeping unknown, inherited, shared, and unused grants visible in the denominator.','Inventory permissions and record user, resource, level, purpose, owner, last use, authentication control, decision, and next review.','Last-use data may be incomplete, and inactivity alone does not prove access is unnecessary for rare events or continuity.','Review two tools with different risk levels, validate a sample of retained grants, and remove access only through the authorized process.'],
].map(([slug,title,excerpt,cluster,question,finding,method,limitation,pilot])=>({slug,title,excerpt,cluster,question,finding,method,limitation,pilot} as Spec));

const sources=[
  {name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework',note:'Governance and accountable-control context.'},
  {name:'UK Government Service Manual: Measuring Success',url:'https://www.gov.uk/service-manual/measuring-success',note:'Measurement framing and interpretation.'},
  {name:'OECD Measuring Productivity',url:'https://www.oecd.org/en/topics/sub-issues/measuring-productivity.html',note:'Denominator and comparison cautions.'},
];
const make=(s:Spec):ResearchPost=>({
  slug:s.slug,title:s.title,excerpt:s.excerpt,cluster:s.cluster,published:'2026-09-02',updated:'2026-09-02',headlineStat:s.finding,
  methodology:`Research question: ${s.question}. ${s.method} This is a bounded OutsourcingAssistant.com operating study, not a causal claim, universal benchmark, or evaluation based on nationality.`,
  keyStats:[s.finding,'The eligible population, missing records, and excluded states remain explicit.','Preparation, dependency waiting, owner decision, and execution are measured separately.'],
  takeaways:['Define the operational decision before selecting the measure.','Preserve original states and evidence for reconstruction.','Test one documented process change, then observe a comparable period.'],
  sections:[
    {heading:'Define the question and eligible population',paragraphs:[`The question is ${s.question}. Declare the queue, period, included records, exclusions, and authorized decision owner before collection.`,'A Philippines-based assistant can maintain evidence. The accountable owner decides comparability and whether change is justified.'],rows:[{label:'Question',value:s.question,source:'Local study protocol'},{label:'Decision owner',value:'Person authorized to change the observed workflow',source:'NIST governance context'}]},
    {heading:'Build a reconstructable observation',paragraphs:[s.method,'Retain prior states and source references so another reviewer can check classification without relying on memory.'],rows:[{label:'Minimum record',value:'Item, state, event, timestamp, source, owner, reason, and disposition',source:'UK Government measurement guidance'},{label:'Publication date',value:'September 2, 2026',source:'OutsourcingAssistant.com batch record'}]},
    {heading:'Interpret within the boundary',paragraphs:[s.finding,s.limitation],rows:[{label:'Supported use',value:'Improve the defined local operating routine',source:'This study design'},{label:'Unsupported use',value:'Universal ranking, individual blame, or causal attribution',source:'OECD measurement cautions'}]},
    {heading:'Run a controlled pilot',paragraphs:[s.pilot,'Record the baseline, one changed rule, observation window, missing cases, and result. Stop if missing or incomparable records could reverse the conclusion.'],rows:[{label:'Pilot',value:s.pilot,source:'Local operating proposal'},{label:'Stop rule',value:'Pause when missing or incomparable cases could materially change the result',source:'Research governance analysis'}]},
    {heading:'Conclusion and limitations',paragraphs:[`The narrow conclusion is: ${s.finding} This supports local review, not a claim about every assistant or team.`,`Primary limitation: ${s.limitation} The owner retains access, policy, personnel, customer-impact, and publication decisions.`],rows:[{label:'Conclusion',value:s.finding,source:'Source synthesis'},{label:'Primary limitation',value:s.limitation,source:'Scope analysis'}]},
  ],
  faqs:[{q:'Does this create a universal benchmark?',a:'No. It describes a defined local population and period; comparisons require compatible definitions and methods.'},{q:'What work can the assistant own?',a:'The assistant can collect observations and prepare analysis. An authorized owner decides consequential changes and public interpretation.'}],
  sources,related:['assistant-quality-scorecard','time-zone-handoff-design','claim-scope-provenance'],body:[],
});
export const researchBatch20260902: readonly ResearchPost[] = specs.map(make);
