import type { ResearchPost, ResearchSection, ResearchSource } from './fleet-content';

const sources: readonly ResearchSource[] = [
 {name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework',note:'Primary governance and risk-management framework.'},
 {name:'NIST SP 800-53 Revision 5, Update 1',url:'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final',note:'Primary controls guidance for access, accountability, and review.'},
 {name:'U.S. GAO Assessing Data Reliability',url:'https://www.gao.gov/products/gao-20-283g',note:'Primary methodology guidance for judging whether evidence is fit for its intended use.'},
 {name:'UK Government Service Manual: Measuring success',url:'https://www.gov.uk/service-manual/measuring-success',note:'Official guidance on selecting and interpreting service measures.'},
 {name:'ILO, Working from Home',url:'https://www.ilo.org/publications/working-home-estimating-worldwide-potential',note:'International research context for remote-work organisation and the limits of broad estimates.'}
];
type Spec={slug:string;title:string;excerpt:string;cluster:string;question:string;unit:string;signal:string;limit:string;test:string;image:string};
const specs:Spec[]=[
 {slug:'assistant-approval-queue-stale-item-study',title:'When does an assistant approval queue become stale?',excerpt:'A local study design for separating legitimate owner waiting from abandoned, superseded, and evidence-poor requests.',cluster:'Operations research',question:'Which observable conditions make a decision-ready item stale?',unit:'one approval item with ready time, evidence version, decision owner, review window, state changes, and disposition',signal:'Age alone does not establish staleness; ownership, evidence currency, and whether the requested decision still matters must be observed together.',limit:'This design does not supply a universal ageing threshold or prove that a delayed approval reflects poor performance.',test:'Compare consecutive approval items by decision class and inspect whether the evidence or business need changed before disposition.',image:'/images/research-2026-08-23/overnight-research-review-readiness.png'},
 {slug:'delegated-data-entry-source-distance-review',title:'Studying source distance in delegated data entry',excerpt:'A claim-level method for testing how many transformations sit between an original record and an assistant-prepared field.',cluster:'Data quality',question:'Does greater source distance make a prepared field harder to verify?',unit:'one prepared field linked to the original record, each transformation, conflicts, reviewer decision, and correction outcome',signal:'Source distance is useful only when each transformation is visible; a simple count cannot substitute for evidence quality or consequence.',limit:'The proposed record does not establish a causal error rate and should not be compared across unlike fields or systems.',test:'Trace a consecutive sample of corrected and unchanged fields, then have a second reviewer reconstruct each value from the retained source chain.',image:'/images/research-2026-08-20/assistant-source-chain-for-daily-articles.png'},
 {slug:'philippines-assistant-escalation-window-fit',title:'Evaluating escalation-window fit for Philippines-based assistant work',excerpt:'A scoped comparison of incident consequence, owner availability, documented handoffs, and the time until a safe decision.',cluster:'Distributed work',question:'Does the stated escalation window match the decisions a workflow actually generates?',unit:'one escalated event with Philippine and owner-local timestamps, consequence class, available evidence, contact attempts, response, and disposition',signal:'An escalation window is fit for purpose only when the authorised owner can respond before waiting creates the stated consequence.',limit:'The reviewed sources do not specify an optimal time-zone overlap or response target for Philippines-based teams.',test:'Map consecutive escalations against the planned coverage window and separately report events that could safely wait, required live review, or lacked an owner.',image:'/images/research-2026-08-21/philippines-assistant-article-handoff-window.png'},
 {slug:'outsourced-content-citation-drift-audit',title:'Auditing citation drift in outsourced content revisions',excerpt:'A reproducible audit for finding when a supported draft claim changes while its old citation remains attached.',cluster:'Content research',question:'How can editors detect that revision has moved a claim beyond its source?',unit:'one material claim across draft versions with exact wording, cited source, supported scope, revision reason, reviewer, and final disposition',signal:'Citation presence is not citation support; the claim and the source scope must be compared again after a material revision.',limit:'The audit detects reviewable mismatches but does not score overall article truth or infer an author’s intent.',test:'Blindly review a sample of changed material claims against primary sources, recording support as direct, partial, conflicting, or absent.',image:'/images/research-2026-08-21/source-freshness-for-daily-outsourced-articles.png'},
 {slug:'virtual-assistant-exception-owner-continuity',title:'Measuring owner continuity in virtual assistant exception handling',excerpt:'A bounded method for examining whether consequential exceptions retain a reachable decision owner from intake through closure.',cluster:'Governance research',question:'What evidence shows that an exception kept a responsible owner through handoffs?',unit:'one exception with consequence, assigned owner, coverage changes, handoff acceptance, decisions, timestamps, and closure evidence',signal:'An owner name is insufficient when availability, acceptance, and decision authority are not recorded at the point of handoff.',limit:'This local process measure cannot establish individual accountability, legal responsibility, or a universal staffing ratio.',test:'Follow consecutive consequential exceptions end to end and identify every interval with no accepted, reachable, authorised owner.',image:'/images/research-2026-09-03/manager-feedback-sop-change-thresholds.png'}
];
const section=(heading:string,paragraphs:string[],rows:ResearchSection['rows']):ResearchSection=>({heading,paragraphs,rows});
const make=(x:Spec):ResearchPost=>({slug:x.slug,title:x.title,excerpt:x.excerpt,cluster:x.cluster,published:'2026-09-08',updated:'2026-09-08',image:{url:x.image,alt:`Research evidence illustration for ${x.title}`},headlineStat:x.signal,methodology:`Structured desk review of five named public sources, followed by a proposed local observational design. The unit of analysis is ${x.unit}. Source principles are separated from OutsourcingAssistant.com operating inferences; no causal or universal performance claim is made.`,keyStats:['Five reputable public sources in the review protocol',`Unit of analysis: ${x.unit}`,'Consecutive local cases proposed to reduce selection by outcome'],takeaways:[x.signal,'Retain raw evidence and state changes before assigning categories.','Keep consequential interpretation with the authorised owner.'],sections:[
 section('Question, scope, and evidence boundary',[`${x.question} This review draws on public governance, control, data-reliability, measurement, and remote-work guidance. None of the sources tests this exact assistant workflow, so the operational design below is an inference to test locally, not a published benchmark.`,`The observation unit is ${x.unit}. Fixing the unit before collection prevents messages, whole projects, and owner decisions from being mixed in one denominator.`],[{label:'Evidence set',value:'Five named public sources',source:'Desk-review protocol'},{label:'Intended use',value:'Local process diagnosis',source:'Author-defined scope'}]),
 section('Method and observation record',[`Record the original request, source evidence, current state, responsible owner, timestamps, and final disposition. Preserve missing and conflicting values instead of replacing them with a convenient category.`,x.test],[{label:'Sampling',value:'Consecutive in-scope cases over a stated period',source:'Proposed method'},{label:'Minimum record',value:'Source, state, owner, time, and disposition',source:'NIST and GAO principles'}]),
 section('Interpretation',[`${x.signal} Compare like-for-like decision classes, publish the inclusion rule, and report counts with denominators.`, `For a Philippines-based workflow, preserve both Philippine Time and the owner’s local review window. This distinguishes planned overnight waiting from a missing escalation path.`],[{label:'Primary signal',value:x.signal,source:'Evidence-informed operating inference'},{label:'Time-zone field',value:'Expected and actual owner-review window',source:'Proposed observation design'}]),
 section('Limitations and inference limits',[x.limit,`The sources support disciplined governance and measurement principles, but applying them to OutsourcingAssistant.com requires local validation. Findings may be affected by task mix, seasonality, missing records, changing owners, or reviewer disagreement.`],[{label:'Claim limit',value:x.limit,source:'Review boundary'},{label:'Excluded claim',value:'No universal benchmark or causal effect',source:'Methodology'}]),
 section('Small operational pilot',[`Pilot the record on a consecutive, bounded sample and have a second reviewer test whether each classification can be reconstructed from the retained evidence. Record disagreements rather than forcing consensus after the fact.`,`Change one workflow element at a time, retain the baseline, and inspect unintended effects such as added collection burden, delayed escalation, or sensitive data copied into the research record.`],[{label:'Quality check',value:'Independent reconstruction from retained evidence',source:'Proposed method'},{label:'Change rule',value:'One documented change with baseline retained',source:'Measurement design'}])
],sources:[...sources],related:[],body:[],faqs:[{q:'Is this a benchmark?',a:'No. It is a local observational design informed by public guidance.'},{q:'What is measured?',a:x.unit},{q:'What remains uncertain?',a:x.limit}],serviceHandoff:{heading:'Turn the question into a reviewable brief',href:'/services/research-briefing',label:'research briefing support',paragraphs:['Use research briefing support to define the question, evidence boundary, source register, and review owner.','The owner remains responsible for scope, interpretation, and consequential decisions.']}});
export const researchBatch20260908: readonly ResearchPost[] = specs.map(make);
