import type { ResearchPost, ResearchSource, ResearchSection } from './fleet-content';

const sources: readonly ResearchSource[]=[
 {name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework',note:'Governance and risk-management outcomes.'},
 {name:'NIST SP 800-53 Revision 5',url:'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final',note:'Access, accountability, and audit guidance.'},
 {name:'GAO Assessing Data Reliability',url:'https://www.gao.gov/products/gao-20-283g',note:'Framework for determining whether evidence is fit for use.'},
 {name:'UK Government Service Manual: Measuring success',url:'https://www.gov.uk/service-manual/measuring-success',note:'Guidance on choosing and interpreting service measures.'},
 {name:'ILO Working from Home',url:'https://www.ilo.org/publications/working-home-estimating-worldwide-potential',note:'Remote-work organisation and limits of broad estimates.'}
];
type Spec={slug:string;title:string;excerpt:string;cluster:string;question:string;unit:string;signal:string;limit:string;image:string};
const specs:Spec[]=[
 {slug:'assistant-clarification-wait-time-study',title:'Measuring clarification wait time in delegated assistant queues',excerpt:'A bounded design for separating incomplete intake, owner response time, and active preparation.',cluster:'Operations research',question:'What does clarification waiting actually measure?',unit:'one clarification event with request, evidence gap, responsible owner, timestamps, and disposition',signal:'Clarification time is interpretable only when active work, owner waiting, and external waiting are recorded separately.',limit:'The method does not prove why a person responded slowly or establish a universal service target.',image:'/images/research-2026-08-23/research-stop-rules-source-conflict.png'},
 {slug:'outsourced-article-source-diversity-review',title:'Reviewing source diversity in outsourced article research',excerpt:'A claim-level approach to source variety that does not mistake a longer bibliography for stronger evidence.',cluster:'Content research',question:'When does source diversity improve an article?',unit:'one material claim mapped to publisher, source type, population, date, finding, and limitation',signal:'Source diversity is useful when independent evidence addresses the same claim from relevant scopes, not when citations merely accumulate.',limit:'This desk review does not validate a diversity score or show that more publishers always improve accuracy.',image:'/images/research-2026-08-21/source-freshness-for-daily-outsourced-articles.png'},
 {slug:'virtual-assistant-owner-review-capacity',title:'Estimating owner review capacity for virtual assistant work',excerpt:'A transparent way to compare decision-ready work with the owner time actually available to approve it.',cluster:'Distributed work',question:'Is queue growth caused by assistant throughput or limited owner review?',unit:'one review window with ready items, decision classes, available owner minutes, and dispositions',signal:'Production capacity and approval capacity are different resources and should be measured in separate queues.',limit:'Observed local capacity does not predict other teams and cannot isolate productivity from task complexity.',image:'/images/research-2026-08-21/philippines-assistant-article-handoff-window.png'},
 {slug:'delegated-record-correction-reversal-rate',title:'Studying reversals after delegated record corrections',excerpt:'A local quality measure that preserves correction type, evidence strength, consequence, and owner approval.',cluster:'Quality systems',question:'What can a reversed correction tell an operations team?',unit:'one proposed record correction with source evidence, approval, applied change, later reversal, and reason',signal:'A reversal becomes useful evidence only when the original basis and the reason for reversal remain linked.',limit:'A small reversal count cannot establish error rates across workers or prove that delegation caused the outcome.',image:'/images/research-2026-09-03/manager-feedback-sop-change-thresholds.png'},
 {slug:'philippines-handoff-overlap-window-analysis',title:'Analysing overlap windows in Philippines-based assistant handoffs',excerpt:'A scoped comparison of synchronous overlap, documented handoffs, decision access, and unresolved work.',cluster:'Distributed work',question:'How much live overlap does a distributed assistant workflow need?',unit:'one recurring workflow observed across a stated period with handoff and decision timestamps',signal:'Overlap is valuable for specific clarification and decision needs; more shared hours are not automatically better.',limit:'The cited sources do not specify an optimal Philippines-to-owner overlap duration or prove causal performance effects.',image:'/images/research-2026-08-21/philippines-assistant-article-handoff-window.png'}
];
const section=(heading:string,paragraphs:string[],rows:ResearchSection['rows']):ResearchSection=>({heading,paragraphs,rows});
const make=(x:Spec):ResearchPost=>({slug:x.slug,title:x.title,excerpt:x.excerpt,cluster:x.cluster,published:'2026-09-07',updated:'2026-09-07',image:{url:x.image,alt:`Evidence review illustration for ${x.title}`},headlineStat:x.signal,methodology:`This is a structured desk review of five named public sources. The proposed unit of analysis is ${x.unit}. Source principles are separated from the author’s operating recommendations; no causal or universal performance claim is made.`,keyStats:['Five reputable public sources reviewed',`Unit of analysis: ${x.unit}`,'Evidence, state, owner, and time retained before interpretation'],takeaways:[x.signal,'Keep raw observations beside categories and calculations.','Route consequential interpretation to the authorised owner.'],sections:[
 section('Research question and scope',[`${x.question} The evidence set covers governance, data reliability, measurement, access control, and remote-work organisation. None of the sources evaluates this exact OutsourcingAssistant.com routine, so the workflow is an evidence-informed proposal rather than a validated benchmark.`,`The analysis uses ${x.unit}. A fixed unit prevents messages, whole projects, and owner decisions from being mixed in one denominator.`],[{label:'Evidence set',value:'Five named public sources',source:'Review protocol'},{label:'Unit',value:x.unit,source:'Proposed measurement design'}]),
 section('Observation record',[`Record the original request, source evidence, current state, responsible owner, time of each state change, and final disposition. Preserve missing and conflicting values.`,`${x.signal} For Philippines-based work, include the expected owner review window so planned overnight waiting is not classified as an unowned delay.`],[{label:'Minimum fields',value:'Evidence, state, owner, timestamp, disposition',source:'NIST and GAO principles'},{label:'Time-zone field',value:'Expected and actual review window',source:'Proposed operating record'}]),
 section('Interpretation and limitations',[`Compare like-for-like cases over a stated period, publish inclusion and exclusion rules, and keep consequential categories separate. Report counts with their denominator rather than presenting a percentage alone.`,`${x.limit} The sources support disciplined governance and measurement principles, but transferring them to an assistant queue requires local testing and owner review.`],[{label:'Scope limit',value:x.limit,source:'Author interpretation boundary'},{label:'Safe use',value:'Local process review, not universal benchmarking',source:'Review protocol'}]),
 section('Operational test',[`Pilot the record on a small consecutive sample. Have a second reviewer check whether the evidence supports the state and disposition without relying on private chat or memory.`,`Change one part of the workflow at a time, preserve the baseline, and review unintended effects such as added data collection, delayed escalation, or hidden owner work.`],[{label:'Pilot',value:'Consecutive local cases with explicit inclusion rules',source:'Proposed method'},{label:'Review',value:'Source fidelity, consistent classification, and owner boundary',source:'Proposed method'}])
],sources:[...sources],related:[],body:[],faqs:[{q:'Is this a benchmark?',a:'No. It is a local measurement design informed by public guidance.'},{q:'What should the assistant record?',a:`The assistant should record ${x.unit}, using only data needed for the stated review.`},{q:'What remains uncertain?',a:x.limit}],serviceHandoff:{heading:'Apply the finding carefully',href:'/services/research-briefing',label:'research briefing support',paragraphs:[`Use research briefing support to turn the question into a sourced, reviewable brief.`,`The owner remains responsible for scope, interpretation, and consequential decisions.`]}});

export const researchBatch20260907: readonly ResearchPost[] = specs.map(make);
