import type { ResearchPost, ResearchSection, ResearchSource } from './fleet-content';

const src = (items: ResearchSource[]) => items;
const row = (label: string, value: string, source: string) => ({ label, value, source });
const sec = (heading: string, paragraphs: string[], rows: ReturnType<typeof row>[]): ResearchSection => ({ heading, paragraphs, rows });
const common: ResearchSource[] = [
  { name: 'OECD Measuring Productivity', url: 'https://www.oecd.org/en/topics/sub-issues/measuring-productivity.html', note: 'Definitions and cautions for interpreting productivity evidence.' },
  { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework', note: 'Governance and risk-management concepts applied to role boundaries.' },
  { name: 'ILO Working from Home Report', url: 'https://www.ilo.org/global/topics/non-standard-employment/publications/WCMS_765806/lang--en/index.htm', note: 'Evidence about how remote work is organised and experienced.' },
];

const records: ResearchPost[] = [
  {
    slug: 'outsourced-article-intake-question-quality',
    image: { url: '/images/research-2026-08-21/outsourced-article-intake-question-quality.png', alt: 'Remote assistant reviewing a focused article research brief' },
    title: 'Which intake questions make outsourced article research answerable?',
    excerpt: 'A bounded study of how a content owner can turn a recurring article request into a research question an assistant can investigate without guessing.',
    published: '2026-08-21', updated: '2026-08-21', cluster: 'Research operations',
    headlineStat: 'A topic names a subject; an answerable intake names a reader, decision, evidence boundary, and owner.',
    methodology: 'Research question: which intake fields most reduce ambiguity when a Philippines-based assistant prepares daily research for an outsourcing-focused site? This desk review compares OECD productivity definitions, NIST governance guidance, the ILO remote-work report, and the U.S. Government Publishing Office Style Manual. It applies those concepts to article preparation, not to a staffing forecast, legal conclusion, or claim about company performance. Facts from the sources are separated from the local operating analysis below.',
    keyStats: ['A research question should name the reader decision, not only a keyword', 'Evidence scope should state population, period, and source class', 'The owner retains approval of public interpretation and company-specific claims'],
    takeaways: ['Ask what decision the article should help a reader make.', 'Give the assistant a stop condition when evidence cannot support the proposed claim.', 'Record unresolved questions as review items rather than filling gaps with plausible detail.'],
    sections: [
      sec('Why a keyword is an incomplete brief', [
        'A request such as “write about outsourcing assistants” gives a subject but no test for relevance. An assistant can collect many pages and still miss the reader’s actual problem: whether to delegate a repeatable research step, how to preserve review ownership, or when an exception needs escalation. The first intake question should therefore name the operational decision. The niche belongs in the question itself, not as a sentence added after generic research has been collected.',
        'This is an analysis of brief quality, not a claim that one wording guarantees a strong article. A narrow question can still have weak evidence, and a well-sourced question can be poorly edited. Its value is diagnostic: the owner can see early whether the requested page is about a real outsourcing choice or merely a broad topic that could fit any productivity site.'
      ], [row('Weak intake', 'Subject and keyword without a decision', 'This review method'), row('Stronger intake', 'Reader, decision, operating context, and evidence boundary', 'OECD and NIST concepts')]),
      sec('Specify the evidence before the search', [
        'Evidence scope tells the researcher what a source is allowed to establish. An official occupational description may explain the nature of administrative work, but it cannot estimate the output of one assistant. Productivity guidance can distinguish inputs from outputs, but it cannot prove that a particular delegation arrangement will create a fixed gain. A remote-work study can provide context for handoffs, while remaining silent about this site’s publishing queue.',
        'A useful intake records the population, period, jurisdiction, source classes, and freshness requirement. It also says what the article must not claim. Those fields narrow the search in a productive way: when no source fits the stated scope, the assistant can return with a smaller question or a limitation. That is safer than expanding the conclusion until a convenient citation appears.'
      ], [row('Scope fields', 'Population, unit, period, jurisdiction, method, source class', 'OECD definitions'), row('Stop condition', 'No source supports the proposed claim within scope', 'Evidence-boundary analysis')]),
      sec('Make the handoff decision-ready', [
        'The intake should leave room for a source table, a proposed thesis, competing interpretations, and a list of owner decisions. The assistant can prepare those materials and identify conflicts. The editor can decide whether the sources are sufficiently relevant, whether examples remain hypothetical, and whether the conclusion belongs on a public page. Separating preparation from approval gives the work a visible boundary.',
        'For daily article creation, this also protects the review window. A packet that states “approve, narrow, request another source, or stop” is easier to handle than a polished draft with uncertainty buried in its prose. The owner does not need to reread every search result; they do need enough context to understand why each material claim is present and what remains unproven.'
      ], [row('Assistant output', 'Question, source notes, outline, limitations, open decisions', 'Role-boundary analysis'), row('Owner decision', 'Approve, narrow, request evidence, or stop', 'NIST governance frame')]),
      sec('Limitations and evidence-led conclusion', [
        'This review does not test which intake form produces the highest publishing rate, determine an ideal number of fields, or establish that remote preparation is faster. Source definitions differ, public evidence may not match a small business question, and a changing topic may require a fresh review. The proposed fields are a reasoning aid, not a universal standard.',
        'The evidence-led conclusion is that outsourced article research becomes more answerable when the intake names a reader decision, evidence scope, role boundary, and escalation route. A Philippines-based assistant can prepare the investigation inside that boundary. An authorised editor should retain the final decision about public wording, company facts, and the conclusion.'
      ], [row('Supported conclusion', 'Better-defined questions make evidence gaps visible earlier', 'OECD, NIST, ILO synthesis'), row('Not proven', 'A particular brief format guarantees article quality', 'Scope limitation')]),
    ],
    faqs: [{ q: 'Should every article start with a statistic?', a: 'No. It should start with a genuine niche question and use a statistic only when the source and scope make it relevant.' }, { q: 'Can the assistant choose the final thesis?', a: 'The assistant can propose and compare theses; an authorised editor should approve the public interpretation.' }],
    sources: src([
      { name: 'U.S. Government Publishing Office Style Manual', url: 'https://www.govinfo.gov/app/details/GPO-STYLEMANUAL-2016', note: 'Editorial treatment of clear, accurate public writing.' },
      { name: 'OECD Measuring Productivity', url: 'https://www.oecd.org/en/topics/sub-issues/measuring-productivity.html', note: 'Definitions and cautions for interpreting productivity evidence.' },
      { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework', note: 'Governance and risk-management concepts applied to role boundaries.' }
    ]), related: ['content-research-source-traceability', 'research-briefing-workflow', 'assistant-task-intake-design'], body: []
  },
  {
    slug: 'philippines-assistant-article-handoff-window',
    image: { url: '/images/research-2026-08-21/philippines-assistant-article-handoff-window.png', alt: 'Two remote workspaces connected through an article review handoff' },
    title: 'When does a Philippines-based assistant handoff actually extend article capacity?',
    excerpt: 'Research on the difference between overnight preparation and a genuinely covered review window in a daily publishing routine.',
    published: '2026-08-21', updated: '2026-08-21', cluster: 'Distributed work',
    headlineStat: 'A time-zone difference creates capacity only when prepared evidence reaches an authorised reviewer at a usable decision point.',
    methodology: 'Research question: what observable conditions distinguish a useful Philippines-based assistant handoff from work that simply waits for review? This analysis uses the ILO Working from Home report, OECD productivity measurement guidance, NIST governance concepts, and the UK Government Service Manual on measuring success. It studies state transitions and decision coverage for an outsourced article routine; it does not estimate a universal time-zone advantage, staffing ratio, or turnaround promise.',
    keyStats: ['Preparation hours and decision hours are different resources', 'A ready item needs a named reviewer and a defined review interval', 'Waiting reasons are more informative than a single turnaround number'],
    takeaways: ['Measure evidence-ready to authorised decision separately from draft creation.', 'Record whether an item waits for a person, source, clarification, or revision.', 'Treat an overnight draft as review-ready only when its unresolved decisions are visible.'],
    sections: [
      sec('Define capacity at the decision boundary', ['A daily article can arrive before the owner is available and still fail to create usable capacity. The assistant may have completed source collection and drafted a careful analysis, but the page remains unapproved if no authorised person can assess its claims. Capacity therefore has at least two components: preparation capacity and decision capacity. A handoff extends the first only when it connects to the second.', 'The ILO evidence is useful as context because remote work depends on organisation and working conditions, not geography alone. Applied locally, that means recording when an evidence packet became ready, when review could begin, and which decision ended the wait. The record can reveal a coordination issue without pretending that one team’s observation is a general workforce result.'], [row('Preparation capacity', 'Time and skill to collect evidence and draft', 'Queue-state analysis'), row('Decision capacity', 'Authorised time to approve, narrow, or return', 'NIST governance concepts')]),
      sec('Design an honest comparison', ['A comparison of handoff windows should keep the brief, source threshold, editorial rubric, topic difficulty, and exceptions visible. Compare periods with a scheduled review event against periods without one, but preserve the reason an item was delayed. If waiting falls after a review window is added, the evidence supports a coordination finding. It does not prove that the assistant became more capable or that all remote teams will see the same pattern.', 'The denominator matters. Include eligible article packets, state which items were cancelled or merged, and separate sensitive or unusually volatile topics when their review path differs. A number that combines all these populations can look precise while hiding the actual operating constraint.'], [row('Primary measure', 'Time from evidence-ready to authorised decision', 'UK Government measurement logic'), row('Required context', 'Topic, source volatility, exclusions, and return reason', 'Measurement-method analysis')]),
      sec('What a useful overnight packet contains', ['An assistant can refine the question, gather reputable sources, attach scope notes, draft a thesis, identify limitations, and list the decisions an editor must make. The packet should distinguish observed facts from analysis and hypothetical examples from company facts. Its purpose is to make the next review decision smaller and safer, not to imply that a finished-looking page is already approved.', 'The owner can then accept the bounded conclusion, narrow it, request another source, or stop the article. If the owner is unavailable, the accurate state is waiting for review. This language seems small, but it keeps the publishing rhythm honest: time-zone coverage supports preparation while accountability remains with the decision-maker.'], [row('Safe overnight output', 'Evidence packet, bounded draft, limitations, and questions', 'Role-boundary analysis'), row('Hard stop', 'Publication without authorised review', 'NIST governance frame')]),
      sec('Limitations and evidence-led conclusion', ['The public sources do not identify an ideal overlap duration, and this review does not isolate geography from topic difficulty, reviewer habits, or source volatility. A local sample can reveal recurring waits and clarify ownership, but it cannot support a universal performance promise. A difficult article may properly take longer because the evidence is weak or the consequences of error are higher.', 'The evidence-led conclusion is that a Philippines-based assistant extends daily article capacity when preparation is linked to a scheduled, authorised review event. The handoff should show what is complete, what is uncertain, and what decision is required. More working hours alone do not establish more publishing capacity.', 'A practical local test is to review comparable article packets and classify each waiting interval before changing the schedule. If the dominant wait is owner review, protect a decision window. If it is missing evidence, improve the brief. If it is revision, improve the rubric. This keeps the intervention tied to observed work rather than an assumption about geography.'], [row('Supported conclusion', 'Capacity includes preparation plus accountable review', 'ILO, OECD, NIST synthesis'), row('Not proven', 'A universal time-zone productivity advantage', 'Scope limitation')]),
    ],
    faqs: [{ q: 'Is an overnight draft publishable?', a: 'No. It is ready for the defined evidence and editorial review event.' }, { q: 'What should waiting time include?', a: 'The interval from evidence-ready to the first valid owner decision, with the reason for any pause.' }],
    sources: src([
      { name: 'UK Government Service Manual: Measuring Success', url: 'https://www.gov.uk/service-manual/measuring-success', note: 'Measurement questions, denominators, and interpretation limits.' },
      { name: 'ILO Working from Home Report', url: 'https://www.ilo.org/global/topics/non-standard-employment/publications/WCMS_765806/lang--en/index.htm', note: 'Evidence about how remote work is organised and experienced.' },
      { name: 'OECD Measuring Productivity', url: 'https://www.oecd.org/en/topics/sub-issues/measuring-productivity.html', note: 'Definitions and cautions for interpreting productivity evidence.' }
    ]), related: ['time-zone-handoff-design', 'review-window-coverage', 'handoff-state-transitions'], body: []
  },
  {
    slug: 'article-quality-sampling-for-outsourced-routines',
    image: { url: '/images/research-2026-08-21/article-quality-sampling-for-outsourced-routines.png', alt: 'Editor sampling distinct article evidence cards for quality review' },
    title: 'What can quality sampling reveal about an outsourced daily article routine?',
    excerpt: 'A research-led look at sampling claims, review dimensions, and the limits of judging article quality from a small queue.',
    published: '2026-08-21', updated: '2026-08-21', cluster: 'Quality systems',
    headlineStat: 'A sample is useful when its selection rule and review rubric are explicit; it is misleading when a clean subset stands in for the whole queue.',
    methodology: 'Research question: what can a small content owner safely learn by sampling articles prepared by an outsourced assistant? This desk review draws on the UK Government Service Manual, NIST measurement and governance material, the National Academies discussion of uncertainty, and the GPO Style Manual. It applies these principles to niche article review and does not calculate a universal quality rate or infer causality from a small sample.',
    keyStats: ['Selection rules affect what a sample can represent', 'Evidence fit, niche relevance, dates, and role boundaries are separate checks', 'A return reason is more actionable than an unexplained pass percentage'],
    takeaways: ['Define eligible, excluded, reopened, and sensitive items before sampling.', 'Review claims and reader usefulness separately from prose fluency.', 'Use findings to adjust the routine locally, not to promise a benchmark.'],
    sections: [
      sec('Choose the population before the sample', ['Sampling begins with a population definition. Is the owner reviewing every article prepared in a week, only articles that reached editorial review, or only pages published? Each choice answers a different question. A published-only sample may miss drafts returned for weak evidence. A first-pass sample may overstate readiness if reopened items disappear from view. Keep the eligibility and exclusion rules with the result.', 'The UK Government measurement guidance supports asking what decision a measure serves. In this context, the owner may want to know whether briefs are clear, whether source notes survive handoff, or whether public dates and links remain accurate. One sample need not answer all three. Separating them makes the review smaller and the corrective action more specific.'], [row('Population field', 'Eligible items, exclusions, reopenings, final disposition', 'UK Government measurement logic'), row('Interpretation limit', 'A clean-case sample is not a queue-wide rate', 'National Academies uncertainty')]),
      sec('Use a multidimensional rubric', ['A fluent article can fail because its sources do not support the thesis, its examples leave the outsourcing niche, or its conclusion turns context into a company claim. A useful rubric therefore separates evidence fit, scope accuracy, niche relevance, visible and structured dates, originality, readability, and role boundaries. The reviewer should record the observed issue and its consequence instead of assigning one intuitive score.', 'The rubric can still be lightweight. A small owner may mark each dimension pass, return, or not applicable, then add one sentence explaining the decision. The objective is not to create a false measurement of quality. It is to make disagreements discussable and show whether the next improvement belongs in intake, research, drafting, or review.'], [row('Evidence check', 'Source relevance, accurate representation, stated limitation', 'NIST and GPO framing'), row('Editorial check', 'Reader, niche, structure, dates, and public boundaries', 'Site-specific analysis')]),
      sec('Interpret returns as operating evidence', ['If sampled work repeatedly returns for broad questions, the intake may be under-specified. If sources are strong but dates or canonical identity drift, the review boundary may be incomplete. If examples become generic, the brief may not be keeping the outsourcing decision central. These are different findings, even if they all appear as “quality issues” in a dashboard.', 'Record the primary return reason and the next corrective action. A sample can show a pattern worth testing; it cannot show that one intervention caused a later improvement unless the comparison and confounders are defined. Preserve the original review observation so the owner can distinguish a real correction from a later rewrite that erased the reason for return.'], [row('Diagnostic', 'Return reason tied to a stage and corrective action', 'This review method'), row('Causal boundary', 'A local pattern is not proof of universal improvement', 'National Academies uncertainty')]),
      sec('Limitations and evidence-led conclusion', ['This review does not determine a statistically sufficient sample for every site, topic, or consequence level. High-risk or highly volatile subjects may need full review regardless of sample design. Reviewers can also disagree about niche relevance or whether analysis is sufficiently bounded. Those limits should be visible rather than hidden behind a single score.', 'The evidence-led conclusion is that sampling helps an outsourced article routine when the population, selection rule, rubric, and return reasons are explicit. It can show where preparation or review needs refinement. It cannot certify every article, establish a universal quality percentage, or replace an authorised editor’s decision about public copy.', 'The most useful sampling record is modest and repeatable: identify the eligible set, preserve why an item was selected, mark the dimension reviewed, and state the next change. Over time, it can show whether a failure mode recurs. It still should not be presented as a market benchmark or guarantee for readers outside the observed queue.'], [row('Supported conclusion', 'Explicit sampling makes local correction patterns visible', 'UK Government, NIST synthesis'), row('Not proven', 'A small sample certifies all future articles', 'Scope limitation')]),
    ],
    faqs: [{ q: 'Should every article be sampled?', a: 'Sampling is useful for routine review, but sensitive or unusually consequential topics may warrant full review.' }, { q: 'Is one score enough?', a: 'No. Separate evidence, relevance, dates, originality, and boundary checks so the correction is actionable.' }],
    sources: src([
      { name: 'UK Government Service Manual: Measuring Success', url: 'https://www.gov.uk/service-manual/measuring-success', note: 'Measurement design and honest interpretation.' },
      { name: 'National Academies: Communicating Science Effectively', url: 'https://nap.nationalacademies.org/catalog/23674/communicating-science-effectively', note: 'Uncertainty and interpretation boundaries.' },
      { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework', note: 'Governance and risk-management concepts applied to review controls.' }
    ]), related: ['assistant-quality-scorecard', 'assistant-quality-sampling-plan', 'queue-denominator-integrity'], body: []
  },
  {
    slug: 'outsourced-research-approval-boundary',
    image: { url: '/images/research-2026-08-21/outsourced-research-approval-boundary.png', alt: 'Owner and assistant reviewing a proposed research decision with a clear approval boundary' },
    title: 'Where should approval remain when an assistant prepares outsourced research?',
    excerpt: 'A role-boundary study of evidence collection, interpretation, and publication approval in recurring research-led article work.',
    published: '2026-08-21', updated: '2026-08-21', cluster: 'Role design',
    headlineStat: 'Delegating research preparation is different from delegating authority to turn uncertain evidence into a public commitment.',
    methodology: 'Research question: which decisions can a Philippines-based assistant prepare safely, and which should remain with an authorised owner when producing research articles? This analysis compares NIST governance and access principles, OECD measurement guidance, the GPO Style Manual, and ILO remote-work evidence. It concerns role boundaries in article preparation, not employment advice, legal advice, or a claim about the capabilities of any individual.',
    keyStats: ['Preparation can be delegated without transferring final interpretation', 'Authority should follow consequence, uncertainty, and reversibility', 'A clear escalation route is part of the work design'],
    takeaways: ['Let the assistant collect and annotate evidence inside a stated question.', 'Require owner review for company-specific claims, consequential interpretations, and publication approval.', 'Use proposed states and preserved evidence when authority or recovery is unclear.'],
    sections: [
      sec('Separate work from authority', ['An assistant can perform valuable research without owning the conclusion. Collecting primary sources, comparing definitions, drafting a source note, and identifying a limitation are preparation activities. Deciding that a claim applies to a company, promising an outcome, or publishing a consequential interpretation requires a different level of authority. Confusing the two makes a recurring task appear simpler than it is.', 'NIST governance concepts help frame this as an accountability question: who can make the decision, what evidence must be available, and how is the decision reviewed? The answer should be written into the article brief. A role boundary that exists only in a manager’s memory will fail during urgency, absence, or a time-zone handoff.'], [row('Preparation', 'Collect, compare, annotate, and propose', 'NIST governance frame'), row('Approval', 'Accept public interpretation and consequential claims', 'Role-boundary analysis')]),
      sec('Use consequence and reversibility', ['Not every article sentence carries the same consequence. A definition supported by an authoritative source is different from a claim about a customer, a business result, an employment decision, or a sensitive process. The owner should ask what happens if the interpretation is wrong, whether the public statement can be corrected cleanly, and who can authorise the correction. When the recovery path is uncertain, the assistant should preserve the proposal and escalate.', 'This does not mean every low-risk sentence needs a meeting. It means the review depth should follow the consequence and uncertainty of the claim. A clear matrix can let routine evidence notes move quickly while keeping high-impact interpretations with the owner. The matrix is a local control, not a universal legal or operational standard.'], [row('Routing inputs', 'Consequence, uncertainty, reversibility, required authority', 'NIST access and governance concepts'), row('Safe default', 'Prepare a proposal when recovery or authority is unclear', 'This review method')]),
      sec('Make escalation specific', ['“Ask if unsure” is too vague for a daily article queue. The brief should name hard stops: unsupported company facts, promises or testimonials, public rates or pricing claims, sensitive personal information, disputed source interpretations, and conclusions that exceed the evidence. It should also tell the assistant what to send with the escalation: the question, source links, relevant passages, proposed wording, limitation, and exact owner decision.', 'Specific escalation reduces both overreach and unnecessary interruption. The assistant can continue collecting bounded evidence while the owner decides a disputed interpretation. The owner can return a narrower question instead of rewriting an entire page. The result is a visible boundary that supports preparation without hiding where accountability changes hands.'], [row('Escalation packet', 'Question, sources, scope, proposed wording, limitation, decision needed', 'Research handoff design'), row('Hard stop', 'Unsupported or consequential public claim', 'NIST and GPO synthesis')]),
      sec('Limitations and evidence-led conclusion', ['The sources do not define a single correct division of labour for every content team. Topic risk, reviewer expertise, source volatility, and the cost of an error vary. This review also does not assess an individual assistant or provide a substitute for professional advice where a topic is regulated or high consequence.', 'The evidence-led conclusion is that outsourced research works best when preparation authority is explicit and publication authority remains with a named owner. A Philippines-based assistant can make the evidence easier to inspect, but repeated work does not itself create permission to decide. The safest boundary is visible in the brief, the handoff, and the final review.', 'The boundary should survive ordinary exceptions. If the owner is absent, the assistant can preserve sources and propose alternatives, but should not treat silence as approval. If the question changes, the record should show which authority and evidence assumptions changed. If sources conflict, the disagreement belongs in the escalation packet.', 'The same rule applies to a correction after publication. Preserve the original source note, identify the disputed sentence, and route the proposed change to the authorised owner. This lets the assistant contribute precise evidence without silently changing the public meaning of an article.'], [row('Supported conclusion', 'Clear authority boundaries make escalation and review more reliable', 'NIST, OECD, ILO synthesis'), row('Not proven', 'A role label alone guarantees safe delegation', 'Scope limitation')]),
    ],
    faqs: [{ q: 'Can an assistant write the conclusion?', a: 'The assistant can draft an evidence-led conclusion with limitations; an authorised owner should approve its public meaning.' }, { q: 'When should work stop?', a: 'Stop when evidence, authority, identity, or recovery is unclear and route the preserved work to the owner.' }],
    sources: src([
      { name: 'U.S. Government Publishing Office Style Manual', url: 'https://www.govinfo.gov/app/details/GPO-STYLEMANUAL-2016', note: 'Clear and accurate public communication.' },
      { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework', note: 'Governance and access principles applied to approval boundaries.' },
      { name: 'OECD Measuring Productivity', url: 'https://www.oecd.org/en/topics/sub-issues/measuring-productivity.html', note: 'Definitions and cautions for interpreting evidence and outcomes.' }
    ]), related: ['reversible-action-boundaries', 'sensitive-case-segmentation', 'research-claim-review-queue'], body: []
  },
  {
    slug: 'source-freshness-for-daily-outsourced-articles',
    image: { url: '/images/research-2026-08-21/source-freshness-for-daily-outsourced-articles.png', alt: 'Reviewer comparing source dates and article update notes' },
    title: 'How should daily outsourced articles handle source freshness?',
    excerpt: 'Research on matching source recency to the claim, topic volatility, and the review decision rather than treating every newer page as stronger evidence.',
    published: '2026-08-21', updated: '2026-08-21', cluster: 'Evidence quality',
    headlineStat: 'Freshness is a property of the claim, population, jurisdiction, and decision—not a substitute for source quality.',
    methodology: 'Research question: how should a daily article routine decide whether a source is current enough for its claim? This desk review uses NIST governance guidance, OECD measurement definitions, the GPO Style Manual, and ILO remote-work research. It distinguishes a source’s publication or update date from the period it observed and applies the distinction to OutsourcingAssistant.com research articles. It does not give legal, regulatory, or market advice and does not claim that a newer source is always more reliable.',
    keyStats: ['Publication date and observation period answer different questions', 'Freshness should be matched to topic volatility and consequence', 'A current commentary page may still be weaker than an older primary source'],
    takeaways: ['Record source date, update date, observation period, and jurisdiction.', 'Ask whether the source is current enough for the exact sentence.', 'Keep a review trigger for claims that can change rather than implying permanent validity.'],
    sections: [
      sec('Define what “current” means', ['A page updated yesterday may describe data collected years ago. An older standard may remain the controlling reference for a stable concept. A current commentary page may summarize a claim without showing its method. These differences matter in a daily article because the date on a link can create false confidence if the researcher does not record what the source actually observed.', 'The article brief should distinguish publication date, update date, observation period, jurisdiction, population, and source class. The assistant can collect those fields and flag a mismatch. The editor can decide whether the mismatch changes the wording, requires a newer authority, or belongs in the limitations section.'], [row('Freshness record', 'Publication, update, observation, jurisdiction, population', 'OECD and GPO framing'), row('Common error', 'Treating a recent page as evidence of a recent observation', 'This review method')]),
      sec('Match freshness to the decision', ['A durable explanation of a role boundary may not need the same review cadence as a statement about a changing rule, product feature, or public benchmark. The relevant test is whether the claim could change in a way that would alter the reader’s decision. If so, the brief should identify a current primary source and a recheck trigger. If not, the researcher can explain why an older source still fits.', 'This is not an argument for replacing every source daily. Excessive freshness work can crowd out source quality and substantive analysis. It is an argument for making the tradeoff visible. A source packet can state: current enough for this claim because the concept is stable; or currentness unresolved because the decision is time-sensitive.'], [row('Decision test', 'Could a change alter the reader’s decision?', 'NIST risk framing'), row('Review trigger', 'A stated event, update, or volatility condition', 'Evidence-boundary analysis')]),
      sec('Keep context separate from a local claim', ['A study of remote-work conditions can inform context about distributed handoffs, but it cannot establish how one owner’s article queue performs. A productivity definition can explain what an output measure means, but it cannot certify an outsourcing result. Source freshness does not remove this scope boundary. The sentence must still stay inside the population and method the source supports.', 'The assistant should mark the transfer from source fact to local analysis. That lets the editor narrow an overbroad sentence without discarding useful research. It also gives future reviewers a way to tell whether a later update changes the underlying evidence or only the surrounding interpretation.'], [row('Source fact', 'What the authority directly reports within its scope', 'Source review'), row('Local analysis', 'A bounded implication for an article routine', 'Editorial interpretation')]),
      sec('Limitations and evidence-led conclusion', ['This review does not establish a universal recency window and cannot predict every topic’s volatility. Sources can change without clear notices, definitions can be revised, and a current page can still have weak evidence. A reviewer may need professional or legal guidance for high-consequence subjects. The article should disclose those limitations instead of using a date as a confidence score.', 'The evidence-led conclusion is that daily outsourced articles should treat freshness as claim-dependent. Record the source’s dates and scope, match review effort to consequence and volatility, and keep the owner’s decision about current public wording. A Philippines-based assistant can maintain that evidence record; an authorised editor should decide whether it is sufficient to publish.', 'A dated source note is also useful after publication. When a source changes, the owner can identify which sentence depended on it and decide whether the article needs correction, clarification, or no change. This is more precise than refreshing every link on a fixed schedule and respects the difference between a stable explanation and a claim that can move.'], [row('Supported conclusion', 'Claim-specific freshness checks reduce date-related overreach', 'NIST, OECD, ILO synthesis'), row('Not proven', 'A newer source is automatically stronger', 'Scope limitation')]),
    ],
    faqs: [{ q: 'Is the newest source always best?', a: 'No. Relevance, method, authority, population, and scope still matter.' }, { q: 'What should an assistant record?', a: 'Publication and update dates, observation period, jurisdiction, population, claim supported, and the reason the source is current enough.' }],
    sources: src([
      { name: 'U.S. Government Publishing Office Style Manual', url: 'https://www.govinfo.gov/app/details/GPO-STYLEMANUAL-2016', note: 'Accurate, bounded public writing.' },
      { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework', note: 'Risk and governance concepts applied to freshness decisions.' },
      { name: 'OECD Measuring Productivity', url: 'https://www.oecd.org/en/topics/sub-issues/measuring-productivity.html', note: 'Definitions and cautions for interpreting dated evidence.' }
    ]), related: ['source-recency-interpretation', 'claim-scope-provenance', 'content-research-source-traceability'], body: []
  },
];

export const researchBatch20260821: readonly ResearchPost[] = records;
