import type { ResearchPost, ResearchSource } from './fleet-content';

const checked = 'Checked October 5, 2026.';
const governanceSources: readonly ResearchSource[] = [
  { name: 'U.S. GAO, Assessing Data Reliability', url: 'https://www.gao.gov/products/gao-20-283g', note: `Primary audit-method guidance on accuracy, completeness, applicability, risk, corroboration, and documented judgment. ${checked}` },
  { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework', note: `Primary governance framework used for roles, oversight, protection, response, recovery, and supplier-risk reasoning. ${checked}` },
  { name: 'NIST SP 800-53 Rev. 5', url: 'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final', note: `Primary control catalogue used for least privilege, account management, audit records, separation of duties, and external services. ${checked}` },
];
const accessibilitySources: readonly ResearchSource[] = [
  { name: 'W3C, Web Content Accessibility Guidelines (WCAG) 2.2', url: 'https://www.w3.org/TR/WCAG22/', note: `Normative W3C Recommendation used to define testable web-content accessibility outcomes; it does not by itself certify a particular document or determine a buyer's legal obligations. ${checked}` },
  { name: 'W3C WAI, Understanding WCAG 2.2', url: 'https://www.w3.org/WAI/WCAG22/understanding/', note: `Informative explanations used to plan review examples while keeping the normative success criteria distinct. ${checked}` },
  ...governanceSources,
];

export const researchBatch20261005: readonly ResearchPost[] = [
  {
    slug: 'delegated-document-accessibility-acceptance-sample',
    title: 'How should a buyer sample accessibility in assistant-prepared documents?',
    excerpt: 'A document-level acceptance study that separates source accuracy, semantic structure, visual review, assistive-technology checks, and owner approval.',
    published: '2026-10-05', updated: '2026-10-05', cluster: 'Document production research',
    image: { url: '/illustrations/getillustrations/goodle-team/assistant-handoff-collaboration.svg', alt: 'Owner and assistant reviewing a document acceptance checklist together' },
    headlineStat: 'Accessibility acceptance needs a declared document population, testable criteria, retained failures, and a named decision owner; a clean visual preview is not sufficient evidence.',
    methodology: 'This protocol applies WCAG 2.2 concepts, W3C explanatory material, GAO data-reliability questions, and NIST governance controls to a bounded sample of assistant-prepared digital documents. It is an operating study, not a conformance certification or legal opinion. The unit is one final-format document linked to its approved source, template, conversion route, manual checks, assistive-technology observations, exceptions, reviewer, and disposition.',
    keyStats: ['Population: every final-format document in one declared production lane, including corrected and rejected files.', 'Evidence: source file, exported artifact, test record, issue log, repair evidence, and owner decision remain linked.', 'Decision: accept, repair, replace, narrow the supported format, seek specialist review, or stop delivery.'],
    takeaways: ['Sample by document risk and feature, not convenience or appearance.', 'Automated checks find some conditions but do not replace reading order, meaning, keyboard, or user-context review.', 'The document owner sets the required standard and accepts residual risk; the assistant records and repairs within written authority.'],
    sources: accessibilitySources, related: ['document-production-version-control-acceptance-test', 'assistant-quality-sampling-plan', 'sourced-brief-acceptance'],
    body: ['one document and its source lineage', 'semantic and visual inspection', 'assistive-technology observation', 'feature-stratified sampling', 'owner acceptance and retained exceptions'],
    sections: [
      { heading: 'Define the artifact before testing it', rows: [], paragraphs: [
        'A buyer first needs to say what is being accepted. An editable word-processing file, a tagged PDF, a web page, and a slide deck expose different structures and controls. The production brief should name the final format, intended distribution channel, audience, required standard, supported viewing tools, and any approved alternative. If the assistant reviews the source file while recipients receive a converted PDF, the study has tested the wrong artifact. Keep the exported file and its source version together so a later correction can be reproduced.',
        'The document inventory should describe features that can change the test: headings, tables, forms, links, images, charts, footnotes, columns, language changes, headers, and reading order. A five-page text memo is not equivalent to a two-page form. Sampling only the simplest files can create reassuring percentages while excluding the documents most likely to contain barriers. Stratification makes the claim modest and useful: the observed sample covered stated feature classes, not every possible reader, tool, or document.',
        'Acceptance criteria must be written before results are known. WCAG provides testable web-content outcomes, while its Understanding material is informative rather than normative. A business may choose a relevant standard or specialist protocol for its document format. The assistant can map checks to that approved rule and preserve evidence. The owner or qualified reviewer decides whether the rule is appropriate, whether an alternate format is acceptable, and whether a consequential exception can be released.'
      ]},
      { heading: 'Build a feature-stratified sample', rows: [], paragraphs: [
        'Start with a complete release list for a fixed period. Tag each file by template, final format, length band, feature set, conversion method, novelty, and consequence if information is missed. Include every first use of a template and every known conversion failure, then draw ordinary examples from the remaining groups. This design deliberately overrepresents risky work, so its issue rate cannot be reported as the rate for all documents. It does, however, help a buyer decide where stronger gates or specialist review are warranted.',
        'Retain failures, withdrawals, and repairs in the denominator. Removing a file after a problem is found turns the sample into a display of survivors. Record the original result, issue class, who decided the remedy, corrected artifact, and retest. If a deadline causes a document to be replaced with an accessible web page or plain-text version, that is an operational outcome rather than a passing result for the original file. The distinction protects both readers and the integrity of later improvement claims.',
        'Reviewer agreement can be measured on a small overlapping subset. Two reviewers independently apply the same criteria, then discuss differences such as whether a heading communicates structure, whether link text has enough context, or whether a table linearises meaningfully. Disagreement is not automatically reviewer error. It may reveal an ambiguous rubric, a tool limitation, or a genuinely contextual judgment. Preserve the initial decisions and resolution instead of editing the record until reviewers appear to agree.'
      ]},
      { heading: 'Test structure, meaning, and use', rows: [], paragraphs: [
        'A visual inspection begins the work but cannot finish it. Check whether headings are encoded as headings, lists as lists, tables with the relationships needed for interpretation, and the document language is identified. Inspect reading order after conversion rather than assuming the source application preserved it. Images need alternatives that serve their actual purpose; decorative graphics should not create noise. A chart description must communicate the decision-relevant pattern without inventing precision that the chart itself does not support.',
        'Interaction requires its own pass. Follow links from meaningful labels, move through controls in a logical order, confirm that focus is visible where the format supports interaction, and inspect fields for names, instructions, errors, and status changes. A mouse-only success does not show keyboard access. An exported form that looks correct but loses labels is a failed conversion. Record the tool, version, settings, and exact step so another reviewer can reproduce what happened rather than relying on a generic checked box.',
        'Assistive-technology observation should answer a bounded question. For example: can a reviewer using the organisation’s supported screen reader identify the title, navigate headings, understand a sample table, reach each link, and complete a representative field? That observation is valuable but does not prove usability for every person, device, setting, or disability. Where the document is high consequence or the format is novel, include qualified accessibility review or user research instead of stretching an assistant sample into a certification claim.'
      ]},
      { heading: 'Separate repair authority from release authority', rows: [], paragraphs: [
        'The assistant can often repair known mechanical defects: apply an approved heading style, remove empty paragraphs used for spacing, replace an ambiguous link label, enter approved alternative text, or repeat an export using documented settings. Content meaning, reading sequence, mathematical notation, complex tables, legal notices, and material alternatives may require the author or specialist. The issue record should state which role owns the next decision. Repetition does not grant authority to resolve an ambiguous meaning.',
        'A repair is complete only after the final artifact is retested. Correcting the source without regenerating the deliverable leaves conversion risk unexamined. Keep the failed artifact where retention rules permit, create the corrected version under a new version identifier, repeat the relevant checks, and document the result. If the fix alters wording or meaning, route it through editorial approval as well. Accessibility review is not permission to silently rewrite an approved statement.',
        'Release status should communicate evidence, not optimism. Useful states include not tested, tested with stated scope, repair pending, specialist review required, alternate provided, accepted with an owner-approved exception, and rejected. Avoid a single green accessibility field that hides the standard, artifact, date, reviewer, and unresolved issue. The buyer should be able to trace exactly why a file was delivered and which questions remain open.'
      ]},
      { heading: 'Interpret the result without overclaiming', rows: [], paragraphs: [
        'Report coverage first: how many eligible files existed, how many were sampled in each feature class, which checks were applied, which tools were used, and what could not be tested. Then report findings by issue type and consequence, with repaired and unresolved results separated. A high pass share from plain memos says little about complex forms. A small number of serious reading-order failures may justify a process change even when most sampled checks passed.',
        'The study cannot establish legal compliance, universal usability, or the accessibility skill of an individual worker. It can show whether a declared production lane preserves required evidence and catches specified defects under stated conditions. Tool updates, template changes, new conversion services, and changes in the document population all limit comparison over time. Re-run the sample when those conditions change and keep the earlier record rather than presenting a moving process as one continuous benchmark.',
        'For a buyer, the practical outcome is a narrower and safer delegation decision. Routine structure checks and documented repairs may fit an assistant lane when examples and escalation rules are clear. Complex or consequential artifacts can be routed to qualified review. The owner retains responsibility for the standard, distribution decision, exceptions, and response when a recipient reports a barrier. That boundary makes assistant support useful without turning a checklist into unsupported assurance.'
      ]},
    ],
    serviceHandoff: { heading: 'Apply the protocol to document production', href: '/services/document-production', label: 'document production service', paragraphs: ['Use this evidence model when scoping a document production service, while keeping standard selection, specialist interpretation, and final release with the named owner.'] },
    faqs: [{ q: 'Does an automated accessibility score prove acceptance?', a: 'No. It can support a declared check, but structure, meaning, reading order, interaction, context, and unresolved exceptions still require appropriate review.' }, { q: 'Who approves an exception?', a: 'The document owner or qualified reviewer named in the policy, not the assistant merely because the deadline is close.' }],
  },
  {
    slug: 'project-status-source-conflict-resolution-study', title: 'Resolving source conflicts in assistant-prepared project status reports',
    excerpt: 'A status-claim protocol for deciding what to report when schedules, task systems, owner updates, and delivery evidence disagree.',
    published: '2026-10-05', updated: '2026-10-05', cluster: 'Project administration research',
    image: { url: '/illustrations/getillustrations/goodle-team/assistant-handoff-collaboration.svg', alt: 'Project owner comparing status evidence with an assistant' },
    headlineStat: 'A project status is a dated claim supported by identified evidence, not a colour copied from whichever system was updated last.',
    methodology: 'A prospective study of one reporting cycle. Each material status claim is linked to its governing milestone definition, source records, source timestamps, conflict note, owner response, published wording, and later correction. GAO data-reliability guidance frames accuracy, completeness, and applicability; NIST governance concepts frame role ownership and retained evidence. The method diagnoses reporting reliability, not team performance or delivery probability.',
    keyStats: ['Observation unit: one material status claim for a milestone, dependency, risk, decision, or deliverable.', 'Conflict classes: definition, timestamp, scope, ownership, completion evidence, dependency, or unauthorised override.', 'Outcome: supported, qualified, awaiting owner decision, superseded, corrected, or omitted with reason.'],
    takeaways: ['The newest timestamp is not automatically the most authoritative source.', 'Contradictions stay visible until a named owner resolves or qualifies them.', 'A report can be on time and still be incomplete if consequential uncertainty is hidden.'],
    sources: governanceSources, related: ['project-dependency-register-delegation-study', 'handoff-state-transitions', 'approval-dependency-latency'],
    body: ['status claim provenance', 'conflict register', 'cutoff discipline', 'owner qualification', 'correction trail'],
    sections: [
      { heading: 'Treat status as a claim with a cutoff', rows: [], paragraphs: [
        'Begin by defining the reporting cutoff and time zone. A dashboard observed at 16:00, an owner message sent at 16:20, and a deployment event at 17:10 describe different moments. The assistant should not merge them into a timeless present. Each report line needs an as-of time, governing definition, and evidence route. Late evidence can be included in a clearly labelled update or next report; quietly blending it into an earlier snapshot makes the record impossible to reproduce.',
        'A status word must point to a finish condition. “Complete” might mean code written, internal review passed, customer accepted, invoice approved, or production released. Capture the milestone definition approved for this project and compare evidence with that definition. A task-system checkbox is useful only if the person closing it had the authority and evidence the definition requires. When no definition exists, the assistant can expose the gap, but the project owner must decide what completion means.',
        'The study population should include ordinary green items as well as delayed, disputed, reopened, and cancelled work. Sampling only escalations exaggerates conflict; sampling only closed work hides it. Follow a fixed set of status claims from initial preparation through owner review and later outcome. That permits useful questions: which source conflicts recur, which qualifications survive publication, and which report statements later need correction.'
      ]},
      { heading: 'Classify why records disagree', rows: [], paragraphs: [
        'Some differences are temporal rather than contradictory. A weekly plan may remain accurate for its issue date while a live task record reflects later change. Other differences come from scope: a vendor says its component shipped while the internal milestone requires installation and acceptance. Record both scopes before choosing language. The assistant should not force agreement by replacing the narrower statement with the broader one.',
        'Ownership conflicts require special care. A contributor may report work ready, a reviewer may report changes required, and a sponsor may change the objective. These statements can all be authentic while only one role controls the published milestone state. The authority map should identify who can accept completion, change scope, acknowledge a risk, or approve a recovery forecast. If the map is absent, the report says awaiting owner decision rather than inferring authority from seniority or confidence.',
        'Evidence can also conflict in quality. A screenshot may show an interface state but omit account, environment, or time. A chat message may be current but lack the underlying delivery event. A system export may be complete yet use a field that does not apply to the milestone decision. Following GAO’s framing, assess accuracy, completeness, and applicability for this report purpose. Authority and recency matter, but neither rescues evidence that answers a different question.'
      ]},
      { heading: 'Write a conflict note the owner can decide', rows: [], paragraphs: [
        'A useful conflict note is short but specific: claim proposed, sources compared, exact difference, material consequence, information still needed, deadline, and named decision owner. Attach stable links or identifiers rather than pasting sensitive records into a broad report. The assistant can recommend neutral wording such as “implementation reported complete; acceptance evidence pending.” That preserves progress without claiming the unverified state.',
        'Avoid averaging unlike evidence into a colour. One severe dependency does not become amber because four routine subtasks are green. Conversely, one stale task should not make an otherwise evidenced milestone red if it no longer controls delivery. Keep milestone state, confidence in evidence, dependency exposure, and decision age as separate fields. The owner can then decide which combination drives executive reporting.',
        'Silence is not confirmation. If the decision owner does not respond before cutoff, publish the supported portion with the unresolved qualification when policy permits, or omit the claim and name the pending decision. Do not copy the previous week’s status as if it were freshly verified. Carry-forward statements should retain their original evidence date and a revalidation flag.'
      ]},
      { heading: 'Test the workflow against hard cases', rows: [], paragraphs: [
        'Construct a review set containing a completed deliverable without acceptance, an accepted deliverable with an outdated task field, a dependency reported differently by two owners, a scope change after cutoff, and a reopened milestone. Ask two reviewers to prepare the status independently under the same rules. Compare not just colours but cited evidence, qualification, owner, and next action. Preserve disagreement so the rubric can be improved.',
        'Run the first prospective cycles in recommendation-only mode. The assistant prepares claims and conflict notes, while the project owner approves every material state. Expand only stable low-consequence classes after the owner sees accurate evidence capture and reliable escalation. Changes to customer commitments, spend, contracts, safety, access, or public statements remain with authorised roles even if the reporting process becomes routine.',
        'Later outcomes provide a correction test, not perfect ground truth. If a milestone described as accepted is reopened because the acceptance record was wrong, link the correction. If new scope arrives later, do not rewrite the earlier report as false. Classify whether the original claim lacked evidence, exceeded its scope, or was accurate at cutoff and later superseded.'
      ]},
      { heading: 'Report reliability without ranking people', rows: [], paragraphs: [
        'Summarise the number of eligible claims, conflicts by class, decisions received before cutoff, qualifications published, carried-forward items, and corrections. Show distributions and examples rather than a universal conflict rate. A rise may reflect better detection, a more volatile project, or weaker source discipline. It does not by itself prove an assistant, owner, or team became less reliable.',
        'Limitations include private decisions not captured in the authorised record, inconsistent system clocks, changing milestone definitions, and reviewers who know the eventual outcome. A single project cannot establish a benchmark for another organisation. The study supports local workflow design: which sources deserve priority for which claims, which owners must be available, and which states need explicit qualification.',
        'The buyer’s decision is whether an assistant can prepare a traceable status packet without being asked to settle disputes or promise delivery. A strong lane reduces reconstruction work because evidence and uncertainty arrive together. The project owner keeps control of definitions, consequence, commitments, corrections, and release. That division is more defensible than judging the service by report punctuality or the number of green items.'
      ]},
    ],
    serviceHandoff: { heading: 'Use conflict evidence in project support', href: '/services/project-administration', label: 'project administration service', paragraphs: ['A project administration service can prepare source-linked status claims and conflict notes; milestone acceptance, commitments, and published interpretation remain with the project owner.'] },
    faqs: [{ q: 'Should the newest source always win?', a: 'No. Its scope, authority, accuracy, completeness, and applicability to the defined milestone still need review.' }, { q: 'What if the owner misses cutoff?', a: 'Publish only supported wording under the approved rule, retain the unresolved qualification, or omit the claim; do not infer approval.' }],
  },
  {
    slug: 'executive-support-purchase-request-verification-study', title: 'Verifying purchase requests in delegated personal executive support',
    excerpt: 'A request-level study of identity, purpose, budget, vendor, payment boundary, delivery details, approval, and evidence without giving an assistant spending authority.',
    published: '2026-10-05', updated: '2026-10-05', cluster: 'Personal executive support research',
    image: { url: '/illustrations/getillustrations/goodle-team/assistant-handoff-collaboration.svg', alt: 'Executive and assistant reviewing a purchase request and approval record' },
    headlineStat: 'Convenience work becomes consequential when it changes money, identity, delivery location, recurring terms, or an external commitment.',
    methodology: 'A request-level pilot compares the original instruction, approved vendor route, item specification, price observation, terms, identity verification, budget rule, approval event, order evidence, receipt, exception, and correction. NIST control concepts support least privilege and separation of duties; GAO reliability questions frame source fitness. This is not financial, fraud, legal, tax, or procurement advice.',
    keyStats: ['Unit: one requested purchase or reservation from intake through verified disposition.', 'Hard boundary: research and preparation do not equal permission to spend, enrol, subscribe, or disclose personal information.', 'Sample: routine, changed, urgent, recurring, high-value, failed-delivery, refund, and suspected-impersonation cases.'],
    takeaways: ['Verify the instruction and material change through an approved channel.', 'Show total cost and terms at approval time; do not hide renewal, cancellation, return, or delivery constraints.', 'Keep payment credentials out of broad notes and require a named owner for purchase and exception decisions.'],
    sources: governanceSources, related: ['personal-executive-support-privacy-boundary-test', 'access-purpose-evidence', 'vendor-verification-checklist'],
    body: ['instruction identity', 'purchase packet', 'approval snapshot', 'payment boundary', 'receipt and exception evidence'],
    sections: [
      { heading: 'Draw the boundary at commitment', rows: [], paragraphs: [
        'Personal support requests often sound harmless: send a gift, replace an item, reserve a table, renew a membership, or arrange a household service. Each can expose money, location, relationships, preferences, or recurring obligations. The intake should separate research, cart or draft preparation, approval, purchase, and post-purchase follow-up. An assistant who may compare options does not automatically have authority to place an order.',
        'Write the authority rule in observable terms. It should name permitted categories, maximum amount if any, approved payment route, vendors or verification method, delivery constraints, prohibited data, and events that require fresh approval. A verbal “use your judgment” is not enough for a repeatable lane. The executive or authorised manager decides whether any standing authority exists and can revoke it without waiting for a routine review.',
        'Treat material changes as new decisions. A substituted item, higher total, different seller, recurring plan, changed delivery address, nonrefundable term, or request for identity documents can reverse the original choice. The assistant preserves the approved snapshot and sends a concise change note. Urgency, familiarity, or a prior similar purchase does not make the new condition approved.'
      ]},
      { heading: 'Verify who asked and what they meant', rows: [], paragraphs: [
        'The study records the request channel, verified requester, exact item or outcome, recipient, occasion where relevant, deadline, privacy class, and approval route. A display name, forwarded message, or text from an unfamiliar number should not be treated as identity proof. The organisation should define an independent channel for unusual, urgent, secret, payment-changing, or credential-seeking requests.',
        'Clarify specifications that change suitability: model, size, quantity, compatibility, dietary need, accessibility need, colour only when material, delivery window, gift message, and acceptable alternatives. The assistant should not fill sensitive gaps by searching private records outside the task purpose. Ask only for the minimum information needed, and place it in the approved system rather than a reusable personal profile by default.',
        'Purpose matters because the same item can follow different rules. A routine office replacement, personal gift, regulated product, subscription, and service at a home address have different consequences. Tagging purpose is not permission to infer a legal or tax category. Route uncertain or specialist questions to the owner and record that the purchase packet does not answer them.'
      ]},
      { heading: 'Prepare a decision-ready purchase packet', rows: [], paragraphs: [
        'Use the official or approved vendor route where possible. Capture seller identity, product or service identifier, quantity, total shown cost, currency, taxes or fees known at the time, delivery estimate, return or cancellation terms, renewal terms, warranty source, and check time. Label estimates and exclusions. A search-card price is not the checkout total, and a marketplace listing does not prove the seller is authorised.',
        'Comparisons should preserve trade-offs instead of collapsing them into “best.” A cheaper option may have an uncertain seller, slower delivery, restrictive return rule, different specification, or automatic renewal. The assistant can organise these differences and flag the owner’s stated priorities. The executive decides which compromise is acceptable. Do not invent a preference from past behaviour when the current purchase has a different recipient or consequence.',
        'The approval view should be stable enough to audit. Record the selected option, total, material terms, delivery destination in a privacy-safe form, and approval timestamp. If the checkout changes afterward, pause. Screenshots may supplement the record but can expose personal details and may omit interactive terms; retain only what policy permits and link to the underlying order evidence.'
      ]},
      { heading: 'Separate payment, ordering, and receipt', rows: [], paragraphs: [
        'Least privilege means the assistant sees only the information needed for the approved step. A tokenised delegated method or owner-completed checkout is preferable to copying card details into chat. Account recovery, new payees, bank changes, one-time codes, and requests to move outside the approved platform require the organisation’s security process. The research protocol does not declare any channel safe; it checks whether the declared controls were followed.',
        'After an authorised order, retain confirmation number, seller, amount, expected delivery, permitted recipient view, and who owns follow-up. A confirmation page is evidence of submission, not receipt or suitability. Track shipment only through approved routes. A message asking for an additional fee, changed address, or new payment link is an exception, not a continuation that the assistant may accept automatically.',
        'Receipt closes the operational loop only when the finish rule is met. Delivery may require confirmation by the recipient, installation, return-window review, or correction of damage. Gift privacy may limit what can be recorded. The assistant can prepare a discrepancy packet with order facts, policy terms, and approved contact route; refund, dispute, replacement, or concession decisions remain with the named owner.'
      ]},
      { heading: 'Pilot with reversibility and honest measures', rows: [], paragraphs: [
        'Begin in preparation-only mode using historical or simulated cases. Include an ordinary reorder, a price increase, a subscription default, an unfamiliar seller, a changed delivery address, a request apparently from the executive on a new channel, and a failed delivery. Score whether the packet caught the material change, protected sensitive data, named the decision owner, and stopped before unauthorised commitment.',
        'If live scope expands, use low-consequence categories, explicit limits, transaction alerts, retained receipts, rapid access removal, and periodic review. Sample all exceptions plus ordinary cases. Do not judge the lane by dollars spent, orders placed, or speed alone. Those measures can reward unnecessary buying or rushed verification. Measure evidence completeness, correct pauses, owner-confirmed outcomes, and correction handling.',
        'The pilot cannot prove that fraud will be prevented or every purchase will satisfy its recipient. It can show whether a defined lane preserves instruction, terms, approval, and outcome without hidden authority. The buyer can then decide which preparation tasks save time, which commitments remain owner-completed, and which categories are too sensitive. That is a safer outcome than treating personal support as unrestricted access justified by convenience.'
      ]},
    ],
    serviceHandoff: { heading: 'Scope personal executive support carefully', href: '/services/personal-executive-support', label: 'personal executive support service', paragraphs: ['Use the verification and approval fields when defining a personal executive support service; the executive retains spending, identity, privacy, and exception decisions.'] },
    faqs: [{ q: 'Does preparing a cart authorise checkout?', a: 'No. Preparation and financial commitment are separate states unless a written, limited authority rule explicitly says otherwise.' }, { q: 'What requires fresh approval?', a: 'Any material change such as seller, total, subscription, item, delivery destination, payment route, or restrictive term.' }],
  },
  {
    slug: 'shared-inbox-thread-context-loss-study', title: 'Measuring context loss in delegated shared-inbox threads',
    excerpt: 'A thread-level study of missing history, attachments, identity, prior commitments, channel changes, and draft safety before an assistant replies.',
    published: '2026-10-05', updated: '2026-10-05', cluster: 'Inbox operations research',
    image: { url: '/illustrations/getillustrations/goodle-team/assistant-handoff-collaboration.svg', alt: 'Assistant and mailbox owner reviewing a message thread with supporting records' },
    headlineStat: 'A current message can be readable yet unsafe to answer when its identity, prior promise, attachment, side-channel decision, or governing record is missing.',
    methodology: 'Review a consecutive set of shared-inbox threads from intake through approved disposition. Reconstruct the evidence available at drafting time and compare it with the final authorised record. NIST governance, access, and audit concepts support role and logging controls; GAO reliability concepts support completeness and applicability checks. No private message content is published, and the protocol does not determine legal, privacy, security, or customer-remedy outcomes.',
    keyStats: ['Unit: one reply decision linked to the complete authorised thread and relevant source record.', 'Loss types: identity, earlier promise, attachment, quoted-text truncation, side channel, recipient scope, policy version, ownership, or time.', 'Disposition: safe draft, approved template, clarification, verification, specialist route, owner decision, or no reply.'],
    takeaways: ['Summaries help navigation but cannot silently replace the underlying thread.', 'A reply must be checked against prior commitments and the current source of truth.', 'High-consequence ambiguity stops the send path even when a draft sounds plausible.'],
    sources: governanceSources, related: ['shared-inbox-delegation-control-study', 'executive-inbox-delegation-readiness-test', 'inbox-template-drift-detection-study'],
    body: ['thread reconstruction', 'commitment extraction', 'identity and recipients', 'draft evidence', 'safe escalation'],
    sections: [
      { heading: 'Define context loss from the decision backward', rows: [], paragraphs: [
        'Do not count missing words; ask whether omitted information could change the permitted reply. A hidden earlier promise, a corrected attachment, a changed account owner, or a recipient added later may be material even when most of the conversation is visible. For each sampled thread, define the decision the reply would make and identify the minimum records needed to support it.',
        'The authorised context may extend beyond email. A case system can contain the accepted remedy, a CRM can identify the account relationship, a calendar can show the approved time, and an internal decision log can supersede discussion in the thread. The assistant should use only approved systems within task purpose. The study records which source was required and available; it does not reward broad searching through unrelated personal or company data.',
        'Choose a consecutive sample that includes replies, drafts returned for clarification, transfers, no-response dispositions, reopened threads, and known exceptions. Preserve the state visible when the assistant worked. Later evidence can explain the outcome but should not be used to pretend the original draft had information that arrived afterward.'
      ]},
      { heading: 'Reconstruct identity, audience, and chronology', rows: [], paragraphs: [
        'Start with sender and recipient identity rather than display names. Record the account, approved contacts, aliases, forwarding route, and any verification state required by the lane. A legitimate-looking domain or familiar signature is not sufficient for consequential changes. If a message requests credentials, payment changes, sensitive disclosure, secrecy, or unusual urgency, route it through the organisation’s security procedure.',
        'Build a chronology of requests, facts, promises, approvals, corrections, and unresolved questions. Quoted text can be incomplete, reordered, or stripped of attachments. A long thread may also contain two separate issues whose owners differ. The assistant marks each claim with its source event instead of producing one smooth summary that erases disagreement or turns a proposal into a commitment.',
        'Audience changes can alter what may be said. A draft suitable for an internal owner may expose personal data or candid assessment when an external recipient is added. Reply-all, forwarding, and shared links need their own check. The mailbox rule should state who can approve recipient changes and what information must be removed or replaced with a secure route.'
      ]},
      { heading: 'Test summaries against the source thread', rows: [], paragraphs: [
        'Summaries are useful for review when they are treated as indexes. A thread brief can list current request, confirmed facts, prior commitments, disputed points, sensitive elements, governing record, proposed reply, and owner. Each material item should lead back to the source. If the summary omits an unresolved contradiction, it has changed the decision rather than merely shortened the reading.',
        'Have a second reviewer answer the proposed reply question from the brief, then inspect the full authorised context. Record whether the decision, qualification, recipient set, or escalation changes. This is a practical context-loss test. It does not claim that every difference is an error: reviewers may exercise legitimate judgment, and the full thread can itself be incomplete.',
        'Attachments need explicit status. Record filename, version, sender, received time, scan or handling state under policy, and how it supports the reply. Do not infer the contents of an inaccessible attachment from its name. If an attachment is superseded, keep the relationship visible so a later reviewer knows why the current version was used.'
      ]},
      { heading: 'Control drafting and sending separately', rows: [], paragraphs: [
        'Drafting authority should be narrower than mailbox access and separate from send authority. An assistant may label messages, gather approved records, prepare a neutral acknowledgement, or draft under a template. Responses that change money, terms, policy, access, privacy, legal position, public statements, or personal commitments require the named owner or specialist. A polished draft is still pending until the required decision exists.',
        'Templates carry context assumptions. Record which message classes they cover, prohibited variants, required fields, owner, and version. If the customer or vendor asks a question outside the template, the assistant should not stretch familiar wording to close the item. A template-drift or exception note is more valuable than a fast reply that quietly creates a new promise.',
        'The send record should preserve approver, final recipients, final text or stable identifier, attachments, time, and source state. If the owner edits the draft substantially, keep the final approved version rather than attributing it to the preparation stage. Corrections and recalls remain linked to the original message so the routine can learn without rewriting history.'
      ]},
      { heading: 'Use findings to narrow the lane', rows: [], paragraphs: [
        'Report how often each required context element was available, missing, contradictory, or discovered only after escalation. Separate safe pauses from avoidable omissions. A higher clarification count may reflect responsible detection in a newly controlled inbox rather than poor performance. Pair counts with consequence and examples that do not reveal private content.',
        'Review thread age and workload separately from context quality. An old thread may be complete but waiting for an external event, while a new message can be unsafe because its prior commitment is missing. Likewise, a short response time does not show that the right history was consulted. Retain waiting reason, evidence-ready time, review time, and send decision as distinct events. This keeps the study from blaming an assistant for owner or customer waiting and prevents speed from concealing an unsupported reply.',
        'Limitations include side conversations the study cannot access, incomplete migration history, private relationships, ambiguous policy, and hindsight after the final outcome. The sample describes this inbox and period. It cannot prove a universal staffing ratio, a worker’s trustworthiness, or that every future message in a stable category will be safe.',
        'The buyer should finish with an explicit scope: which thread classes an assistant may triage, which records can be consulted, which drafts need review, which templates may be sent, and which triggers stop work. The mailbox owner retains access decisions, sensitive disclosure, commitments, consequential exceptions, and account recovery. Context evidence makes delegation reviewable; it does not transfer ownership of the conversation.'
      ]},
    ],
    serviceHandoff: { heading: 'Design the shared-inbox lane', href: '/services/inbox-triage', label: 'inbox triage service', paragraphs: ['Use the context-loss test when scoping an inbox triage service, with access, send authority, commitments, and sensitive exceptions retained by the mailbox owner.'] },
    faqs: [{ q: 'Can a summary replace the original thread?', a: 'It can guide review, but material facts and decisions must remain traceable to the authorised source records.' }, { q: 'When should drafting stop?', a: 'When identity, recipients, prior commitments, governing records, or authority are missing for a consequential reply.' }],
  },
  {
    slug: 'research-brief-source-update-trigger-study', title: 'When should an assistant reopen the sources in a research brief?',
    excerpt: 'A claim-level freshness study that replaces arbitrary age limits with documented change triggers, source ownership, rechecks, and editorial decisions.',
    published: '2026-10-05', updated: '2026-10-05', cluster: 'Research briefing research',
    image: { url: '/illustrations/getillustrations/goodle-team/assistant-handoff-collaboration.svg', alt: 'Researcher and editor checking source dates and change triggers' },
    headlineStat: 'Source age is not the same as source fitness: a stable definition may remain applicable while a newer price, officeholder, rule, schedule, or product page can become wrong quickly.',
    methodology: 'Track material claims in a bounded set of briefs from initial source check through editorial approval. For each claim, record source owner, version or publication date, checked date, change indicators, supported scope, recheck event, wording decision, and later correction. GAO reliability guidance frames fitness for purpose; NIST governance concepts frame ownership and review. This method does not supply legal, medical, financial, or regulatory advice.',
    keyStats: ['Unit: one material claim and the evidence needed for its intended reader decision.', 'Trigger classes: scheduled release, version change, volatile field, broken route, contradictory authority, scope change, or owner request.', 'Result: unchanged and supported, updated, narrowed, removed, contradicted, inaccessible, or escalated.'],
    takeaways: ['Assign freshness at the claim level, not one expiry date to an entire article.', 'Prefer authoritative version and update signals over search-result recency.', 'A recheck can end by narrowing or removing a claim; finding a replacement statistic is not mandatory.'],
    sources: governanceSources, related: ['source-freshness-for-daily-outsourced-articles', 'outsourced-research-brief-acceptance-protocol', 'content-research-source-traceability'],
    body: ['claim volatility', 'source ownership', 'trigger calendar', 'recheck evidence', 'editorial resolution'],
    sections: [
      { heading: 'Classify change before choosing a schedule', rows: [], paragraphs: [
        'Some evidence changes on a known timetable: official statistics, recurring reports, standards revisions, election results, or scheduled rate decisions. Other evidence changes without a calendar: product features, prices, executive roles, service availability, and web guidance. A third group contains stable historical facts or definitions. Applying the same thirty-day rule to all three creates needless work in one place and stale claims in another.',
        'The brief should identify what could change the meaning of each material claim. For a statistic, that may be a new release or revised series. For a standard, it may be a superseding version or erratum. For a service page, it may be a product update. For a public official or schedule, the fact itself is volatile. This classification is an editorial hypothesis that the reviewer can revise; it is not a promise that unlisted change cannot occur.',
        'Freshness also depends on the decision. An older primary study may remain appropriate for a historical finding while being insufficient to describe the current market. A current secondary summary may still misstate the measured population. Following GAO’s fitness concepts, ask whether evidence is accurate enough, complete enough, and applicable to the article’s exact purpose, not merely whether its date looks recent.'
      ]},
      { heading: 'Record source ownership and version identity', rows: [], paragraphs: [
        'Store title, publisher, canonical URL, publication or version date when available, checked date, and the passage or data element supporting the claim. For living pages, note visible update signals and the absence of a version marker rather than inventing one. A search result snippet is a discovery aid, not the evidence record. Redirects and mirrored copies should be reconciled with the publisher’s authoritative route.',
        'Ownership is not the same as authority for every question. A product vendor is primary for its current documented feature but not an independent judge of business benefit. A statistics agency may define its series but not answer a company-specific staffing question. Record why the source fits the claim and where it stops. That note helps a future assistant recheck meaning instead of replacing an unavailable page with the first similar sentence.',
        'When a source disappears, preserve permitted bibliographic and review evidence without republishing copyrighted material. Check whether the publisher moved, superseded, archived, or withdrew it. An archive can establish what a page said at a prior time; it does not prove the statement remains current. If continued support cannot be established, narrow or remove the claim and tell the editor what changed.'
      ]},
      { heading: 'Build triggers around the publishing decision', rows: [], paragraphs: [
        'Every material volatile claim gets a next-check trigger. It may be immediately before publication, after a known release, when a cited version changes, when the brief scope changes, or when contradictory authoritative evidence appears. Stable claims can use a longer review interval plus event triggers. Record the trigger owner so “check later” does not become an orphaned note.',
        'A production delay can make a previously checked brief stale. Before approval, recheck fields that could reverse the reader’s decision rather than reopening every source indiscriminately. Confirm the article’s dates, named organisations and people, prices or availability if included, current rule or standard versions, and links supporting the central conclusion. Keep the earlier observation so the editor can see whether wording changed because evidence changed or because the analysis improved.',
        'Crossing midnight matters for publication metadata, but it does not automatically change evidence. The checked date records when the source was reviewed; the publication date records when the article first becomes publicly reachable and passes verification. They answer different questions. A delayed release may require another source check under the trigger rule and must use its actual publication date rather than the original campaign label.'
      ]},
      { heading: 'Resolve changed evidence without patchwriting', rows: [], paragraphs: [
        'When a source changes, revisit the argument, not just the number. A revised population, definition, methodology, or jurisdiction may invalidate the comparison around it. Update the claim table, identify downstream paragraphs, and ask whether the conclusion still follows. Replacing one statistic while leaving the old reasoning intact can produce a fluent but unsupported article.',
        'Contradictory evidence deserves a structured note: what each source measures, population, period, method, authority, and supported conclusion. Sources can differ without one being wrong. The editor may present both, narrow the claim, choose the source that matches the decision, or stop publication. The assistant prepares the comparison and labels inference; it does not hide conflict to preserve a deadline.',
        'Rechecking should be bounded. If the official source confirms no material change, record the event and leave approved prose alone. Continuous rewriting introduces errors and makes review unstable. If a nonmaterial layout change occurs, do not claim the evidence was substantively updated. A truthful log distinguishes accessed, unchanged, revised, superseded, inaccessible, and not rechecked.'
      ]},
      { heading: 'Evaluate the routine through corrections and misses', rows: [], paragraphs: [
        'Sample claims across volatility classes and compare the planned trigger with what actually changed. Include claims removed before publication, corrections after release, and sources that remained stable. Measure whether the trigger fired, whether the recheck found the change, whether the editor received a decision-ready note, and whether public wording and metadata were corrected when needed.',
        'Do not turn correction count into a writer score. More corrections can reflect volatile subject matter, stronger detection, or weak earlier controls. Misses may remain undiscovered. Report examples and denominators, and separate evidence change from initial misreading, unsupported inference, broken link, and editorial change. Each cause suggests a different improvement.',
        'The study’s practical result is a source-maintenance plan attached to reader decisions. An assistant can own scheduled checks, version comparison, claim mapping, and escalation. The editor owns whether the claim remains useful, how uncertainty is expressed, and whether publication proceeds. This division supports a daily article routine without pretending that a fresh date, a long source list, or automated link success guarantees current research.'
      ]},
    ],
    serviceHandoff: { heading: 'Commission a maintainable evidence brief', href: '/services/research-briefing', label: 'research briefing service', paragraphs: ['Use claim-level change triggers when scoping a research briefing service; consequential interpretation and publication approval remain editorial decisions.'] },
    faqs: [{ q: 'How old is too old for a source?', a: 'There is no universal age. Fitness depends on what the claim asks, what can change, the source’s authority and scope, and the publication decision.' }, { q: 'What if the source changed?', a: 'Reassess the claim and downstream reasoning; update, qualify, narrow, remove, or escalate rather than swapping a number mechanically.' }],
  },
];
