import type { ResearchPost } from './fleet-content';

const source = (name: string, url: string, note: string) => ({ name, url, note });
const sources = [
  source('NIST Cybersecurity Framework 2.0', 'https://www.nist.gov/cyberframework', 'Governance and risk ownership.'),
  source('UK Government Service Manual: Measuring Success', 'https://www.gov.uk/service-manual/measuring-success', 'Measurement design and interpretation.'),
  source('OECD Measuring Productivity', 'https://www.oecd.org/en/topics/sub-issues/measuring-productivity.html', 'Definitions, populations, and measurement limits.'),
];
type Spec = { slug: string; title: string; excerpt: string; cluster: string; question: string; finding: string; method: string; risk: string; test: string };
const specs: Spec[] = [
  { slug: 'assistant-queue-interruption-cost-observation', title: 'How should a team observe interruption cost in an assistant queue?', excerpt: 'A bounded method for studying task switches without turning activity data into a productivity verdict.', cluster: 'Operations research', question: 'whether interruptions make a delegated queue harder to resume', finding: 'A task switch is interpretable only when the queue records the prior state, interruption reason, and work needed to resume.', method: 'Compare similar work items across a fixed observation period. Record interruptions, source, duration, resume step, errors found at review, and owner availability.', risk: 'A high interruption count does not prove poor performance. Urgent owner requests, broken inputs, or unstable tools may create the pattern.', test: 'Pilot the record on one queue for two weeks, then inspect which interruption types caused lost context or extra review.' },
  { slug: 'delegated-work-approval-sampling-bias', title: 'Can approval-only samples hide problems in delegated work?', excerpt: 'Research on survivorship bias when a quality review examines only assistant work that reached approval.', cluster: 'Quality research', question: 'whether approved items represent the full work queue', finding: 'A sample of approved work omits stopped, abandoned, reassigned, and repeatedly returned items unless the reviewer includes them deliberately.', method: 'Define the eligible queue before sampling. Preserve every disposition and select records across routine, returned, stopped, and exception states.', risk: 'An approval rate can rise because difficult work disappeared from the denominator, not because the routine improved.', test: 'Compare an approval-only sample with a state-stratified sample from the same period and document which defect categories appear only in the latter.' },
  { slug: 'philippines-handoff-overlap-window-study', title: 'What should a Philippines handoff overlap window be tested against?', excerpt: 'A research design for evaluating overlap time through decisions resolved, not presence alone.', cluster: 'Distributed work', question: 'whether a scheduled overlap window reduces avoidable waiting', finding: 'Overlap has operational value when the team ties it to named decisions, complete packets, and a known owner who can respond.', method: 'Record questions ready before overlap, decisions attempted, decisions resolved, missing evidence, and work resumed after the window.', risk: 'Attendance minutes alone do not show that the overlap helped. Topic mix and owner availability can change the result.', test: 'Run the same handoff template before and after a small schedule change while preserving stopped and unanswered questions.' },
  { slug: 'assistant-access-review-evidence-completeness', title: 'What makes an assistant access review record complete?', excerpt: 'A source-led study of the evidence needed to retain, narrow, or remove delegated access.', cluster: 'Security research', question: 'whether each permission still supports a current, approved task', finding: 'A usable review record connects the person, resource, permission, business purpose, approver, last use evidence, and next review decision.', method: 'Inventory account and delegated permissions, match each to an active task, record exceptions, and have the resource owner decide the disposition.', risk: 'A login timestamp proves use, not need. Missing activity also does not prove that access is safe to remove without checking the work owner.', test: 'Sample permissions from one assistant role and measure how often the reviewer can decide without asking for missing purpose or ownership data.' },
  { slug: 'research-brief-return-reason-taxonomy', title: 'Can return reasons improve an outsourced research brief?', excerpt: 'A practical taxonomy for learning why evidence packets come back from editorial review.', cluster: 'Research operations', question: 'which defects belong to intake, sourcing, interpretation, drafting, or approval', finding: 'Return counts become useful when every category points to a stage that can be changed and preserves the reviewer’s actual reason.', method: 'Code returned briefs by the earliest repairable cause, allow a secondary code, and retain the reviewer note and final disposition.', risk: 'A broad “quality issue” label hides the remedy, while too many categories make reviewers classify inconsistently.', test: 'Code one month of returns with a short dictionary, double-review a sample, and merge labels that reviewers cannot distinguish.' },
];

const make = (s: Spec): ResearchPost => ({
  slug: s.slug, title: s.title, excerpt: s.excerpt,
  published: '2026-08-31', updated: '2026-08-31', cluster: s.cluster,
  headlineStat: s.finding,
  methodology: `Research question: ${s.question}. ${s.method} This is a local operating study for OutsourcingAssistant.com, not a universal benchmark, causal claim, or evaluation of workers by nationality.`,
  keyStats: [s.finding, 'The eligible population and every excluded state must be named before calculation.', 'An assistant may prepare evidence; the authorized owner interprets consequential results.'],
  takeaways: ['Define the question and eligible queue before collecting observations.', 'Keep waiting, stopped, returned, and approved states separate.', 'Use the result to change one documented control, then observe again.'],
  sections: [
    { heading: 'Define the decision before the metric', paragraphs: [`The working question is ${s.question}. Begin with the decision the observation may inform. A metric without a decision invites a neat chart that changes nothing. State the queue, period, eligible records, exclusions, and owner before data collection starts.`, 'The assistant can maintain the record and flag incomplete rows. The owner decides whether the population is comparable enough to support an operational change.'], rows: [{ label: 'Research question', value: s.question, source: 'Local study design' }, { label: 'Decision owner', value: 'The person authorized to change the workflow', source: 'NIST governance context' }] },
    { heading: 'Collect evidence that survives a handoff', paragraphs: [s.method, 'Keep source fields beside the observation. A reviewer in another time zone should be able to reconstruct the state without searching chat messages or guessing why an item was excluded.'], rows: [{ label: 'Minimum record', value: 'Item, state, timestamp, source, owner, reason, disposition', source: 'UK Government measurement logic' }, { label: 'Date', value: 'August 31, 2026 campaign and publication date', source: 'OutsourcingAssistant.com batch record' }] },
    { heading: 'Interpret the finding within its limits', paragraphs: [s.finding, s.risk], rows: [{ label: 'Supported use', value: 'Improve the observed local queue', source: 'This study design' }, { label: 'Unsupported use', value: 'Ranking people or claiming a universal productivity effect', source: 'OECD measurement limits' }] },
    { heading: 'Run a small test', paragraphs: [s.test, 'Keep the previous rule, change, observation period, and result together. If the evidence is mixed, preserve the disagreement and narrow the next question rather than smoothing it into a confident conclusion.'], rows: [{ label: 'Test', value: s.test, source: 'Local operating proposal' }, { label: 'Stop rule', value: 'Pause interpretation when missing records could change the result', source: 'Research governance analysis' }] },
    { heading: 'Conclusion and limitations', paragraphs: [`The evidence supports a modest conclusion: ${s.finding.toLowerCase()} This can make a delegated routine easier to inspect, but it cannot isolate every influence on the result.`, 'A Philippines-based assistant can collect observations, check completeness, and prepare the comparison. The owner retains authority over access, policy, public claims, and changes that affect staff or customers.'], rows: [{ label: 'Conclusion', value: s.finding, source: 'NIST, OECD, and UK Government synthesis' }, { label: 'Limit', value: s.risk, source: 'Scope analysis' }] },
  ],
  faqs: [{ q: 'Does this method produce a benchmark?', a: 'No. It describes a defined local queue and period. Comparisons require the same population, rules, and measurement method.' }, { q: 'What can the assistant own?', a: 'The assistant can maintain records and prepare analysis. An authorized owner decides policy, access, and consequential interpretation.' }],
  sources,
  related: ['assistant-quality-scorecard', 'time-zone-handoff-design', 'claim-scope-provenance'], body: [],
});

export const researchBatch20260831: readonly ResearchPost[] = specs.map(make);
