import type { ResearchPost, ResearchSource } from './fleet-content';

const sources: readonly ResearchSource[] = [
  { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework', note: 'Governance and risk-management outcomes.' },
  { name: 'NIST SP 800-53 Revision 5', url: 'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final', note: 'Access, audit, and account-management guidance.' },
  { name: 'CISA Secure Our World', url: 'https://www.cisa.gov/secure-our-world', note: 'Practical identity and phishing safeguards.' },
  { name: 'FTC Data Security', url: 'https://www.ftc.gov/business-guidance/privacy-security/data-security', note: 'Data minimisation and reasonable safeguards.' },
  { name: 'CIS Critical Security Controls v8', url: 'https://www.cisecurity.org/controls/v8', note: 'Prioritised inventory and access safeguards.' },
  { name: 'ILO Working from Home Report', url: 'https://www.ilo.org/global/topics/non-standard-employment/publications/WCMS_765806/lang--en/index.htm', note: 'Organisation and working-condition context.' },
];

type Topic = {
  slug: string; title: string; excerpt: string; cluster: string; stat: string; published: string; question: string;
  finding: string; distinction: string; scenario: string; measure: string; boundary: string; related: readonly string[];
};

const makePost = (t: Topic): ResearchPost => ({
  slug: t.slug, title: t.title, excerpt: t.excerpt, published: t.published, updated: '2026-08-17', cluster: t.cluster,
  headlineStat: t.stat,
  methodology: `Research question: ${t.question} This desk review compares the operating question with guidance from six named public sources, then applies that evidence to a Philippines-based assistant supporting a small business. The sources describe controls and work conditions; they do not establish that outsourcing causes a particular result.`,
  keyStats: [t.stat, 'Six named public sources reviewed', 'Three decision boundaries examined'],
  takeaways: [t.finding, t.distinction, 'Treat the result as a bounded design decision and re-check it when the task, data, or owner changes.'],
  sections: [
    { heading: 'Research question and scope', paragraphs: [t.question, `The unit of analysis is one recurring work queue handled by a Philippines-based assistant for an owner-led company. The review considers preparation, evidence capture, escalation, and acceptance. It does not assess individual worker performance, employment classification, legal compliance in a particular jurisdiction, or a vendor’s commercial claims.`], rows: [{ label: 'Population', value: 'One recurring assistant-supported queue', source: 'Defined scope for this review' }, { label: 'Evidence type', value: 'Public standards and guidance, not a causal trial', source: 'Method boundary' }] },
    { heading: 'What the evidence supports', paragraphs: [t.finding, `NIST’s governance framing is useful here because a manager must decide who is accountable before a tool permission or handoff exists. CIS and NIST control guidance reinforce inventory, account, and review questions. Those sources support a control model; they do not prove that every small team needs the same control depth.`], rows: [{ label: 'Control anchor', value: 'Name the owner, resource, action, and review point', source: 'NIST CSF 2.0; NIST SP 800-53' }, { label: 'Security anchor', value: 'Know what is shared and why it remains shared', source: 'CIS Controls v8; FTC Data Security' }] },
    { heading: 'The niche-specific decision', paragraphs: [t.distinction, `The Philippines setting matters operationally because the assistant and owner may not share working hours. A handoff therefore needs a status, a source record, and a named next decision-maker. Time-zone coverage can improve continuity, but a gap in authority still leaves work waiting; it is not solved by simply adding another inbox or permission.`], rows: [{ label: 'Preparation', value: 'Assistant may collect, classify, draft, and cite', source: 'Operational interpretation' }, { label: 'Decision', value: 'Owner or named approver keeps consequential action', source: 'NIST governance and access principles' }] },
    { heading: 'A bounded operating test', paragraphs: [`Start with a fixed sample of ${t.measure}. For each item, record the input, source checked, proposed result, exception reason, and reviewer decision. Review enough items to expose repeated ambiguity rather than rewarding raw throughput. If the same exception appears repeatedly, update the task definition before expanding volume.`, `A useful test compares the queue before and after the handoff using the same definitions. Count returned items and waiting-on-owner time separately from assistant defects. That prevents a slow approval loop from being mislabelled as poor preparation.`], rows: [{ label: 'Quality signal', value: 'Defects classified by cause, not one blended score', source: 'Measurement design' }, { label: 'Continuity signal', value: 'Waiting status includes owner and next event', source: 'ILO working-condition context' }] },
    { heading: 'Scenario analysis', paragraphs: [t.scenario, `In the low-consequence case, the assistant can usually prepare a complete record for review. In the high-consequence case, the correct output is often a flagged case with evidence, not a completed action. The boundary should be written in examples because a generic instruction such as “use judgment” transfers risk without defining authority.`], rows: [{ label: 'Routine case', value: 'Prepare and document within the approved queue', source: 'Operational recommendation' }, { label: 'Exception case', value: 'Pause, preserve evidence, and escalate', source: 'CISA; NIST incident and access guidance' }] },
    { heading: 'Limitations and counter-cases', paragraphs: [t.boundary, `The evidence set is not a Philippines outsourcing survey, a productivity benchmark, or proof of return on investment. It also cannot decide whether a particular task contains regulated data or requires professional advice. Local law, contract terms, data-processing roles, and employment arrangements require qualified review where applicable.`], rows: [{ label: 'Not proven', value: 'A control pattern guarantees quality or security', source: 'Scope limitation' }, { label: 'Needs local review', value: 'Legal, regulatory, employment, and privacy obligations', source: 'FTC and ICO-style principles do not replace counsel' }] },
    { heading: 'Conclusion', paragraphs: [`For ${t.title.toLowerCase()}, the evidence points to a narrow conclusion: make the work observable, keep authority explicit, and measure the queue with denominators that include waiting and returned work. That is more defensible than assuming a remote assistant can safely own an undefined outcome.`, `The owner should approve the smallest useful trial, name the evidence required for acceptance, and set a review date. Expand the lane only when the sample shows that the handoff works under the actual data, tools, time zone, and exception load.`], rows: [{ label: 'Evidence-led conclusion', value: t.finding, source: 'Synthesis of the named sources' }, { label: 'Next decision', value: 'Approve, narrow, or stop the bounded trial', source: 'Owner governance decision' }] },
  ],
  faqs: [{ q: 'Does this research prove outsourcing is better?', a: 'No. It identifies a bounded control and measurement question for one assistant-supported queue; it does not establish a causal business result.' }, { q: 'What should the owner review first?', a: 'Review the scope, data access, exception examples, evidence trail, and the definition of acceptance before increasing volume.' }],
  sources, related: t.related, body: [],
});

export const researchBatch20260817: readonly ResearchPost[] = [
  makePost({ slug: 'assistant-research-brief-source-fit', published: '2026-08-17', title: 'Assistant research brief source fit for outsourcing decisions', excerpt: 'How source population, method, and scope affect a research brief prepared by a Philippines-based assistant.', cluster: 'Research operations', stat: 'Source fit depends on population, method, scope, and observation period', question: 'How should an owner judge whether a source is fit for an outsourcing decision brief?', finding: 'A source is useful only when its population and method match the claim being made.', distinction: 'A cited source can add authority without answering the specific operational question.', scenario: 'An assistant finds a national survey and uses it to describe one company’s customer queue.', measure: 'source-to-claim matches and unresolved scope gaps', boundary: 'Source fit cannot turn a descriptive survey into a forecast for one company.', related: ['outsourced-research-source-register', 'source-recency-interpretation', 'research-evidence-strength-ranking'] }),
  makePost({ slug: 'philippines-assistant-review-window-capacity', published: '2026-08-17', title: 'Philippines assistant review-window capacity across time zones', excerpt: 'A research model for separating production capacity from the owner review time that makes delegated work safe.', cluster: 'Distributed work', stat: 'Production time and decision time are different capacity constraints', question: 'When does a time-zone handoff improve continuity, and when does owner review become the bottleneck?', finding: 'A queue is not truly supported if completed work waits indefinitely for an authorised decision.', distinction: 'Hours available for preparation do not equal hours available for approval.', scenario: 'A Philippines-based assistant completes a morning queue while the owner is offline and no exception route exists.', measure: 'ready items, owner-wait hours, and decision-window coverage', boundary: 'This does not predict staffing capacity without the team’s actual schedule and queue volume.', related: ['review-window-coverage', 'time-zone-handoff-design', 'handoff-state-transitions'] }),
  makePost({ slug: 'delegated-inbox-risk-segmentation', published: '2026-08-17', title: 'Delegated inbox risk segmentation for virtual assistant work', excerpt: 'How to separate routine inbox preparation from messages that carry privacy, payment, or commitment risk.', cluster: 'Executive operations', stat: 'Inbox authority should follow consequence, not message volume', question: 'Which inbox messages can a virtual assistant prepare, and which require owner review before any response?', finding: 'Segmentation by consequence and required authority is safer than a simple urgent-versus-normal label.', distinction: 'A fast reply is not a successful handoff when the message changes a commitment or exposes sensitive data.', scenario: 'An assistant receives a routine scheduling request beside a bank-detail change in the same shared inbox.', measure: 'cases by consequence class, escalation reason, and approval outcome', boundary: 'No segmentation scheme replaces incident response, legal advice, or a business-specific data policy.', related: ['inbox-triage-risk-controls', 'sensitive-case-segmentation', 'support-queue-privacy-controls'] }),
  makePost({ slug: 'outsourced-crm-field-change-provenance', published: '2026-08-17', title: 'Outsourced CRM field-change provenance for assistant updates', excerpt: 'Why every delegated CRM correction needs a source, timestamp, proposed change, and accountable reviewer.', cluster: 'Operations data', stat: 'A corrected field is more trustworthy when its source and decision remain visible', question: 'What evidence should accompany a CRM field change prepared by an outsourced assistant?', finding: 'Provenance lets an owner distinguish a supported correction from a plausible guess.', distinction: 'Data cleanliness is not the same as changing more fields or deleting more history.', scenario: 'An assistant sees two customer records with different phone numbers and prepares a merge.', measure: 'changes with source evidence, reversals, and unresolved conflicts', boundary: 'A provenance record does not validate the source itself or remove retention obligations.', related: ['record-correction-confidence', 'crm-record-confidence-review', 'outsourced-crm-audit-trail'] }),
  makePost({ slug: 'assistant-task-intake-evidence-quality', published: '2026-08-17', title: 'Assistant task-intake evidence quality for outsourced operations', excerpt: 'A bounded way to tell whether a request contains enough context for a Philippines-based assistant to begin.', cluster: 'Delegation design', stat: 'Intake quality is a decision about missing context, not a speed score', question: 'How can an owner tell whether a delegated task is ready for preparation?', finding: 'A ready task names the outcome, source records, authority boundary, and acceptance evidence.', distinction: 'A short request may be efficient for a familiar owner but incomplete for a new assistant.', scenario: 'A request says “follow up with the vendor” but omits the approved contact, desired outcome, and spending limit.', measure: 'intake fields present, clarification cycles, and returned tasks', boundary: 'Completeness does not guarantee the requested action is appropriate or authorised.', related: ['input-completeness-baseline', 'assistant-delegation-scope-mapping', 'assistant-work-acceptance-criteria'] }),
  makePost({ slug: 'remote-assistant-access-review-periods', published: '2026-08-17', title: 'Remote assistant access review periods for small teams', excerpt: 'How to connect a delegated permission to a task, owner, resource, and review date.', cluster: 'Security operations', stat: 'A permission without a review point becomes difficult to justify over time', question: 'How often should a small team re-check access granted to a remote assistant?', finding: 'Review cadence should follow task sensitivity, change rate, and consequence rather than a universal calendar rule.', distinction: 'A quarterly reminder is not evidence that access still matches the work.', scenario: 'An assistant moves from one shared folder to a new support queue but keeps access to the old workspace.', measure: 'active permissions tied to current tasks, owners, and review outcomes', boundary: 'This framework does not set a compliance interval for a particular industry or jurisdiction.', related: ['access-purpose-evidence', 'remote-assistant-access-review', 'permission-review-expiry'] }),
  makePost({ slug: 'outsourced-support-escalation-evidence', published: '2026-08-17', title: 'Outsourced support escalation evidence before customer replies', excerpt: 'How support preparation can preserve customer context while keeping refunds, promises, and policy exceptions with the owner.', cluster: 'Support operations', stat: 'Escalation quality depends on context, policy fit, and a clear decision owner', question: 'What should an outsourced support assistant attach before escalating a consequential customer case?', finding: 'The smallest useful packet includes the customer request, source record, policy reference, proposed next step, and unresolved risk.', distinction: 'A polite draft can still be unsafe if it implies a refund, admission, or delivery promise.', scenario: 'A customer requests a refund outside the normal window and the order record is incomplete.', measure: 'escalations with complete evidence and decisions returned for missing context', boundary: 'The model does not interpret consumer law or decide the business’s refund policy.', related: ['customer-support-escalation-matrix', 'support-refund-approval-queue', 'outsourced-support-case-classification'] }),
  makePost({ slug: 'assistant-vendor-follow-up-authority', published: '2026-08-17', title: 'Assistant vendor follow-up authority in outsourced operations', excerpt: 'A source-led boundary between preparing supplier follow-up and making an unauthorised commercial commitment.', cluster: 'Operations systems', stat: 'Contacting a supplier and changing an obligation are different authorities', question: 'Where should a vendor follow-up assistant stop when a supplier asks for a commitment?', finding: 'The assistant can verify status and prepare options, while price, terms, payment, and acceptance decisions need an authorised owner.', distinction: 'Persistence improves visibility only when the escalation line prevents accidental promises.', scenario: 'A supplier asks the assistant to approve a substitute item and accept a revised delivery condition.', measure: 'follow-ups by status, exception type, and owner decision time', boundary: 'This is not procurement, contract, or legal advice and cannot approve a supplier relationship.', related: ['vendor-follow-up-authority-limits', 'vendor-contact-verification', 'vendor-follow-up-source-checks'] }),
  makePost({ slug: 'assistant-content-claim-evidence-boundaries', published: '2026-08-17', title: 'Assistant content claim evidence boundaries for research publishing', excerpt: 'How a research assistant can collect and map sources without turning citations into unsupported publication claims.', cluster: 'Content operations', stat: 'A citation supports a claim only within the source’s actual scope', question: 'How should a content team separate source collection, claim drafting, and publication approval?', finding: 'Claim provenance is strongest when the exact source passage, interpretation, limitation, and approver remain connected.', distinction: 'Adding citations after drafting does not repair a thesis that the evidence never addressed.', scenario: 'An assistant finds a security standard and drafts a guarantee about the safety of outsourced work.', measure: 'claims with direct source mapping, limitations, and review decisions', boundary: 'This does not replace subject-matter review for legal, medical, financial, or security claims.', related: ['content-claim-escalation-rules', 'research-claim-review-queue', 'content-research-source-traceability'] }),
  makePost({ slug: 'assistant-quality-sample-denominators', published: '2026-08-17', title: 'Assistant quality-sample denominators for recurring queues', excerpt: 'Why returned, reopened, waiting, and excluded items must stay visible when assistant work is evaluated.', cluster: 'Quality systems', stat: 'A quality rate is meaningful only when its population and exclusions are explicit', question: 'What should count in a quality sample for a recurring assistant queue?', finding: 'The denominator must describe the work that entered review, not only the items that passed cleanly.', distinction: 'A high pass rate can hide rework when failed or waiting items are removed before measurement.', scenario: 'A manager samples only completed CRM updates while returned records remain in a separate spreadsheet.', measure: 'items received, sampled, returned, reopened, and excluded with reasons', boundary: 'A sampling result is not a performance ranking or a guarantee of future accuracy.', related: ['queue-denominator-integrity', 'assistant-quality-sampling-plan', 'assistant-quality-scorecard'] }),
  makePost({ slug: 'outsourced-assistant-offboarding-evidence', published: '2026-08-17', title: 'Outsourced assistant offboarding evidence for continuity', excerpt: 'A research-backed way to close access, transfer open work, and retain only the records the business still needs.', cluster: 'Security operations', stat: 'Offboarding is both an access event and a continuity handoff', question: 'What evidence shows that a remote assistant’s access was closed without losing necessary work?', finding: 'A defensible closeout links each account and active task to an action, owner, timestamp, and follow-up check.', distinction: 'Disabling one login is not the same as reviewing forwarding rules, shared links, tokens, and open queues.', scenario: 'A support assistant leaves while customer cases, delegated inbox rules, and a shared folder remain active.', measure: 'accounts closed, sessions revoked, work transferred, and residual access checks', boundary: 'The evidence pattern does not determine retention periods or employment obligations.', related: ['outsourced-access-offboarding-runbook', 'secure-offboarding-checklist', 'access-review-cadence'] }),
];
