import type { ResearchPost, ResearchSection, ResearchSource } from './fleet-content';

const sources: readonly ResearchSource[]=[
 {name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework',note:'Primary governance and risk-management framework.'},
 {name:'NIST SP 800-53 Revision 5, Update 1',url:'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final',note:'Primary controls guidance for access, accountability, and review.'},
 {name:'U.S. GAO Assessing Data Reliability',url:'https://www.gao.gov/products/gao-20-283g',note:'Primary methodology guidance for assessing whether evidence is fit for use.'},
 {name:'UK Government Service Manual: Measuring success',url:'https://www.gov.uk/service-manual/measuring-success',note:'Official guidance on interpretable service measures.'},
 {name:'ILO, Working from Home',url:'https://www.ilo.org/publications/working-home-estimating-worldwide-potential',note:'International evidence on remote-work organisation and broad-estimate limits.'}
];
type Spec={slug:string;title:string;excerpt:string;cluster:string;question:string;unit:string;signal:string;limit:string;test:string;image:string};
const specs:Spec[]=[
 {slug:'assistant-handoff-evidence-decay-study',title:'How quickly does handoff evidence lose operational value?',excerpt:'A local longitudinal design for observing when linked facts become stale before an owner reviews assistant-prepared work.',cluster:'Distributed work',question:'Which changes make a previously decision-ready handoff unsafe to act on?',unit:'one handoff version with source timestamps, claimed state, review window, intervening changes, owner response, and disposition',signal:'Elapsed time is not evidence decay by itself; decay occurs when a material source, state, authority, or constraint changes before review.',limit:'This design does not establish a universal handoff lifespan or show that time-zone separation causes stale evidence.',test:'Follow consecutive handoffs through owner review and independently classify every intervening change as material, immaterial, or unresolved.',image:'/images/research-2026-08-23/overnight-research-review-readiness.png'},
 {slug:'delegated-queue-reopen-reason-analysis',title:'Classifying why delegated work queues reopen after closure',excerpt:'A reproducible review design for separating new demand from premature closure, missing evidence, and changed owner decisions.',cluster:'Operations research',question:'What observable reason best explains a closed item returning to active work?',unit:'one reopened item linked to its closure evidence, reopening event, reason category, responsible owner, additional work, and final state',signal:'A reopened item is not automatically rework; new facts, changed scope, and correction of an incomplete closure should be reported separately.',limit:'Local classifications cannot prove individual fault, productivity loss, or a benchmark reopen rate across unlike queues.',test:'Have two reviewers classify a consecutive sample from retained records, publish disagreements, and compare like-for-like task classes only.',image:'/images/research-2026-09-03/manager-feedback-sop-change-thresholds.png'},
 {slug:'outsourced-research-source-substitution-audit',title:'Auditing source substitution in outsourced research briefs',excerpt:'A claim-level method for detecting when a convenient secondary source silently replaces the primary evidence named in a brief.',cluster:'Content research',question:'When does source substitution materially change the support for an assistant-prepared claim?',unit:'one material claim with requested source type, source actually used, access constraint, supported scope, reviewer decision, and final wording',signal:'Substitution matters when it changes authority, measured population, definition, period, or the reader’s ability to verify the claim.',limit:'The audit can identify scope changes but cannot infer an author’s intent or declare every secondary source unsuitable.',test:'Blindly compare claim support under the requested and substituted sources, recording direct, partial, conflicting, inaccessible, or absent support.',image:'/images/research-2026-08-21/source-freshness-for-daily-outsourced-articles.png'},
 {slug:'virtual-assistant-approval-owner-coverage-gaps',title:'Measuring approval-owner coverage gaps in virtual assistant workflows',excerpt:'A time-bounded observational design for finding intervals when decision-ready work has no reachable, authorised reviewer.',cluster:'Governance research',question:'How often does a workflow lack an accepted decision owner during its stated operating window?',unit:'one decision-ready item with consequence class, assigned owner, coverage calendar, handoff acceptance, contact events, decision time, and outcome',signal:'An owner field does not establish coverage unless the person has accepted the role, holds the required authority, and is reachable within the safe decision window.',limit:'The measure does not prescribe staffing ratios or establish that a delayed decision caused a business outcome.',test:'Map consecutive decision-ready items against planned owner coverage and report uncovered intervals separately by consequence class.',image:'/images/research-2026-08-21/philippines-assistant-article-handoff-window.png'},
 {slug:'assistant-data-minimisation-exception-review',title:'Studying exceptions to data minimisation in assistant operations',excerpt:'A field-level method for examining when delegated records collect more personal or commercial data than the task requires.',cluster:'Data quality',question:'Which workflow conditions lead approved records to retain fields beyond their documented purpose?',unit:'one collected field linked to task purpose, necessity rationale, source, access group, retention rule, exception approval, and disposition',signal:'Field presence does not establish necessity; necessity must connect the field to the stated output and the least-data alternative considered.',limit:'This operational review is not a legal compliance determination and cannot identify all harms or obligations in every jurisdiction.',test:'Review all fields in a bounded consecutive sample, compare them with the approved task purpose, and have a privacy owner adjudicate disputed necessity.',image:'/images/research-2026-08-20/assistant-source-chain-for-daily-articles.png'}
];
const section=(heading:string,paragraphs:string[],rows:ResearchSection['rows']):ResearchSection=>({heading,paragraphs,rows});
const make=(x:Spec):ResearchPost=>({slug:x.slug,title:x.title,excerpt:x.excerpt,cluster:x.cluster,published:'2026-09-09',updated:'2026-09-09',image:{url:x.image,alt:`Research-method illustration for ${x.title}`},headlineStat:x.signal,methodology:`Structured desk review of five named public sources followed by a proposed local observational study. The unit of analysis is ${x.unit}. Published principles are separated from OutsourcingAssistant.com operating inferences; the design makes no causal or universal performance claim.`,keyStats:['Five reputable public sources in the desk-review protocol',`Observation unit: ${x.unit}`,'Consecutive in-scope cases proposed to reduce outcome-based selection'],takeaways:[x.signal,'Retain raw observations and disagreements before interpreting results.','Keep consequential classification and workflow changes with the authorised owner.'],sections:[
 section('Research question and scope',[`${x.question} The desk review covers governance, controls, data reliability, measurement, and remote-work organisation. None of the sources evaluates this exact assistant workflow, so the proposed measure is a local inference to test rather than a published benchmark.`,`The unit is ${x.unit}. Defining it before collection prevents messages, projects, fields, and decisions from being mixed in one denominator.`],[{label:'Evidence set',value:'Five named public sources',source:'Desk-review protocol'},{label:'Use',value:'Local workflow diagnosis',source:'Author-defined scope'}]),
 section('Methodology and observation record',[`For each unit, retain the initiating request, authoritative sources, relevant state changes, timestamps, owner, and final disposition. Record missing and conflicting evidence rather than forcing it into a clean category.`,x.test],[{label:'Sampling',value:'Consecutive in-scope observations over a declared period',source:'Proposed method'},{label:'Reproducibility check',value:'Second reviewer reconstructs classifications from retained evidence',source:'GAO reliability principles'}]),
 section('Interpretation',[`${x.signal} Report raw counts and denominators, compare like task classes, and publish category rules before reviewing outcomes.`,`In a Philippines-based routine, retain Philippine Time and the owner-local review window. This allows planned overnight waiting to be distinguished from a genuine coverage failure.`],[{label:'Primary interpretation',value:x.signal,source:'Evidence-informed operating inference'},{label:'Time field',value:'Expected and actual owner-review window',source:'Proposed design'}]),
 section('Inference limits and limitations',[x.limit,`Applying broad public guidance to OutsourcingAssistant.com requires local validation. Results may be distorted by task mix, seasonal demand, missing records, policy changes, reviewer disagreement, or a small observation window.`],[{label:'Claim boundary',value:x.limit,source:'Review scope'},{label:'Excluded inference',value:'No universal benchmark or causal effect',source:'Methodology'}]),
 section('Bounded pilot',[`Pilot the method on a declared consecutive sample and ask a second reviewer to reconstruct every material category from retained evidence. Preserve disagreements and revise the codebook prospectively rather than silently recoding history.`,`Change one workflow element at a time, retain the baseline, and monitor unintended effects such as slower escalation, added collection burden, or sensitive information copied into the study record.`],[{label:'Quality control',value:'Independent reconstruction with disagreement log',source:'Proposed method'},{label:'Change rule',value:'One documented change while retaining baseline',source:'Measurement design'}])
],sources:[...sources],related:[],body:[],faqs:[{q:'Is this a benchmark?',a:'No. It is a local observational design informed by public guidance.'},{q:'What is the unit of analysis?',a:x.unit},{q:'What remains outside the claim?',a:x.limit}],serviceHandoff:{heading:'Turn the question into a bounded evidence brief',href:'/services/research-briefing',label:'research briefing support',paragraphs:['Use research briefing support to define the question, observation unit, evidence boundary, source register, and review owner.','The owner remains responsible for scope, interpretation, privacy decisions, and consequential workflow changes.']}});

export const researchBatch20260909: readonly ResearchPost[] = specs.map(make);
