import type { ResearchPost, ResearchSection, ResearchSource } from './fleet-content';

const sources = (extra: ResearchSource): readonly ResearchSource[] => [
  extra,
  { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework', note: 'Governance and risk-management outcomes used as an analytical frame.' },
  { name: 'NIST SP 800-53 Revision 5', url: 'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final', note: 'Access, accountability, audit, and configuration control guidance.' },
  { name: 'ILO Working from Home Report', url: 'https://www.ilo.org/global/topics/non-standard-employment/publications/WCMS_765806/lang--en/index.htm', note: 'Context on how remote work is organised and experienced.' },
];

const table = (label: string, value: string, source: string) => ({ label, value, source });
const section = (heading: string, paragraphs: readonly string[], rows: readonly ReturnType<typeof table>[]): ResearchSection => ({ heading, paragraphs, rows });

const records: ResearchPost[] = [
  {
    slug: 'assistant-source-chain-for-daily-articles', image: { url: '/images/research-2026-08-20/assistant-source-chain-for-daily-articles.png', alt: 'Assistant reviewing source notes for a daily article' }, title: 'What source chain makes a daily article prepared by an assistant reviewable?',
    excerpt: 'A bounded study of how research questions, source passages, and editorial decisions stay connected in outsourced article routines.', published: '2026-08-20', updated: '2026-08-20', cluster: 'Content operations',
    headlineStat: 'A citation list is weaker than a claim-to-source chain that preserves scope and interpretation.',
    methodology: 'Research question: what evidence chain allows a Philippines-based assistant to prepare a daily article that an owner can review without reconstructing the research? This desk review compares the NIST Cybersecurity Framework 2.0, the U.S. Government Publishing Office Style Manual, the OECD guidance on measuring productivity, and the ILO Working from Home report. The scope is article preparation for OutsourcingAssistant.com; it does not measure search performance, establish a publishing success rate, or prove a causal effect from outsourcing.',
    keyStats: ['Each material claim needs a source, scope, and interpretation note', 'A source URL alone does not show which sentence it supports', 'Editorial review remains separate from research collection'],
    takeaways: ['Write the research question before collecting links.', 'Attach the observed population, period, and source passage to material claims.', 'Let the owner decide whether analysis is sufficiently bounded for publication.'],
    sections: [
      section('The question behind the citation list', ['A daily article is often assembled from a brief, several public pages, a draft, and a review conversation. When those pieces are separate, a reviewer sees citations but cannot tell whether a source supports the sentence beside it. The useful unit is therefore not the article’s bibliography. It is the claim chain: question, observed evidence, interpretation, limitation, and editorial decision.', 'For an outsourced assistant, this distinction defines the role. The assistant can locate primary or authoritative material, quote or paraphrase the relevant finding, record what population and period it covers, and mark an inference as analysis. The editor decides whether the claim belongs in public copy. That division preserves speed in preparation without transferring publication judgment to an unexamined link list.'], [table('Chain minimum', 'Question, claim, source, scope, interpretation, limitation, decision', 'This review method'), table('Failure signal', 'A citation is present but its supported sentence cannot be identified', 'Source-chain test')]),
      section('How evidence scope changes the sentence', ['A national labour statistic can describe an occupation while saying little about one company’s article queue. A framework can define governance outcomes while saying nothing about the number of hours a particular assistant needs. An editorial style manual can explain treatment of dates and headings without validating a business conclusion. The assistant should preserve those boundaries in the research record instead of converting context into a local benchmark.', 'A practical chain contains the source title and URL, the exact finding or paraphrase, the population or unit observed, the observation period, and the proposed sentence. The reviewer can then ask whether the sentence stays inside that evidence. If it does not, the repair is to narrow the sentence or label the transfer as analysis, not to add a more impressive citation.'], [table('Observed fact', 'What the linked source directly reports or recommends', 'OECD and GPO scope'), table('Analysis', 'A bounded implication for an assistant-supported article routine', 'Editorial interpretation')]),
      section('A research packet the assistant can prepare', ['The assistant can prepare a packet with the question at the top, a short source table, claim-level notes, unresolved conflicts, and a proposed outline. Each source row should explain why it is relevant and what it cannot prove. This makes a review conversation concrete: the editor can accept the source, reject it, narrow the claim, or request a better source without rereading an unstructured search history.', 'The packet should also identify freshness risk. A current rule, product instruction, or security recommendation may require a more recent check than a durable research principle. Date the review of the source, but do not imply that checking a page makes every claim timeless. A daily content routine is more trustworthy when a source’s volatility is visible and the next review trigger is explicit.'], [table('Preparation authority', 'Collect, compare, annotate, and propose', 'Role-boundary analysis'), table('Editorial authority', 'Approve public wording, thesis, and conclusion', 'OutsourcingAssistant.com operating boundary')]),
      section('Limitations and evidence-led conclusion', ['This review does not test inter-reviewer agreement, estimate an ideal number of sources, or determine whether every topic has a suitable public dataset. Source pages can be revised, definitions can differ, and a small business question may not match the population of any available study. Those limitations mean the chain supports inspection; it does not manufacture certainty.', 'The evidence-led conclusion is that daily article preparation becomes reviewable when every important sentence has a visible relationship to the question, source scope, and stated analysis. A Philippines-based assistant can maintain that chain as preparation work. The owner or editor should retain the decision to publish, narrow, or reject the conclusion.'], [table('Supported conclusion', 'Traceability makes the research decision inspectable', 'NIST, GPO, OECD, ILO synthesis'), table('Not proven', 'That more citations or faster collection improves article quality by itself', 'Scope limitation')]),
    ],
    faqs: [{ q: 'Is three source URLs enough?', a: 'The count is not the test. Each source must be relevant to a material claim and its scope must support the wording.' }, { q: 'Can an assistant approve the conclusion?', a: 'The assistant can prepare evidence and alternatives; an authorised editor should approve public interpretation.' }],
    sources: [{ name: 'U.S. Government Publishing Office Style Manual', url: 'https://www.govinfo.gov/app/details/GPO-STYLEMANUAL-2016', note: 'Editorial treatment of dates, facts, and source-aware writing.' }, { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework', note: 'Governance and risk-management outcomes used as an analytical frame.' }, { name: 'NIST SP 800-53 Revision 5', url: 'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final', note: 'Access, accountability, audit, and configuration control guidance.' }, { name: 'ILO Working from Home Report', url: 'https://www.ilo.org/global/topics/non-standard-employment/publications/WCMS_765806/lang--en/index.htm', note: 'Context on how remote work is organised and experienced.' }], related: ['content-research-source-traceability', 'claim-scope-provenance', 'research-briefing-workflow'], body: []
  },
  {
    slug: 'daily-article-review-queue-design', image: { url: '/images/research-2026-08-20/daily-article-review-queue-design.png', alt: 'Two colleagues sorting article pages through review stages' }, title: 'How should an outsourced article review queue separate evidence from editing?',
    excerpt: 'Research on queue states, review ownership, and return reasons for a steady assistant-supported article routine.', published: '2026-08-20', updated: '2026-08-20', cluster: 'Content operations',
    headlineStat: 'A draft is not ready when it is written; it is ready when evidence and editorial decisions are inspectable.',
    methodology: 'Research question: which states and measures distinguish research completion from editorial readiness in a daily article queue? This analysis uses NIST measurement and governance material, the UK Government Service Manual on measuring success, the National Academies discussion of uncertainty, and ILO remote-work research. It applies those concepts to OutsourcingAssistant.com article preparation and does not prescribe a staffing ratio, universal turnaround time, or quality guarantee.',
    keyStats: ['Research complete and publication ready are different states', 'Return reasons reveal whether the brief, evidence, or draft failed', 'Queue measures need an explicit denominator and exclusion rule'],
    takeaways: ['Use named states such as briefed, researching, drafted, evidence review, editorial review, and approved.', 'Record the reason an article returns instead of treating all rework as the same.', 'Measure the queue to improve the routine, not to turn a small sample into a universal rate.'],
    sections: [
      section('Define readiness as a state transition', ['A content queue becomes difficult to manage when “done” means different things to the researcher, writer, and editor. A source packet may be complete while the thesis remains too broad. A polished draft may still contain a date mismatch or a claim that exceeds its evidence. A useful queue names the transition required at each stage and the person who can make it.', 'For a daily routine, a practical sequence is briefed, researching, evidence packet ready, draft ready, editorial review, revision requested, approved, and published. The assistant can move an item through preparation states when the finish line is explicit. The editor owns the transition into approved public copy. This prevents a time-zone handoff from turning an unfinished decision into a silent publication.'], [table('Preparation state', 'Evidence packet or draft meets its defined local finish line', 'Queue-state design'), table('Approval state', 'Authorised editor accepts claims, dates, and boundaries', 'Governance boundary')]),
      section('Use return reasons as research findings', ['A returned article is not merely a slower article. Its reason can show that the question was unanswerable, that the sources addressed a neighbouring problem, that the niche was missing from the examples, or that the public wording overreached. Recording one primary return reason and one corrective action gives the owner evidence about where the routine needs repair.', 'The UK Government Service Manual’s measurement approach is useful here because a measure should answer a service question. For article work, the question might be whether briefs produce reviewable evidence on the first pass. The denominator must say which articles were eligible, which were excluded because they were cancelled or merged, and whether a correction happened before or after approval. A percentage without those definitions is easy to misread.'], [table('Diagnostic', 'Return reason by state and corrective action', 'UK Government measurement logic'), table('Interpretation limit', 'A small queue sample signals patterns but does not certify all future pages', 'National Academies uncertainty')]),
      section('Separate evidence review from copy review', ['Evidence review asks whether the sources are reputable, relevant, current enough for the claim, and accurately represented. Copy review asks whether the title, structure, examples, language, dates, and conclusion serve the intended reader. The two reviews overlap, but they are not interchangeable. A fluent paragraph can still fail the evidence test, and a well-supported claim can still be irrelevant to a site about practical outsourcing decisions.', 'An assistant can prepare both views in one packet: a claim table for the research reviewer and a draft outline for the editor. The packet should call out unresolved questions rather than hiding them in prose. A separate owner decision field—approve, narrow, request source, or stop—makes the handoff explicit. That is especially important when the reviewer and assistant work in different time zones.'], [table('Evidence check', 'Source fit, scope, accuracy, limitations', 'NIST and National Academies framing'), table('Editorial check', 'Audience, niche, structure, tone, date, and public boundaries', 'Site-specific review rubric')]),
      section('Limitations and conclusion', ['The evidence does not establish a universal queue design. Topic difficulty, source volatility, reviewer availability, and the consequence of a wrong claim all change the appropriate review depth. A routine that works for a low-risk process explainer may be inadequate for an article touching security, employment, privacy, or regulated decisions.', 'The evidence-led conclusion is that a daily article queue is more reliable when it treats research, drafting, review, revision, and approval as separate observable states. OutsourcingAssistant.com can delegate preparation and measurement of those states while keeping public publication with an authorised editor. The next improvement should follow the recorded return pattern, not a generic throughput target.'], [table('Supported conclusion', 'Visible state transitions make review work and ownership clearer', 'NIST, UK Government, ILO synthesis'), table('Boundary', 'No universal queue timing or pass-rate claim', 'Scope limitation')]),
    ],
    faqs: [{ q: 'Does “draft complete” mean publishable?', a: 'No. It means the draft has met its preparation finish line and still needs the defined editorial and evidence gates.' }, { q: 'What is the most useful queue metric?', a: 'Start with time in each state and the reason for returns, with the eligible population documented.' }],
    sources: [{ name: 'UK Government Service Manual: Measuring Success', url: 'https://www.gov.uk/service-manual/measuring-success', note: 'Measurement design, service questions, and honest interpretation.' }, { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework', note: 'Governance and risk-management outcomes used as an analytical frame.' }, { name: 'NIST SP 800-53 Revision 5', url: 'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final', note: 'Access, accountability, audit, and configuration control guidance.' }, { name: 'ILO Working from Home Report', url: 'https://www.ilo.org/global/topics/non-standard-employment/publications/WCMS_765806/lang--en/index.htm', note: 'Context on how remote work is organised and experienced.' }], related: ['assistant-quality-sampling-plan', 'queue-denominator-integrity', 'assistant-editorial-review-sample-size'], body: []
  },
  {
    slug: 'outsourced-content-brief-evidence-scope', image: { url: '/images/research-2026-08-20/outsourced-content-brief-evidence-scope.png', alt: 'Content strategist preparing a focused research brief' }, title: 'What should an outsourcing brief specify before daily article research begins?',
    excerpt: 'A research-led examination of audience, decision, evidence scope, and role boundaries in outsourced content briefs.', published: '2026-08-20', updated: '2026-08-20', cluster: 'Research operations',
    headlineStat: 'A content brief is a decision boundary: it tells the assistant what to investigate and what not to infer.',
    methodology: 'Research question: which brief fields reduce ambiguity when a Philippines-based assistant researches articles about outsourcing and daily operations? This desk review uses OECD productivity measurement guidance, NIST governance principles, the U.S. Bureau of Labor Statistics Occupational Outlook Handbook, and the GPO Style Manual. It examines brief design, not writing talent or business outcomes, and does not supply legal, employment, or market advice.',
    keyStats: ['Audience and decision are different fields', 'Evidence scope should identify population, period, and source class', 'Role boundaries belong in the brief before access is granted'],
    takeaways: ['Name the reader’s decision, not only the keyword or topic.', 'Specify what evidence counts and what the article must not claim.', 'Give the assistant an escalation route for gaps, conflicts, and sensitive interpretations.'],
    sections: [
      section('A topic is not a research question', ['“Write about outsourced assistants” describes a subject but not a decision. A useful brief asks whether a specific operating choice, risk, benchmark, or role boundary can be explained for a defined reader. For OutsourcingAssistant.com, that might be how an owner separates preparation from approval in a recurring administrative queue. The question should make the niche unavoidable in the thesis, examples, and conclusion.', 'The distinction matters because a broad keyword encourages generic material that could belong to any productivity site. A research question gives the assistant a test: what does the evidence help the reader decide, what remains uncertain, and which company-specific facts are unavailable? The brief should record those limits before research begins.'], [table('Weak input', 'Topic or keyword without a decision', 'Brief-quality analysis'), table('Strong input', 'Reader, decision, operating context, evidence scope, and boundary', 'Research-question design')]),
      section('Specify evidence before collecting it', ['Evidence scope should state the source classes that fit the question, the period that matters, and the population being discussed. An occupational outlook page can contextualise administrative work; it cannot estimate one owner’s assistant output. Productivity guidance can clarify inputs and outputs; it cannot prove that a new delegation arrangement will create a particular gain. These are not minor footnotes. They determine whether a claim can be written at all.', 'The assistant can build a source plan with primary authorities, standards, official statistics, and relevant research. Each planned source should have a reason for inclusion and a known limitation. If the search finds commentary instead of primary material, the packet should flag that substitution for review. This is more useful than gathering a large number of links that all repeat an unsupported assertion.'], [table('Scope field', 'Population, unit, method, period, jurisdiction, and source class', 'OECD and BLS definitions'), table('Stop condition', 'No source can support the proposed claim within its stated scope', 'Evidence-boundary rule')]),
      section('Make role boundaries operational', ['A brief should say what the assistant may prepare and what an authorised owner must decide. In daily article work, preparation can include question refinement, source collection, claim notes, outline drafting, image brief preparation, and a limitations section. Publication approval, invented company facts, unsupported results, and high-consequence interpretations remain outside that lane. A boundary is useful only when it tells the assistant what to do next: pause, preserve the evidence, and ask a specific question.', 'NIST governance language helps frame this as accountability rather than suspicion. The operating team needs a named owner, a review event, and a record of the decision. Giving broad tool access does not eliminate the need for those controls. A well-written brief makes the intended authority visible before the work starts.'], [table('May prepare', 'Sources, comparisons, draft language, and open questions', 'Role-boundary analysis'), table('Must escalate', 'Unsupported claim, sensitive inference, invented fact, or approval decision', 'NIST governance frame')]),
      section('Limitations and conclusion', ['A brief cannot resolve missing company data, conflicting public definitions, or a question that is too broad for the available evidence. It also cannot determine the best editorial judgement in every case. The owner may need to narrow a topic after research begins. That is a valid finding, not a failure of the assistant.', 'The evidence-led conclusion is that a daily outsourced article routine improves when the brief defines a decision, evidence scope, and authority boundary before drafting. The assistant can make the research process more legible by showing what was observed, what was inferred, and what remains unanswered. The editor retains the decision to publish a bounded conclusion for the intended audience.'], [table('Supported conclusion', 'Brief specificity improves evidence fit and reviewability', 'OECD, BLS, NIST, GPO synthesis'), table('Not proven', 'That any fixed brief template guarantees article quality', 'Scope limitation')]),
    ],
    faqs: [{ q: 'Should a brief start with a keyword?', a: 'It can include one, but the research question and reader decision should govern the topic.' }, { q: 'Who owns a missing evidence decision?', a: 'The assistant should flag the gap; the owner or editor decides whether to narrow, pause, or change the question.' }],
    sources: [{ name: 'OECD: Measuring Productivity', url: 'https://www.oecd.org/en/topics/sub-issues/measuring-productivity.html', note: 'Definitions of inputs, outputs, units, and limits in operational claims.' }, { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework', note: 'Governance and risk-management outcomes used as an analytical frame.' }, { name: 'NIST SP 800-53 Revision 5', url: 'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final', note: 'Access, accountability, audit, and configuration control guidance.' }, { name: 'ILO Working from Home Report', url: 'https://www.ilo.org/global/topics/non-standard-employment/publications/WCMS_765806/lang--en/index.htm', note: 'Context on how remote work is organised and experienced.' }], related: ['assistant-research-brief-source-fit', 'content-research-source-traceability', 'input-completeness-baseline'], body: []
  },
  {
    slug: 'article-correction-loop-for-outsourced-research', image: { url: '/images/research-2026-08-20/article-correction-loop-for-outsourced-research.png', alt: 'Editor and assistant reviewing corrections to an article' }, title: 'What can a correction loop teach an outsourced daily research routine?',
    excerpt: 'How to use corrections as evidence about briefs, sources, and role boundaries without treating every edit as an assistant failure.', published: '2026-08-20', updated: '2026-08-20', cluster: 'Quality systems',
    headlineStat: 'A correction is most valuable when its cause is classified and returned to the part of the routine that created it.',
    methodology: 'Research question: how should a small team interpret corrections to daily research articles prepared by an assistant? This review draws on NIST continuous-improvement and measurement material, the UK Government Service Manual, the National Academies treatment of uncertainty, and the GPO Style Manual. It applies the evidence to a bounded publishing queue; it does not estimate error rates, assign blame, or claim that correction volume alone measures writing quality.',
    keyStats: ['Corrections may originate in the brief, source, draft, review, or publication gate', 'A correction log needs examples and causes, not only counts', 'Repeated corrections are evidence about the routine’s design'],
    takeaways: ['Classify the correction before changing the role or access.', 'Preserve the original sentence, evidence, decision, and revised wording.', 'Use recurring causes to improve the brief or review gate rather than silently relying on memory.'],
    sections: [
      section('A correction is a system observation', ['When an editor changes an article, the immediate temptation is to label the event as a writing mistake. That can be wrong. The source may have been too broad, the brief may have asked an unanswerable question, the draft may have converted analysis into fact, or the date and route may have been bound incorrectly. A correction loop starts by classifying which part of the system produced the defect.', 'This matters in outsourced work because role expansion is an expensive response to a vague signal. If the problem is a missing example in the brief, giving the assistant more access will not repair it. If the source is unsuitable, asking for a longer article adds volume without evidence. A correction record should make the causal hypothesis explicit and testable.'], [table('Correction fields', 'Original wording, trigger, evidence, cause class, decision, revised wording', 'Measurement design'), table('Avoid', 'Treating every correction as a person-level performance score', 'Fair-review boundary')]),
      section('Use a small taxonomy of causes', ['A useful taxonomy can include question, source fit, scope, factual representation, niche relevance, structure, prohibited language, date or route, and editorial clarity. The list should be short enough to use consistently and specific enough to change the next step. A single correction may have more than one cause, but the reviewer should identify the primary repair location.', 'The UK Government Service Manual’s measurement guidance supports tying a metric to an improvement question. If the team wants to know whether briefs are becoming clearer, it should count brief-caused returns separately from source-caused returns. If it wants to know whether a new date gate works, it should inspect date corrections as their own class. Combining everything into a pass rate hides the intervention.'], [table('Repair location', 'Brief, source plan, draft, review rubric, or route gate', 'Correction-loop method'), table('Useful measure', 'Cause count with reviewed denominator and examples', 'UK Government measurement logic')]),
      section('Preserve fairness across time zones', ['A correction log should show whether the assistant had the information and authority needed to avoid the issue. If the brief omitted the target reader, the correction is partly a design problem. If the source was inaccessible or ambiguous, the assistant should not be penalised for escalating it. If the editor changed the thesis after drafting, the record should distinguish scope change from execution error.', 'The assistant can prepare the log, group repeated causes, and propose a change to an example or gate. An authorised editor decides whether the change becomes a new instruction. Publishing the correction is also a decision: the team should not imply that a routine was perfect merely because the final page was repaired before release.'], [table('Fairness check', 'Was the input, evidence, authority, and review event available?', 'ILO remote-work context'), table('Escalation', 'Repeated or consequential defects require owner review of the routine', 'NIST governance frame')]),
      section('Limitations and conclusion', ['A correction sample cannot reveal defects that no reviewer noticed, and cause categories may reflect reviewer judgement. A lower correction count may mean better work, easier topics, or weaker review. The team should therefore preserve borderline examples and note changes in population, topic difficulty, and rubric. The record is evidence for improvement, not a certification.', 'The evidence-led conclusion is that corrections improve a daily research routine when they are treated as observations about briefs, sources, decisions, and gates. An outsourced assistant can maintain the evidence trail and prepare pattern analysis. The owner remains responsible for deciding which process changes are approved and which public claims are safe.'], [table('Supported conclusion', 'Cause-coded corrections guide targeted routine improvements', 'NIST, UK Government, National Academies synthesis'), table('Boundary', 'No universal defect rate or blame assignment', 'Scope limitation')]),
    ],
    faqs: [{ q: 'Should every correction be counted as an error?', a: 'Count it as an observation, then classify whether the cause was the brief, evidence, draft, review, or a changed decision.' }, { q: 'Can an assistant change the routine after seeing a pattern?', a: 'It can propose a change with examples; an authorised owner should approve new instructions or authority.' }],
    sources: [{ name: 'National Academies: Reproducibility and Replicability in Science', url: 'https://nap.nationalacademies.org/catalog/25303/reproducibility-and-replicability-in-science', note: 'Uncertainty, transparency, and limits on interpreting small samples.' }, { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework', note: 'Governance and risk-management outcomes used as an analytical frame.' }, { name: 'NIST SP 800-53 Revision 5', url: 'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final', note: 'Access, accountability, audit, and configuration control guidance.' }, { name: 'ILO Working from Home Report', url: 'https://www.ilo.org/global/topics/non-standard-employment/publications/WCMS_765806/lang--en/index.htm', note: 'Context on how remote work is organised and experienced.' }], related: ['assistant-quality-sampling-plan', 'queue-denominator-integrity', 'sop-exception-pattern-analysis'], body: []
  },
  {
    slug: 'owner-review-capacity-for-daily-research', image: { url: '/images/research-2026-08-20/owner-review-capacity-for-daily-research.png', alt: 'Remote assistant and owner reviewing a research packet' }, title: 'Does daily research capacity include the owner review window?',
    excerpt: 'A bounded study of preparation hours, editorial decision capacity, and time-zone handoffs in outsourced article publishing.', published: '2026-08-20', updated: '2026-08-20', cluster: 'Distributed work',
    headlineStat: 'Preparation capacity is not publication capacity until an authorised reviewer can make the next decision.',
    methodology: 'Research question: when does a Philippines-based assistant’s preparation schedule create useful daily research capacity rather than a queue waiting for owner review? This analysis compares the ILO Working from Home report, Microsoft Work Trend Index observations, NIST governance principles, and the UK Government Service Manual’s measurement guidance. It distinguishes preparation, evidence review, editorial review, and approval; it does not estimate output, recommend a time zone, or prove a productivity gain.',
    keyStats: ['Ready-for-review time and decision time should be measured separately', 'Waiting reasons distinguish coordination from evidence problems', 'Time-zone coverage cannot transfer editorial authority'],
    takeaways: ['Define the owner review event before setting a preparation cadence.', 'Record whether work waits for a decision, a source, a clarification, or a revision.', 'Use overlap to improve decisions, not to imply that unreviewed drafts are complete.'],
    sections: [
      section('The capacity question', ['A daily article routine can look productive when drafts arrive overnight, yet still lack capacity if the owner cannot inspect sources and approve the conclusion. The relevant question is not how many hours someone worked. It is whether an article can move through the next authorised state within the intended publishing rhythm. Preparation and decision are different resources.', 'The ILO research supports examining remote work through its organisation and conditions rather than assuming geography has one effect. Microsoft’s broad collaboration observations may inform hypotheses about asynchronous work, but they do not measure this company’s queue. A local record should therefore show when a page became ready, when review began, what decision was made, and why any delay occurred.'], [table('Preparation capacity', 'Time and skill available to collect evidence and draft', 'Queue-state definition'), table('Decision capacity', 'Authorised time to assess evidence and approve or return', 'NIST governance frame')]),
      section('Design a fair local comparison', ['A comparison of review windows should keep the article brief, source requirements, editorial rubric, and approximate topic difficulty visible. Compare a period with a scheduled review event to a period without one, while recording exceptions. If waiting falls, the evidence supports a coordination finding. It does not prove that the assistant became more skilled or that one geography is universally better.', 'The most useful diagnostic is the waiting reason. “Owner unavailable” points toward scheduling. “Source population unclear” points toward research. “Thesis too broad” points toward the brief. “Revision not yet complete” points toward drafting. A single turnaround number collapses these distinct problems and can encourage the wrong intervention.'], [table('Primary measure', 'Time from evidence-ready to authorised decision', 'UK Government measurement logic'), table('Diagnostic', 'Waiting and return reason by article state', 'Local queue sample')]),
      section('What can safely happen overnight', ['An assistant can refine the research question, gather three or more reputable sources, record scope and limitations, draft a claim table, prepare an outline, and identify the decisions an editor must make. That work creates a useful morning review only when the packet distinguishes observed facts from analysis. A polished draft should not conceal an unresolved source conflict or an invented company-specific example.', 'The owner can use the review window to accept, narrow, request another source, or stop the article. Those decisions should be recorded in the handoff. If no review event exists, the correct state is waiting, not approved. This simple distinction protects the public site from treating a time-zone advantage as a substitute for editorial accountability.'], [table('Safe overnight output', 'Evidence packet, bounded draft, limitations, and questions', 'Role-boundary analysis'), table('Hard stop', 'Publication or consequential interpretation without authorised review', 'Editorial control')]),
      section('Limitations and conclusion', ['The public research does not identify the ideal overlap duration for every small team. Team size, source volatility, reviewer habits, topic risk, and the cost of a wrong claim all matter. Broad workforce studies also cannot isolate the effect of a Philippines-based assistant on one publishing queue. A local sample must state those limits.', 'A further limitation is that review-window evidence can be confounded by the article itself. A page with a narrow question and stable sources may move quickly, while a page about a changing rule may require several decisions even when the handoff is excellent. The record should therefore retain topic, source volatility, clarification count, and revision reason alongside elapsed time. Otherwise an apparently faster window may simply contain easier research, and an apparently slower one may reflect a responsible refusal to overstate evidence. This is why the comparison should be repeated across more than one release period and interpreted with the queue’s inclusion and exclusion rules visible.', 'The evidence-led conclusion is that daily research capacity includes owner review only when the review event is scheduled, authorised, and measured as a separate state. A remote assistant can extend preparation coverage, but the company gains publication capacity only when the evidence reaches a decision-maker. That is a coordination conclusion, not a staffing promise.'], [table('Supported conclusion', 'Capacity requires preparation plus accountable review', 'ILO, Microsoft, NIST synthesis'), table('Not proven', 'Universal time-zone advantage or staffing ratio', 'Scope limitation')]),
    ],
    faqs: [{ q: 'Is an overnight draft ready to publish?', a: 'No. It is ready for the defined evidence and editorial review event.' }, { q: 'What should the handoff say?', a: 'State what is complete, what evidence supports it, what remains uncertain, and the exact owner decision required.' }],
    sources: [{ name: 'Microsoft Work Trend Index', url: 'https://www.microsoft.com/en-us/worklab/work-trend-index', note: 'Broad observations about distributed collaboration used as context, not a company benchmark.' }, { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework', note: 'Governance and risk-management outcomes used as an analytical frame.' }, { name: 'NIST SP 800-53 Revision 5', url: 'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final', note: 'Access, accountability, audit, and configuration control guidance.' }, { name: 'ILO Working from Home Report', url: 'https://www.ilo.org/global/topics/non-standard-employment/publications/WCMS_765806/lang--en/index.htm', note: 'Context on how remote work is organised and experienced.' }], related: ['review-window-coverage', 'time-zone-handoff-design', 'handoff-state-transitions'], body: []
  },
];

export const researchBatch20260820: readonly ResearchPost[] = records;
