import type { ResearchPost, ResearchSource, ResearchSection } from './fleet-content';

const sources: readonly ResearchSource[] = [
  {name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework',note:'Governance and risk-management outcomes.'},
  {name:'NIST SP 800-53 Revision 5',url:'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final',note:'Access, accountability, audit, and system-control guidance.'},
  {name:'GAO Assessing Data Reliability',url:'https://www.gao.gov/products/gao-20-283g',note:'Framework for judging whether evidence is fit for its intended use.'},
  {name:'UK Government Service Manual: Measuring success',url:'https://www.gov.uk/service-manual/measuring-success',note:'Guidance on choosing and interpreting service measures.'},
  {name:'ILO Working from Home',url:'https://www.ilo.org/publications/working-home-estimating-worldwide-potential',note:'Remote-work organisation and limits of broad estimates.'}
];
type RSpec={slug:string;title:string;excerpt:string;cluster:string;question:string;unit:string;signal:string;limit:string;image:string};
const specs:RSpec[]=[
 {slug:'assistant-queue-age-vs-risk-priority',title:'Queue age is not risk priority in delegated assistant work',excerpt:'A source-led framework for separating elapsed waiting time from consequence, uncertainty, and reversibility.',cluster:'Operations research',question:'Should the oldest assistant task always move first?',unit:'one queue item with timestamps, consequence class, uncertainty, and next owner',signal:'Age describes waiting; risk priority also depends on what can happen, whether the action is reversible, and who has authority.',limit:'The cited sources do not validate a universal scoring formula or prove that one priority rule improves every team.',image:'/images/research-2026-08-23/research-stop-rules-source-conflict.png'},
 {slug:'delegated-content-citation-decay-observation',title:'Observing citation decay in a delegated article library',excerpt:'How to record broken links, changed source language, and claim volatility without treating every old citation as invalid.',cluster:'Content research',question:'Which published citations should an assistant recheck first?',unit:'one material article claim linked to one source and a dated verification',signal:'A useful recheck rule combines source volatility, claim consequence, link status, and time since verification.',limit:'A recheck can show that a source moved or changed; it cannot by itself determine whether the article’s conclusion remains valid.',image:'/images/research-2026-08-21/source-freshness-for-daily-outsourced-articles.png'},
 {slug:'virtual-assistant-exception-recurrence-measure',title:'Measuring recurring exceptions in virtual assistant routines',excerpt:'A bounded method for distinguishing a one-off awkward case from a workflow rule that needs revision.',cluster:'Quality systems',question:'When does an exception justify changing an SOP?',unit:'one exception with its triggering condition, disposition, reviewer, and later recurrence',signal:'Recurrence counts become useful only when cases use the same definition and preserve different outcomes.',limit:'Small counts can identify local review needs but do not establish a universal threshold for changing procedures.',image:'/images/research-2026-09-03/manager-feedback-sop-change-thresholds.png'},
 {slug:'philippines-assistant-review-window-interruption-study',title:'Studying interruption inside Philippines assistant review windows',excerpt:'A careful way to separate planned handoffs, clarification waits, and unplanned interruptions in distributed work.',cluster:'Distributed work',question:'Do interruptions or time-zone design explain a missed review window?',unit:'one planned work block with interruption start, cause, owner, recovery point, and output state',signal:'A timestamped state record can separate active work from waiting and interruption, but interpretation still requires case context.',limit:'This design does not measure cognitive load directly or support comparisons between individuals without equivalent work and conditions.',image:'/images/research-2026-08-21/philippines-assistant-article-handoff-window.png'},
 {slug:'assistant-source-conflict-resolution-record',title:'Evidence records for source conflicts in assistant research',excerpt:'How a research assistant can preserve disagreement and prepare a decision without manufacturing consensus.',cluster:'Research operations',question:'What should happen when reputable sources disagree?',unit:'one contested claim with exact source scope, date, population, finding, and owner disposition',signal:'Conflict becomes reviewable when each source is attached to the precise claim it supports and its limits remain visible.',limit:'The record improves transparency; it does not confer subject-matter authority or resolve legal, medical, financial, or policy disputes.',image:'/images/research-2026-09-03/uncertainty-preservation-summary-transfers.png'}
];
const section=(heading:string,paragraphs:string[],rows:ResearchSection['rows']):ResearchSection=>({heading,paragraphs,rows});
const make=(x:RSpec):ResearchPost=>({slug:x.slug,title:x.title,excerpt:x.excerpt,cluster:x.cluster,published:'2026-09-04',updated:'2026-09-04',image:{url:x.image,alt:`Evidence review illustration for ${x.title}`},headlineStat:x.signal,
 methodology:`This is a structured desk review of five named public sources. The proposed unit of analysis is ${x.unit}. Source principles are separated from the author’s operational recommendations; no causal or universal performance claim is made.`,
 keyStats:['Five reputable public sources reviewed',`Unit of analysis: ${x.unit}`,'Four fields required before interpretation: evidence, state, owner, and time'],
 takeaways:[x.signal,'Keep raw observations beside any category or score.','Route consequential interpretation to the authorised owner.'],
 sections:[
  section('Research question and evidence scope',[`${x.question} The sources provide governance, measurement, evidence-quality, and remote-work context. They do not study this exact OutsourcingAssistant.com workflow, so the operating model below is an evidence-informed proposal rather than a validated benchmark.`,`The analysis uses ${x.unit}. Naming that unit prevents a team from mixing individual messages, whole projects, and owner decisions in one denominator.`],[{label:'Evidence set',value:'Five named public sources',source:'Review protocol'},{label:'Unit',value:x.unit,source:'Proposed measurement design'}]),
  section('What to record',[`Record the original request, source evidence, current state, responsible owner, time of each state change, and final disposition. Preserve missing or conflicting values rather than completing them from memory.`,`${x.signal} For a Philippines-based assistant and an owner in another time zone, also record the expected review window. That distinguishes intentional overnight waiting from an unowned delay.`],[{label:'Observation',value:'Source, state, owner, timestamp, disposition',source:'GAO evidence-fitness principles'},{label:'Control context',value:'Purpose and accountability remain explicit',source:'NIST CSF 2.0 and SP 800-53'}]),
  section('Interpretation and decision rule',[`Compare like cases over a stated period and show the full denominator, including incomplete, returned, and escalated items. A clean subset can diagnose a narrow workflow, but it should not be presented as the performance of the whole queue.`,`Use the observation to decide whether the brief, access, example, review capacity, or escalation path needs attention. Do not convert a descriptive pattern into a judgment about a person or outsourcing location.`],[{label:'Safe conclusion',value:'A local process signal that merits review',source:'UK Government Service Manual'},{label:'Unsafe conclusion',value:'A causal claim about staffing or geography',source:'ILO remote-work context'}]),
  section('Limitations and next test',[x.limit,`The next useful test is prospective: define the fields and categories before the review period, train reviewers on two edge cases, and inspect disagreements. Report missing records and classification changes alongside the result. This makes uncertainty part of the evidence rather than an editorial footnote.`],[{label:'Primary limitation',value:x.limit,source:'Scope assessment'},{label:'Next step',value:'Prospective collection with documented categories',source:'Author recommendation'}])
 ],
 faqs:[{q:x.question,a:'Use a documented evidence record and the stated decision rule; elapsed time or a single label is not enough.'},{q:'Does this establish a benchmark for virtual assistants?',a:'No. It is a local measurement design grounded in public guidance, not a validated industry benchmark.'},{q:'Who interprets consequential cases?',a:'The named business or subject-matter owner. The assistant can prepare the evidence and preserve uncertainty.'}],sources,related:['claim-scope-provenance','queue-denominator-integrity','philippines-assistant-content-review-overlap'],body:[]
});
export const researchBatch20260904: readonly ResearchPost[] = specs.map(make);
