import type { ResearchPost, ResearchSection, ResearchSource } from './fleet-content';

const sources: readonly ResearchSource[] = [
 {name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework',note:'Primary U.S. government framework for governance, responsibility, and risk outcomes.'},
 {name:'U.S. GAO Assessing Data Reliability',url:'https://www.gao.gov/products/gao-20-283g',note:'Primary methodology guidance for testing whether data is sufficiently reliable for its intended use.'},
 {name:'UK Government Service Manual: Measuring success',url:'https://www.gov.uk/service-manual/measuring-success',note:'Official guidance on choosing measures and interpreting service data.'},
 {name:'NIST SP 800-53 Revision 5, Update 1',url:'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final',note:'Primary controls guidance for access, records, accountability, and review.'},
 {name:'International Labour Organization, Working from Home',url:'https://www.ilo.org/publications/working-home-estimating-worldwide-potential',note:'Primary international research on remote-work feasibility and the limits of broad estimates.'}
];
type Spec={slug:string;title:string;excerpt:string;cluster:string;question:string;unit:string;method:string;finding:string;inference:string;limitation:string;decision:string;image:string};
const specs:Spec[]=[
 {slug:'assistant-clarification-round-trip-study',title:'Measuring clarification round trips in delegated article work',excerpt:'A local study design for separating productive clarification from repeated questions caused by missing brief evidence.',cluster:'Content operations research',question:'Which clarification exchanges improve an article decision, and which repeat information that should have been present at intake?',unit:'one article assignment from accepted brief through owner approval, with each question, response, source change, and decision timestamped',method:'Review a consecutive set of assignments. Two reviewers classify each exchange as new scope, missing evidence, conflicting evidence, approval, or avoidable repetition, then retain disagreements.',finding:'A message count alone cannot distinguish careful research from a weak intake. The reason for each exchange and the decision it changes must stay attached.',inference:'The records can describe where clarification occurs in this OutsourcingAssistant.com routine. They cannot prove that a person, location, or time-zone arrangement caused it.',limitation:'Private-chat omissions and inconsistent timestamps can undercount exchanges. A short review period may not represent seasonal or unusually complex articles.',decision:'Use the categories to revise one brief field at a time, then compare the same article class in a later period.',image:'/images/research-2026-09-03/brief-omission-exception-cluster-analysis.png'},
 {slug:'outsourced-content-correction-time-decomposition',title:'Decomposing correction time in outsourced content reviews',excerpt:'A timestamp method for distinguishing detection, evidence retrieval, owner decision, editing, and release during article corrections.',cluster:'Quality research',question:'Where does elapsed time accumulate after a potential article defect is reported?',unit:'one correction case with report time, claim location, evidence request, evidence receipt, decision, edit, validation, and release',method:'Follow consecutive correction cases and calculate each waiting interval separately. Classify active work and waiting time from retained system events rather than recollection.',finding:'Total correction time hides whether the constraint was research, authority, editing, or deployment. Separate intervals make the queue diagnosable.',inference:'The study can identify local delay patterns and missing records. It cannot establish individual productivity or the counterfactual release time under another staffing model.',limitation:'Parallel work, offline review, and missing event logs can distort interval estimates. Different consequence classes should not be combined into one benchmark.',decision:'Route improvements to the interval with observable evidence, while preserving owner approval for changes to public claims.',image:'/images/research-2026-08-23/article-correction-burden-delegated-research.png'},
 {slug:'virtual-assistant-source-access-failure-log-analysis',title:'Analysing source-access failures in assistant research queues',excerpt:'A claim-level method for recording paywalls, broken links, blocked documents, and inaccessible source formats without silently substituting evidence.',cluster:'Research operations',question:'How often does source access prevent a delegated researcher from checking the evidence required for a material claim?',unit:'one requested source and claim pair, including access route, failure type, attempt time, permitted alternative, reviewer response, and final claim state',method:'Record every access failure during a fixed run of research briefs. Verify a sample from a second environment and report access failures separately from evidence-quality judgments.',finding:'An accessible substitute is not automatically equivalent. Authority, population, period, definitions, and the supported claim may change.',inference:'The log can show which sources failed in the observed workflow. It cannot infer the publisher’s intent or predict availability outside the recorded time and environment.',limitation:'Authentication rules, geography, temporary outages, and assistive-technology needs may produce different results for other researchers.',decision:'Ask the owner to approve a source change or narrow the claim; never fill the evidence gap with an uncited assertion.',image:'/images/research-2026-08-21/source-freshness-for-daily-outsourced-articles.png'},
 {slug:'daily-article-review-sample-coverage-study',title:'Testing sample coverage in a daily article review routine',excerpt:'A stratified review design for checking whether routine samples include high-consequence claims, new templates, exceptions, and ordinary pages.',cluster:'Editorial governance research',question:'Does the review sample represent the failure modes the publishing owner needs to see?',unit:'one published article tagged by family, template, topic, consequence class, exception state, reviewer, and observed defect',method:'Define strata before selection, draw a reproducible sample from each, and review all high-consequence exceptions. Compare sampled and unsampled article characteristics without claiming unseen defect counts.',finding:'A large convenience sample may still miss rare but consequential work. Coverage depends on the selection frame, not only the number reviewed.',inference:'Observed defects support conclusions about reviewed pages and documented strata. Estimating an overall defect rate requires a valid sampling design and enough observations.',limitation:'Small strata yield unstable percentages, and inconsistent tagging can make coverage look broader than it is. Reviewer knowledge may also affect classification.',decision:'Use findings to adjust the next sampling frame and the SOP, not to rank workers from a handful of pages.',image:'/images/research-2026-08-21/article-quality-sampling-for-outsourced-routines.png'},
 {slug:'owner-review-interruption-cost-observation',title:'Observing interruption cost in owner article reviews',excerpt:'A bounded diary method for studying fragmented review windows without treating elapsed time as a personal productivity score.',cluster:'Distributed work research',question:'Which interruptions prevent an owner from completing a decision-ready article review in one session?',unit:'one planned review window with start state, interruption category, resume point, context reconstruction, decision, and end state',method:'Use a short prospective diary linked to article events. The owner records interruptions in broad categories, and the analysis reports medians and distributions without collecting private message content.',finding:'Calendar duration, active review time, and waiting time answer different questions. Combining them obscures whether the article or the surrounding work caused delay.',inference:'The observations can inform this team’s review-window design. They do not show that interruptions caused a quality outcome or that another owner would work similarly.',limitation:'Self-recording changes behaviour and misses unnoticed context switching. A busy week may not represent normal operations, and privacy limits useful detail.',decision:'Test one scheduling or handoff change at a time and retain the original observations for comparison.',image:'/images/research-2026-08-20/owner-review-capacity-for-daily-research.png'}
];
const section=(heading:string,paragraphs:string[],rows:ResearchSection['rows']):ResearchSection=>({heading,paragraphs,rows});
const make=(x:Spec):ResearchPost=>({slug:x.slug,title:x.title,excerpt:x.excerpt,published:'2026-09-10',updated:'2026-09-10',cluster:x.cluster,image:{url:x.image,alt:`Research workflow illustration for ${x.title}`},headlineStat:'One observation unit is defined before collection; no universal performance target is claimed.',methodology:`Research question: ${x.question} Scope: OutsourcingAssistant.com's daily article routine and ${x.unit}. Method: ${x.method} Evidence basis: five named primary or official sources provide governance and measurement principles; none studies this exact workflow. Inference boundary: ${x.inference} Limitations: ${x.limitation}`,
 keyStats:[`Observation unit: ${x.unit}.`,'Evidence set: five named primary or official publications.','Claim boundary: results describe the stated local period and recorded cases only.'],takeaways:[x.finding,x.decision,x.inference],sources,related:['content-research-source-traceability','research-publishing-checklist','assistant-quality-scorecard'],body:[x.question,x.method,x.finding,x.inference,x.limitation],sections:[
  section('Research question and scope',[x.question,`The unit of analysis is ${x.unit}. The scope excludes worker ranking, market benchmarks, and causal claims about outsourcing or geography.`],[{label:'Population',value:'Consecutive eligible records from one declared review period',source:'Proposed local protocol'},{label:'Unit',value:x.unit,source:'Pre-specified study design'}]),
  section('Methodology',[x.method,'Keep the selection rule, codebook, raw observations, reviewer disagreements, and exclusions. Report missing data instead of converting it into a favourable assumption.'],[{label:'Selection',value:'Consecutive or reproducibly sampled eligible records',source:'GAO data reliability guidance'},{label:'Reliability check',value:'Second review of a documented sample',source:'GAO data reliability guidance'}]),
  section('What the evidence can support',[x.finding,x.decision],[{label:'Descriptive claim',value:'Supported only for the observed records and stated period',source:'UK Government Service Manual'},{label:'Operating use',value:'Choose a bounded process test for the next comparable period',source:'NIST CSF 2.0'}]),
  section('Inference boundaries',[x.inference,'Association, sequence, and elapsed time do not establish cause. Any proposed explanation must remain labelled as a hypothesis until the design tests it.'],[{label:'Permitted inference',value:'Description of recorded states, intervals, and classifications',source:'Study protocol'},{label:'Excluded inference',value:'Individual fault, universal rate, or geographic cause',source:'Pre-specified boundary'}]),
  section('Limitations',[x.limitation,'Publish exclusions, missing fields, classification disagreements, and workflow changes alongside any result. Do not pool unlike article or consequence classes merely to create a larger number.'],[{label:'Known constraints',value:x.limitation,source:'Protocol limitations log'},{label:'Response',value:'Narrow the claim and preserve missingness',source:'GAO data reliability guidance'}]),
  section('References and application',['The reference list below contains the exact public pages used for the study framework. These sources support governance and measurement choices, not a claim that this local intervention has already been validated.','Before applying a result, the publishing owner should inspect the raw cases, approve the interpretation, and record any SOP change with an effective date.'],sources.map(s=>({label:s.name,value:s.note,source:s.url})))
 ],faqs:[{q:'Does this research establish a benchmark?',a:'No. It describes a local study design and limits any result to the declared records and period.'},{q:'Can the findings identify individual performance?',a:'No. The method examines workflow evidence and does not support worker ranking or causal attribution.'},{q:'Who approves a process change?',a:'The publishing owner reviews the raw observations, limitations, and proposed test before changing the SOP.'}]});
export const researchBatch20260910: readonly ResearchPost[] = specs.map(make);
