import type { ResearchPost } from './fleet-content';

type Spec = { slug: string; title: string; excerpt: string; cluster: string; question: string; finding: string; method: string; limit: string; pilot: string };
const specs: Spec[] = [
  { slug: 'delegated-queue-reopen-rate-interpretation', title: 'What does a reopen rate reveal about delegated queue quality?', excerpt: 'A bounded study separating genuine rework from policy changes, new evidence, and premature closure.', cluster: 'Quality research', question: 'whether reopened items identify a correctable weakness in the delegated workflow', finding: 'A reopen rate is useful only when each item retains its prior disposition and a specific reason for returning to work.', method: 'Define the eligible closed queue and record reopen time, initiator, reason, prior evidence, new evidence, defect stage, and final disposition.', limit: 'A reopened item is not automatically an assistant error; customers, owners, policies, and source systems can introduce new facts after closure.', pilot: 'Code four weeks of reopened items with a short reason dictionary and double-review a sample for classification agreement.' },
  { slug: 'assistant-handoff-question-readiness-study', title: 'How can teams measure whether assistant handoff questions are ready to answer?', excerpt: 'Research on evidence completeness in questions sent across a time-zone handoff.', cluster: 'Distributed work', question: 'whether an owner can decide from the first handoff without reconstructing the case', finding: 'Question readiness requires a named decision, source record, checks attempted, boundary reached, and time by which an answer is useful.', method: 'Sample handoff questions and record the decision requested, evidence, attempted checks, consequence of waiting, and next permitted action.', limit: 'Fast replies can hide incomplete handoffs, while complex cases may require dialogue even when the first packet is complete.', pilot: 'Score one recurring queue for two weeks, revise one missing template field, and compare first-response decision completeness.' },
  { slug: 'outsourced-content-source-reuse-concentration', title: 'When does source reuse narrow outsourced content research?', excerpt: 'A method for observing source concentration without treating a high URL count as proof of diversity.', cluster: 'Content research', question: 'whether daily articles rely too heavily on the same publishers, evidence types, or upstream claims', finding: 'Source diversity is interpretable only when publishers, primary records, evidence types, claim roles, and upstream origins are distinguished.', method: 'Map every material claim in a fixed article sample to its cited publisher, original source where identifiable, evidence type, date, and argument role.', limit: 'Many URLs can repeat one dataset, while one authoritative primary source may appropriately support several related facts.', pilot: 'Review one week of articles, calculate concentration by publisher and upstream source, then inspect the most repeated claim category.' },
  { slug: 'virtual-assistant-exception-resolution-latency', title: 'How should exception-resolution latency be split across a virtual assistant workflow?', excerpt: 'An operating study separating preparation, waiting, owner decision, and execution time.', cluster: 'Operations research', question: 'where an exception actually waits after an assistant identifies it', finding: 'Elapsed time becomes actionable only after evidence preparation, queue waiting, owner deliberation, and post-decision execution are separated.', method: 'Timestamp detection, packet readiness, owner availability, decision request, decision, returned clarification, execution, and closure.', limit: 'Shorter time is not always safer; sensitive cases may require independent verification or deliberately slower approval.', pilot: 'Instrument one exception type for three weeks and compare stage durations before changing staffing or approval windows.' },
  { slug: 'assistant-sop-example-drift-detection', title: 'Can teams detect drift between assistant SOPs and training examples?', excerpt: 'A research design for finding when examples teach a different rule from the approved procedure.', cluster: 'Governance research', question: 'whether active examples remain consistent with the current SOP, authority table, and tool behavior', finding: 'Example drift is detectable when each example has an owner, governing rule, creation date, review date, scenario, and decision boundary.', method: 'Inventory examples used in one workflow, map instructions to the active SOP, and classify contradictions, missing scope, stale interfaces, and unauthorized exceptions.', limit: 'A different example is not necessarily wrong; legitimate scenario variation must be separated from a contradiction in authority or evidence.', pilot: 'Audit the ten most-used examples, remove or relabel stale items, then observe whether the same clarification questions recur.' },
];

const sources = [
  { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework', note: 'Governance and ownership context.' },
  { name: 'UK Government Service Manual: Measuring Success', url: 'https://www.gov.uk/service-manual/measuring-success', note: 'Measurement design.' },
  { name: 'OECD Measuring Productivity', url: 'https://www.oecd.org/en/topics/sub-issues/measuring-productivity.html', note: 'Definitions and interpretation limits.' },
];

const make = (s: Spec): ResearchPost => ({
  slug: s.slug, title: s.title, excerpt: s.excerpt, cluster: s.cluster,
  published: '2026-09-01', updated: '2026-09-01', headlineStat: s.finding,
  methodology: `Research question: ${s.question}. ${s.method} This is a bounded OutsourcingAssistant.com operating study, not a universal benchmark, causal claim, or evaluation based on nationality.`,
  keyStats: [s.finding, 'The eligible population and excluded states must be declared before calculation.', 'Preparation, waiting, and owner-decision time remain separate measures.'],
  takeaways: ['Define the operational decision before selecting a metric.', 'Preserve stopped, returned, waiting, and approved records.', 'Change one documented control after review, then observe another period.'],
  sections: [
    { heading: 'Frame the question and decision', paragraphs: [`The question is ${s.question}. State the queue, period, eligible records, exclusions, and person authorized to act before collection begins.`, 'A Philippines-based assistant may maintain observations and flag gaps. The owner decides whether cases are comparable and whether evidence supports a change.'], rows: [{ label: 'Question', value: s.question, source: 'Local study protocol' }, { label: 'Owner', value: 'Person authorized to change the observed workflow', source: 'NIST governance context' }] },
    { heading: 'Collect a reconstructable record', paragraphs: [s.method, 'Keep observations beside source fields and prior states so a later reviewer can reconstruct the case without relying on memory.'], rows: [{ label: 'Minimum record', value: 'Item, state, timestamp, source, owner, reason, disposition', source: 'UK Government measurement guidance' }, { label: 'Publication date', value: 'September 1, 2026', source: 'OutsourcingAssistant.com batch record' }] },
    { heading: 'Interpret the finding narrowly', paragraphs: [s.finding, s.limit], rows: [{ label: 'Supported use', value: 'Improve the defined local workflow', source: 'This study design' }, { label: 'Unsupported use', value: 'Universal ranking or causal attribution', source: 'OECD measurement limits' }] },
    { heading: 'Run a controlled pilot', paragraphs: [s.pilot, 'Preserve the baseline, changed rule, window, and result. Stop interpretation when missing cases could reverse the conclusion.'], rows: [{ label: 'Pilot', value: s.pilot, source: 'Local operating proposal' }, { label: 'Stop rule', value: 'Pause when missing or incomparable cases could materially change the result', source: 'Research governance analysis' }] },
    { heading: 'Conclusion and limitations', paragraphs: [`The defensible conclusion is modest: ${s.finding.toLowerCase()} This can guide a local adjustment but cannot isolate every influence.`, 'The assistant can collect evidence and prepare comparisons. The accountable owner retains access, policy, personnel, customer-impact, and public-claim decisions.'], rows: [{ label: 'Conclusion', value: s.finding, source: 'Source synthesis' }, { label: 'Primary limitation', value: s.limit, source: 'Scope analysis' }] },
  ],
  faqs: [{ q: 'Does this produce a universal benchmark?', a: 'No. It describes a defined local queue and period; comparisons require compatible populations and methods.' }, { q: 'What can the assistant own?', a: 'The assistant can maintain observations and prepare analysis. An authorized owner decides policy, access, and consequential interpretation.' }],
  sources, related: ['assistant-quality-scorecard', 'time-zone-handoff-design', 'claim-scope-provenance'], body: [],
});

export const researchBatch20260901: readonly ResearchPost[] = specs.map(make);
